### YamlMime:ManagedReference
items:
- uid: ToSic.Cre8magic.Settings.PairOnOffExtensions
  commentId: T:ToSic.Cre8magic.Settings.PairOnOffExtensions
  id: PairOnOffExtensions
  parent: ToSic.Cre8magic.Settings
  children:
  - ToSic.Cre8magic.Settings.PairOnOffExtensions.Get(ToSic.Cre8magic.Settings.MagicSettingOnOff,System.Nullable{System.Boolean})
  langs:
  - csharp
  - vb
  name: PairOnOffExtensions
  nameWithType: PairOnOffExtensions
  fullName: ToSic.Cre8magic.Settings.PairOnOffExtensions
  type: Class
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/MagicSettingOnOff.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: PairOnOffExtensions
    path: ../ToSic.Cre8Magic.Client/Settings/MagicSettingOnOff.cs
    startLine: 44
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings
  syntax:
    content: public static class PairOnOffExtensions
    content.vb: Public Module PairOnOffExtensions
  inheritance:
  - System.Object
- uid: ToSic.Cre8magic.Settings.PairOnOffExtensions.Get(ToSic.Cre8magic.Settings.MagicSettingOnOff,System.Nullable{System.Boolean})
  commentId: M:ToSic.Cre8magic.Settings.PairOnOffExtensions.Get(ToSic.Cre8magic.Settings.MagicSettingOnOff,System.Nullable{System.Boolean})
  id: Get(ToSic.Cre8magic.Settings.MagicSettingOnOff,System.Nullable{System.Boolean})
  isExtensionMethod: true
  parent: ToSic.Cre8magic.Settings.PairOnOffExtensions
  langs:
  - csharp
  - vb
  name: Get(MagicSettingOnOff?, bool?)
  nameWithType: PairOnOffExtensions.Get(MagicSettingOnOff?, bool?)
  fullName: ToSic.Cre8magic.Settings.PairOnOffExtensions.Get(ToSic.Cre8magic.Settings.MagicSettingOnOff?, bool?)
  type: Method
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/MagicSettingOnOff.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: Get
    path: ../ToSic.Cre8Magic.Client/Settings/MagicSettingOnOff.cs
    startLine: 52
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings
  summary: Null-safe pair access
  example: []
  syntax:
    content: public static string? Get(this MagicSettingOnOff? pair, bool? isOn)
    parameters:
    - id: pair
      type: ToSic.Cre8magic.Settings.MagicSettingOnOff
      description: ''
    - id: isOn
      type: System.Nullable{System.Boolean}
      description: ''
    return:
      type: System.String
      description: ''
    content.vb: Public Shared Function [Get](pair As MagicSettingOnOff, isOn As Boolean?) As String
  overload: ToSic.Cre8magic.Settings.PairOnOffExtensions.Get*
  nameWithType.vb: PairOnOffExtensions.Get(MagicSettingOnOff, Boolean?)
  fullName.vb: ToSic.Cre8magic.Settings.PairOnOffExtensions.Get(ToSic.Cre8magic.Settings.MagicSettingOnOff, Boolean?)
  name.vb: Get(MagicSettingOnOff, Boolean?)
references:
- uid: ToSic.Cre8magic.Settings
  commentId: N:ToSic.Cre8magic.Settings
  href: ToSic.html
  name: ToSic.Cre8magic.Settings
  nameWithType: ToSic.Cre8magic.Settings
  fullName: ToSic.Cre8magic.Settings
  spec.csharp:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
  spec.vb:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: ToSic.Cre8magic.Settings.PairOnOffExtensions.Get*
  commentId: Overload:ToSic.Cre8magic.Settings.PairOnOffExtensions.Get
  href: ToSic.Cre8magic.Settings.PairOnOffExtensions.html#ToSic_Cre8magic_Settings_PairOnOffExtensions_Get_ToSic_Cre8magic_Settings_MagicSettingOnOff_System_Nullable_System_Boolean__
  name: Get
  nameWithType: PairOnOffExtensions.Get
  fullName: ToSic.Cre8magic.Settings.PairOnOffExtensions.Get
- uid: ToSic.Cre8magic.Settings.MagicSettingOnOff
  commentId: T:ToSic.Cre8magic.Settings.MagicSettingOnOff
  parent: ToSic.Cre8magic.Settings
  href: ToSic.Cre8magic.Settings.MagicSettingOnOff.html
  name: MagicSettingOnOff
  nameWithType: MagicSettingOnOff
  fullName: ToSic.Cre8magic.Settings.MagicSettingOnOff
- uid: System.Nullable{System.Boolean}
  commentId: T:System.Nullable{System.Boolean}
  parent: System
  definition: System.Nullable`1
  name: bool?
  nameWithType: bool?
  fullName: bool?
  nameWithType.vb: Boolean?
  fullName.vb: Boolean?
  name.vb: Boolean?
  spec.csharp:
  - uid: System.Boolean
    name: bool
    isExternal: true
  - name: '?'
  spec.vb:
  - uid: System.Boolean
    name: Boolean
    isExternal: true
  - name: '?'
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: System.Nullable`1
  commentId: T:System.Nullable`1
  isExternal: true
  name: Nullable<T>
  nameWithType: Nullable<T>
  fullName: System.Nullable<T>
  nameWithType.vb: Nullable(Of T)
  fullName.vb: System.Nullable(Of T)
  name.vb: Nullable(Of T)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    isExternal: true
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
