### YamlMime:ManagedReference
items:
- uid: ToSic.Cre8magic.PageContext.MagicPageContextSettings
  commentId: T:ToSic.Cre8magic.PageContext.MagicPageContextSettings
  id: MagicPageContextSettings
  parent: ToSic.Cre8magic.PageContext
  children:
  - ToSic.Cre8magic.PageContext.MagicPageContextSettings.Classes
  - ToSic.Cre8magic.PageContext.MagicPageContextSettings.TagId
  - ToSic.Cre8magic.PageContext.MagicPageContextSettings.UseBodyTag
  langs:
  - csharp
  - vb
  name: MagicPageContextSettings
  nameWithType: MagicPageContextSettings
  fullName: ToSic.Cre8magic.PageContext.MagicPageContextSettings
  type: Class
  source:
    remote:
      path: ToSic.Cre8Magic.Client/PageContext/MagicPageContextSettings.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: MagicPageContextSettings
    path: ../ToSic.Cre8Magic.Client/PageContext/MagicPageContextSettings.cs
    startLine: 2
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.PageContext
  syntax:
    content: public record MagicPageContextSettings
    content.vb: Public Class MagicPageContextSettings
  inheritance:
  - System.Object
- uid: ToSic.Cre8magic.PageContext.MagicPageContextSettings.UseBodyTag
  commentId: P:ToSic.Cre8magic.PageContext.MagicPageContextSettings.UseBodyTag
  id: UseBodyTag
  parent: ToSic.Cre8magic.PageContext.MagicPageContextSettings
  langs:
  - csharp
  - vb
  name: UseBodyTag
  nameWithType: MagicPageContextSettings.UseBodyTag
  fullName: ToSic.Cre8magic.PageContext.MagicPageContextSettings.UseBodyTag
  type: Property
  source:
    remote:
      path: ToSic.Cre8Magic.Client/PageContext/MagicPageContextSettings.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: UseBodyTag
    path: ../ToSic.Cre8Magic.Client/PageContext/MagicPageContextSettings.cs
    startLine: 4
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.PageContext
  syntax:
    content: public bool? UseBodyTag { get; init; }
    parameters: []
    return:
      type: System.Nullable{System.Boolean}
    content.vb: Public Property UseBodyTag As Boolean?
  overload: ToSic.Cre8magic.PageContext.MagicPageContextSettings.UseBodyTag*
- uid: ToSic.Cre8magic.PageContext.MagicPageContextSettings.Classes
  commentId: P:ToSic.Cre8magic.PageContext.MagicPageContextSettings.Classes
  id: Classes
  parent: ToSic.Cre8magic.PageContext.MagicPageContextSettings
  langs:
  - csharp
  - vb
  name: Classes
  nameWithType: MagicPageContextSettings.Classes
  fullName: ToSic.Cre8magic.PageContext.MagicPageContextSettings.Classes
  type: Property
  source:
    remote:
      path: ToSic.Cre8Magic.Client/PageContext/MagicPageContextSettings.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: Classes
    path: ../ToSic.Cre8Magic.Client/PageContext/MagicPageContextSettings.cs
    startLine: 6
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.PageContext
  syntax:
    content: public string? Classes { get; init; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Classes As String
  overload: ToSic.Cre8magic.PageContext.MagicPageContextSettings.Classes*
- uid: ToSic.Cre8magic.PageContext.MagicPageContextSettings.TagId
  commentId: P:ToSic.Cre8magic.PageContext.MagicPageContextSettings.TagId
  id: TagId
  parent: ToSic.Cre8magic.PageContext.MagicPageContextSettings
  langs:
  - csharp
  - vb
  name: TagId
  nameWithType: MagicPageContextSettings.TagId
  fullName: ToSic.Cre8magic.PageContext.MagicPageContextSettings.TagId
  type: Property
  source:
    remote:
      path: ToSic.Cre8Magic.Client/PageContext/MagicPageContextSettings.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: TagId
    path: ../ToSic.Cre8Magic.Client/PageContext/MagicPageContextSettings.cs
    startLine: 8
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.PageContext
  syntax:
    content: public string? TagId { get; init; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property TagId As String
  overload: ToSic.Cre8magic.PageContext.MagicPageContextSettings.TagId*
references:
- uid: ToSic.Cre8magic.PageContext
  commentId: N:ToSic.Cre8magic.PageContext
  href: ToSic.html
  name: ToSic.Cre8magic.PageContext
  nameWithType: ToSic.Cre8magic.PageContext
  fullName: ToSic.Cre8magic.PageContext
  spec.csharp:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.PageContext
    name: PageContext
    href: ToSic.Cre8magic.PageContext.html
  spec.vb:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.PageContext
    name: PageContext
    href: ToSic.Cre8magic.PageContext.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: ToSic.Cre8magic.PageContext.MagicPageContextSettings.UseBodyTag*
  commentId: Overload:ToSic.Cre8magic.PageContext.MagicPageContextSettings.UseBodyTag
  href: ToSic.Cre8magic.PageContext.MagicPageContextSettings.html#ToSic_Cre8magic_PageContext_MagicPageContextSettings_UseBodyTag
  name: UseBodyTag
  nameWithType: MagicPageContextSettings.UseBodyTag
  fullName: ToSic.Cre8magic.PageContext.MagicPageContextSettings.UseBodyTag
- uid: System.Nullable{System.Boolean}
  commentId: T:System.Nullable{System.Boolean}
  parent: System
  definition: System.Nullable`1
  name: bool?
  nameWithType: bool?
  fullName: bool?
  nameWithType.vb: Boolean?
  fullName.vb: Boolean?
  name.vb: Boolean?
  spec.csharp:
  - uid: System.Boolean
    name: bool
    isExternal: true
  - name: '?'
  spec.vb:
  - uid: System.Boolean
    name: Boolean
    isExternal: true
  - name: '?'
- uid: System.Nullable`1
  commentId: T:System.Nullable`1
  isExternal: true
  name: Nullable<T>
  nameWithType: Nullable<T>
  fullName: System.Nullable<T>
  nameWithType.vb: Nullable(Of T)
  fullName.vb: System.Nullable(Of T)
  name.vb: Nullable(Of T)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    isExternal: true
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: ToSic.Cre8magic.PageContext.MagicPageContextSettings.Classes*
  commentId: Overload:ToSic.Cre8magic.PageContext.MagicPageContextSettings.Classes
  href: ToSic.Cre8magic.PageContext.MagicPageContextSettings.html#ToSic_Cre8magic_PageContext_MagicPageContextSettings_Classes
  name: Classes
  nameWithType: MagicPageContextSettings.Classes
  fullName: ToSic.Cre8magic.PageContext.MagicPageContextSettings.Classes
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: ToSic.Cre8magic.PageContext.MagicPageContextSettings.TagId*
  commentId: Overload:ToSic.Cre8magic.PageContext.MagicPageContextSettings.TagId
  href: ToSic.Cre8magic.PageContext.MagicPageContextSettings.html#ToSic_Cre8magic_PageContext_MagicPageContextSettings_TagId
  name: TagId
  nameWithType: MagicPageContextSettings.TagId
  fullName: ToSic.Cre8magic.PageContext.MagicPageContextSettings.TagId
