### YamlMime:ManagedReference
items:
- uid: ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart
  commentId: T:ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart
  id: MagicBreadcrumbDesignSettingsPart
  parent: ToSic.Cre8magic.Breadcrumbs
  children:
  - ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart.#ctor
  - ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart.#ctor(ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart,ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart)
  - ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart.CloneUnder(ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart,System.Boolean)
  - ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart.HasChildren
  - ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart.IsDisabled
  langs:
  - csharp
  - vb
  name: MagicBreadcrumbDesignSettingsPart
  nameWithType: MagicBreadcrumbDesignSettingsPart
  fullName: ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart
  type: Class
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Breadcrumbs/MagicBreadcrumbDesignSettingsPart.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: MagicBreadcrumbDesignSettingsPart
    path: ../ToSic.Cre8Magic.Client/Breadcrumbs/MagicBreadcrumbDesignSettingsPart.cs
    startLine: 5
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Breadcrumbs
  syntax:
    content: 'public record MagicBreadcrumbDesignSettingsPart : MagicDesignSettingsPart'
    content.vb: Public Class MagicBreadcrumbDesignSettingsPart Inherits MagicDesignSettingsPart
  inheritance:
  - System.Object
  - ToSic.Cre8magic.Settings.MagicDesignSettingsPart
  inheritedMembers:
  - ToSic.Cre8magic.Settings.MagicDesignSettingsPart.Classes
  - ToSic.Cre8magic.Settings.MagicDesignSettingsPart.Value
  - ToSic.Cre8magic.Settings.MagicDesignSettingsPart.Id
  - ToSic.Cre8magic.Settings.MagicDesignSettingsPart.IsActive
  - ToSic.Cre8magic.Settings.MagicDesignSettingsPart.IsPublished
  - ToSic.Cre8magic.Settings.MagicDesignSettingsPart.IsAdmin
- uid: ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart.#ctor
  commentId: M:ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart.#ctor
  id: '#ctor'
  parent: ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart
  langs:
  - csharp
  - vb
  name: MagicBreadcrumbDesignSettingsPart()
  nameWithType: MagicBreadcrumbDesignSettingsPart.MagicBreadcrumbDesignSettingsPart()
  fullName: ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart.MagicBreadcrumbDesignSettingsPart()
  type: Constructor
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Breadcrumbs/MagicBreadcrumbDesignSettingsPart.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: .ctor
    path: ../ToSic.Cre8Magic.Client/Breadcrumbs/MagicBreadcrumbDesignSettingsPart.cs
    startLine: 7
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Breadcrumbs
  syntax:
    content: public MagicBreadcrumbDesignSettingsPart()
    content.vb: Public Sub New()
  overload: ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart.#ctor*
  nameWithType.vb: MagicBreadcrumbDesignSettingsPart.New()
  fullName.vb: ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart.New()
  name.vb: New()
- uid: ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart.#ctor(ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart,ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart)
  commentId: M:ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart.#ctor(ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart,ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart)
  id: '#ctor(ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart,ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart)'
  parent: ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart
  langs:
  - csharp
  - vb
  name: MagicBreadcrumbDesignSettingsPart(MagicBreadcrumbDesignSettingsPart?, MagicBreadcrumbDesignSettingsPart?)
  nameWithType: MagicBreadcrumbDesignSettingsPart.MagicBreadcrumbDesignSettingsPart(MagicBreadcrumbDesignSettingsPart?, MagicBreadcrumbDesignSettingsPart?)
  fullName: ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart.MagicBreadcrumbDesignSettingsPart(ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart?, ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart?)
  type: Constructor
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Breadcrumbs/MagicBreadcrumbDesignSettingsPart.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: .ctor
    path: ../ToSic.Cre8Magic.Client/Breadcrumbs/MagicBreadcrumbDesignSettingsPart.cs
    startLine: 9
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Breadcrumbs
  syntax:
    content: public MagicBreadcrumbDesignSettingsPart(MagicBreadcrumbDesignSettingsPart? priority, MagicBreadcrumbDesignSettingsPart? fallback = null)
    parameters:
    - id: priority
      type: ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart
    - id: fallback
      type: ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart
    content.vb: Public Sub New(priority As MagicBreadcrumbDesignSettingsPart, fallback As MagicBreadcrumbDesignSettingsPart = Nothing)
  overload: ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart.#ctor*
  nameWithType.vb: MagicBreadcrumbDesignSettingsPart.New(MagicBreadcrumbDesignSettingsPart, MagicBreadcrumbDesignSettingsPart)
  fullName.vb: ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart.New(ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart, ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart)
  name.vb: New(MagicBreadcrumbDesignSettingsPart, MagicBreadcrumbDesignSettingsPart)
- uid: ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart.CloneUnder(ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart,System.Boolean)
  commentId: M:ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart.CloneUnder(ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart,System.Boolean)
  id: CloneUnder(ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart,System.Boolean)
  parent: ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart
  langs:
  - csharp
  - vb
  name: CloneUnder(MagicBreadcrumbDesignSettingsPart?, bool)
  nameWithType: MagicBreadcrumbDesignSettingsPart.CloneUnder(MagicBreadcrumbDesignSettingsPart?, bool)
  fullName: ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart.CloneUnder(ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart?, bool)
  type: Method
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Breadcrumbs/MagicBreadcrumbDesignSettingsPart.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: CloneUnder
    path: ../ToSic.Cre8Magic.Client/Breadcrumbs/MagicBreadcrumbDesignSettingsPart.cs
    startLine: 16
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Breadcrumbs
  example: []
  syntax:
    content: public MagicBreadcrumbDesignSettingsPart CloneUnder(MagicBreadcrumbDesignSettingsPart? priority, bool forceCopy = false)
    parameters:
    - id: priority
      type: ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart
    - id: forceCopy
      type: System.Boolean
    return:
      type: ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart
    content.vb: Public Function CloneUnder(priority As MagicBreadcrumbDesignSettingsPart, forceCopy As Boolean = False) As MagicBreadcrumbDesignSettingsPart
  overload: ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart.CloneUnder*
  nameWithType.vb: MagicBreadcrumbDesignSettingsPart.CloneUnder(MagicBreadcrumbDesignSettingsPart, Boolean)
  fullName.vb: ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart.CloneUnder(ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart, Boolean)
  name.vb: CloneUnder(MagicBreadcrumbDesignSettingsPart, Boolean)
- uid: ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart.HasChildren
  commentId: P:ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart.HasChildren
  id: HasChildren
  parent: ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart
  langs:
  - csharp
  - vb
  name: HasChildren
  nameWithType: MagicBreadcrumbDesignSettingsPart.HasChildren
  fullName: ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart.HasChildren
  type: Property
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Breadcrumbs/MagicBreadcrumbDesignSettingsPart.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: HasChildren
    path: ../ToSic.Cre8Magic.Client/Breadcrumbs/MagicBreadcrumbDesignSettingsPart.cs
    startLine: 29
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Breadcrumbs
  summary: Classes to add if this node is a parent (has-children).
  example: []
  syntax:
    content: public PairOnOff? HasChildren { get; init; }
    parameters: []
    return:
      type: ToSic.Cre8magic.Settings.PairOnOff
    content.vb: Public Property HasChildren As PairOnOff
  overload: ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart.HasChildren*
- uid: ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart.IsDisabled
  commentId: P:ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart.IsDisabled
  id: IsDisabled
  parent: ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart
  langs:
  - csharp
  - vb
  name: IsDisabled
  nameWithType: MagicBreadcrumbDesignSettingsPart.IsDisabled
  fullName: ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart.IsDisabled
  type: Property
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Breadcrumbs/MagicBreadcrumbDesignSettingsPart.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: IsDisabled
    path: ../ToSic.Cre8Magic.Client/Breadcrumbs/MagicBreadcrumbDesignSettingsPart.cs
    startLine: 35
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Breadcrumbs
  summary: >-
    Classes to add if the node is disabled.

    TODO: unclear why it's disabled, what would cause this...
  example: []
  syntax:
    content: public PairOnOff? IsDisabled { get; init; }
    parameters: []
    return:
      type: ToSic.Cre8magic.Settings.PairOnOff
    content.vb: Public Property IsDisabled As PairOnOff
  overload: ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart.IsDisabled*
references:
- uid: ToSic.Cre8magic.Breadcrumbs
  commentId: N:ToSic.Cre8magic.Breadcrumbs
  href: ToSic.html
  name: ToSic.Cre8magic.Breadcrumbs
  nameWithType: ToSic.Cre8magic.Breadcrumbs
  fullName: ToSic.Cre8magic.Breadcrumbs
  spec.csharp:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Breadcrumbs
    name: Breadcrumbs
    href: ToSic.Cre8magic.Breadcrumbs.html
  spec.vb:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Breadcrumbs
    name: Breadcrumbs
    href: ToSic.Cre8magic.Breadcrumbs.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: ToSic.Cre8magic.Settings.MagicDesignSettingsPart
  commentId: T:ToSic.Cre8magic.Settings.MagicDesignSettingsPart
  parent: ToSic.Cre8magic.Settings
  href: ToSic.Cre8magic.Settings.MagicDesignSettingsPart.html
  name: MagicDesignSettingsPart
  nameWithType: MagicDesignSettingsPart
  fullName: ToSic.Cre8magic.Settings.MagicDesignSettingsPart
- uid: ToSic.Cre8magic.Settings.MagicDesignSettingsPart.Classes
  commentId: P:ToSic.Cre8magic.Settings.MagicDesignSettingsPart.Classes
  parent: ToSic.Cre8magic.Settings.MagicDesignSettingsPart
  href: ToSic.Cre8magic.Settings.MagicDesignSettingsPart.html#ToSic_Cre8magic_Settings_MagicDesignSettingsPart_Classes
  name: Classes
  nameWithType: MagicDesignSettingsPart.Classes
  fullName: ToSic.Cre8magic.Settings.MagicDesignSettingsPart.Classes
- uid: ToSic.Cre8magic.Settings.MagicDesignSettingsPart.Value
  commentId: P:ToSic.Cre8magic.Settings.MagicDesignSettingsPart.Value
  parent: ToSic.Cre8magic.Settings.MagicDesignSettingsPart
  href: ToSic.Cre8magic.Settings.MagicDesignSettingsPart.html#ToSic_Cre8magic_Settings_MagicDesignSettingsPart_Value
  name: Value
  nameWithType: MagicDesignSettingsPart.Value
  fullName: ToSic.Cre8magic.Settings.MagicDesignSettingsPart.Value
- uid: ToSic.Cre8magic.Settings.MagicDesignSettingsPart.Id
  commentId: P:ToSic.Cre8magic.Settings.MagicDesignSettingsPart.Id
  parent: ToSic.Cre8magic.Settings.MagicDesignSettingsPart
  href: ToSic.Cre8magic.Settings.MagicDesignSettingsPart.html#ToSic_Cre8magic_Settings_MagicDesignSettingsPart_Id
  name: Id
  nameWithType: MagicDesignSettingsPart.Id
  fullName: ToSic.Cre8magic.Settings.MagicDesignSettingsPart.Id
- uid: ToSic.Cre8magic.Settings.MagicDesignSettingsPart.IsActive
  commentId: P:ToSic.Cre8magic.Settings.MagicDesignSettingsPart.IsActive
  parent: ToSic.Cre8magic.Settings.MagicDesignSettingsPart
  href: ToSic.Cre8magic.Settings.MagicDesignSettingsPart.html#ToSic_Cre8magic_Settings_MagicDesignSettingsPart_IsActive
  name: IsActive
  nameWithType: MagicDesignSettingsPart.IsActive
  fullName: ToSic.Cre8magic.Settings.MagicDesignSettingsPart.IsActive
- uid: ToSic.Cre8magic.Settings.MagicDesignSettingsPart.IsPublished
  commentId: P:ToSic.Cre8magic.Settings.MagicDesignSettingsPart.IsPublished
  parent: ToSic.Cre8magic.Settings.MagicDesignSettingsPart
  href: ToSic.Cre8magic.Settings.MagicDesignSettingsPart.html#ToSic_Cre8magic_Settings_MagicDesignSettingsPart_IsPublished
  name: IsPublished
  nameWithType: MagicDesignSettingsPart.IsPublished
  fullName: ToSic.Cre8magic.Settings.MagicDesignSettingsPart.IsPublished
- uid: ToSic.Cre8magic.Settings.MagicDesignSettingsPart.IsAdmin
  commentId: P:ToSic.Cre8magic.Settings.MagicDesignSettingsPart.IsAdmin
  parent: ToSic.Cre8magic.Settings.MagicDesignSettingsPart
  href: ToSic.Cre8magic.Settings.MagicDesignSettingsPart.html#ToSic_Cre8magic_Settings_MagicDesignSettingsPart_IsAdmin
  name: IsAdmin
  nameWithType: MagicDesignSettingsPart.IsAdmin
  fullName: ToSic.Cre8magic.Settings.MagicDesignSettingsPart.IsAdmin
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: ToSic.Cre8magic.Settings
  commentId: N:ToSic.Cre8magic.Settings
  href: ToSic.html
  name: ToSic.Cre8magic.Settings
  nameWithType: ToSic.Cre8magic.Settings
  fullName: ToSic.Cre8magic.Settings
  spec.csharp:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
  spec.vb:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
- uid: ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart.#ctor*
  commentId: Overload:ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart.#ctor
  href: ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart.html#ToSic_Cre8magic_Breadcrumbs_MagicBreadcrumbDesignSettingsPart__ctor
  name: MagicBreadcrumbDesignSettingsPart
  nameWithType: MagicBreadcrumbDesignSettingsPart.MagicBreadcrumbDesignSettingsPart
  fullName: ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart.MagicBreadcrumbDesignSettingsPart
  nameWithType.vb: MagicBreadcrumbDesignSettingsPart.New
  fullName.vb: ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart.New
  name.vb: New
- uid: ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart
  commentId: T:ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart
  parent: ToSic.Cre8magic.Breadcrumbs
  href: ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart.html
  name: MagicBreadcrumbDesignSettingsPart
  nameWithType: MagicBreadcrumbDesignSettingsPart
  fullName: ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart
- uid: ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart.CloneUnder*
  commentId: Overload:ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart.CloneUnder
  href: ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart.html#ToSic_Cre8magic_Breadcrumbs_MagicBreadcrumbDesignSettingsPart_CloneUnder_ToSic_Cre8magic_Breadcrumbs_MagicBreadcrumbDesignSettingsPart_System_Boolean_
  name: CloneUnder
  nameWithType: MagicBreadcrumbDesignSettingsPart.CloneUnder
  fullName: ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart.CloneUnder
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart.HasChildren*
  commentId: Overload:ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart.HasChildren
  href: ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart.html#ToSic_Cre8magic_Breadcrumbs_MagicBreadcrumbDesignSettingsPart_HasChildren
  name: HasChildren
  nameWithType: MagicBreadcrumbDesignSettingsPart.HasChildren
  fullName: ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart.HasChildren
- uid: ToSic.Cre8magic.Settings.PairOnOff
  commentId: T:ToSic.Cre8magic.Settings.PairOnOff
  parent: ToSic.Cre8magic.Settings
  href: ToSic.Cre8magic.Settings.PairOnOff.html
  name: PairOnOff
  nameWithType: PairOnOff
  fullName: ToSic.Cre8magic.Settings.PairOnOff
- uid: ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart.IsDisabled*
  commentId: Overload:ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart.IsDisabled
  href: ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart.html#ToSic_Cre8magic_Breadcrumbs_MagicBreadcrumbDesignSettingsPart_IsDisabled
  name: IsDisabled
  nameWithType: MagicBreadcrumbDesignSettingsPart.IsDisabled
  fullName: ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbDesignSettingsPart.IsDisabled
