### YamlMime:ManagedReference
items:
- uid: ToSic.Cre8magic.Settings
  commentId: N:ToSic.Cre8magic.Settings
  id: Settings
  parent: ToSic.Cre8magic
  children:
  - ToSic.Cre8magic.Settings.Debug
  - ToSic.Cre8magic.Settings.DesignSetting
  - ToSic.Cre8magic.Settings.Internal
  - ToSic.Cre8magic.Settings.Json
  - ToSic.Cre8magic.Settings.MagicAllSettings
  - ToSic.Cre8magic.Settings.MagicPackageSettings
  - ToSic.Cre8magic.Settings.MagicSettingsCatalog
  - ToSic.Cre8magic.Settings.NamedSettings`1
  - ToSic.Cre8magic.Settings.PairOnOff
  - ToSic.Cre8magic.Settings.PairOnOffExtensions
  - ToSic.Cre8magic.Settings.SettingsWithInherit
  langs:
  - csharp
  - vb
  name: ToSic.Cre8magic.Settings
  nameWithType: ToSic.Cre8magic.Settings
  fullName: ToSic.Cre8magic.Settings
  type: Namespace
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
references:
- uid: ToSic.Cre8magic.Settings.Debug
  commentId: N:ToSic.Cre8magic.Settings.Debug
  href: ToSic.html
  name: ToSic.Cre8magic.Settings.Debug
  nameWithType: ToSic.Cre8magic.Settings.Debug
  fullName: ToSic.Cre8magic.Settings.Debug
  spec.csharp:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Debug
    name: Debug
    href: ToSic.Cre8magic.Settings.Debug.html
  spec.vb:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Debug
    name: Debug
    href: ToSic.Cre8magic.Settings.Debug.html
- uid: ToSic.Cre8magic.Settings.Internal
  commentId: N:ToSic.Cre8magic.Settings.Internal
  href: ToSic.html
  name: ToSic.Cre8magic.Settings.Internal
  nameWithType: ToSic.Cre8magic.Settings.Internal
  fullName: ToSic.Cre8magic.Settings.Internal
  spec.csharp:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Internal
    name: Internal
    href: ToSic.Cre8magic.Settings.Internal.html
  spec.vb:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Internal
    name: Internal
    href: ToSic.Cre8magic.Settings.Internal.html
- uid: ToSic.Cre8magic.Settings.Json
  commentId: N:ToSic.Cre8magic.Settings.Json
  href: ToSic.html
  name: ToSic.Cre8magic.Settings.Json
  nameWithType: ToSic.Cre8magic.Settings.Json
  fullName: ToSic.Cre8magic.Settings.Json
  spec.csharp:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Json
    name: Json
    href: ToSic.Cre8magic.Settings.Json.html
  spec.vb:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Json
    name: Json
    href: ToSic.Cre8magic.Settings.Json.html
- uid: ToSic.Cre8magic.Settings.DesignSetting
  commentId: T:ToSic.Cre8magic.Settings.DesignSetting
  parent: ToSic.Cre8magic.Settings
  href: ToSic.Cre8magic.Settings.DesignSetting.html
  name: DesignSetting
  nameWithType: DesignSetting
  fullName: ToSic.Cre8magic.Settings.DesignSetting
- uid: ToSic.Cre8magic.Settings.MagicAllSettings
  commentId: T:ToSic.Cre8magic.Settings.MagicAllSettings
  parent: ToSic.Cre8magic.Settings
  href: ToSic.Cre8magic.Settings.MagicAllSettings.html
  name: MagicAllSettings
  nameWithType: MagicAllSettings
  fullName: ToSic.Cre8magic.Settings.MagicAllSettings
- uid: ToSic.Cre8magic.Settings.MagicPackageSettings
  commentId: T:ToSic.Cre8magic.Settings.MagicPackageSettings
  parent: ToSic.Cre8magic.Settings
  href: ToSic.Cre8magic.Settings.MagicPackageSettings.html
  name: MagicPackageSettings
  nameWithType: MagicPackageSettings
  fullName: ToSic.Cre8magic.Settings.MagicPackageSettings
- uid: ToSic.Cre8magic.Settings.MagicSettingsCatalog
  commentId: T:ToSic.Cre8magic.Settings.MagicSettingsCatalog
  parent: ToSic.Cre8magic.Settings
  href: ToSic.Cre8magic.Settings.MagicSettingsCatalog.html
  name: MagicSettingsCatalog
  nameWithType: MagicSettingsCatalog
  fullName: ToSic.Cre8magic.Settings.MagicSettingsCatalog
- uid: ToSic.Cre8magic.Settings.NamedSettings`1
  commentId: T:ToSic.Cre8magic.Settings.NamedSettings`1
  parent: ToSic.Cre8magic.Settings
  href: ToSic.Cre8magic.Settings.NamedSettings-1.html
  name: NamedSettings<T>
  nameWithType: NamedSettings<T>
  fullName: ToSic.Cre8magic.Settings.NamedSettings<T>
  nameWithType.vb: NamedSettings(Of T)
  fullName.vb: ToSic.Cre8magic.Settings.NamedSettings(Of T)
  name.vb: NamedSettings(Of T)
  spec.csharp:
  - uid: ToSic.Cre8magic.Settings.NamedSettings`1
    name: NamedSettings
    href: ToSic.Cre8magic.Settings.NamedSettings-1.html
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: ToSic.Cre8magic.Settings.NamedSettings`1
    name: NamedSettings
    href: ToSic.Cre8magic.Settings.NamedSettings-1.html
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: ToSic.Cre8magic.Settings.PairOnOff
  commentId: T:ToSic.Cre8magic.Settings.PairOnOff
  parent: ToSic.Cre8magic.Settings
  href: ToSic.Cre8magic.Settings.PairOnOff.html
  name: PairOnOff
  nameWithType: PairOnOff
  fullName: ToSic.Cre8magic.Settings.PairOnOff
- uid: ToSic.Cre8magic.Settings.PairOnOffExtensions
  commentId: T:ToSic.Cre8magic.Settings.PairOnOffExtensions
  parent: ToSic.Cre8magic.Settings
  href: ToSic.Cre8magic.Settings.PairOnOffExtensions.html
  name: PairOnOffExtensions
  nameWithType: PairOnOffExtensions
  fullName: ToSic.Cre8magic.Settings.PairOnOffExtensions
- uid: ToSic.Cre8magic.Settings.SettingsWithInherit
  commentId: T:ToSic.Cre8magic.Settings.SettingsWithInherit
  parent: ToSic.Cre8magic.Settings
  href: ToSic.Cre8magic.Settings.SettingsWithInherit.html
  name: SettingsWithInherit
  nameWithType: SettingsWithInherit
  fullName: ToSic.Cre8magic.Settings.SettingsWithInherit
- uid: ToSic.Cre8magic.Settings
  commentId: N:ToSic.Cre8magic.Settings
  href: ToSic.html
  name: ToSic.Cre8magic.Settings
  nameWithType: ToSic.Cre8magic.Settings
  fullName: ToSic.Cre8magic.Settings
  spec.csharp:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
  spec.vb:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
