### YamlMime:ManagedReference
items:
- uid: ToSic.Cre8magic.Themes.Settings.MagicThemeBlueprint
  commentId: T:ToSic.Cre8magic.Themes.Settings.MagicThemeBlueprint
  id: MagicThemeBlueprint
  parent: ToSic.Cre8magic.Themes.Settings
  children:
  - ToSic.Cre8magic.Themes.Settings.MagicThemeBlueprint.PaneIsEmpty
  langs:
  - csharp
  - vb
  name: MagicThemeBlueprint
  nameWithType: MagicThemeBlueprint
  fullName: ToSic.Cre8magic.Themes.Settings.MagicThemeBlueprint
  type: Class
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Themes/Settings/MagicThemeBlueprint.Defaults.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: MagicThemeBlueprint
    path: ../ToSic.Cre8Magic.Client/Themes/Settings/MagicThemeBlueprint.Defaults.cs
    startLine: 4
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Themes.Settings
  summary: >-
    Constants and helpers related to creating Css and Css Classes.


    If you change these, you must also update the SCSS files.
  example: []
  syntax:
    content: 'public record MagicThemeBlueprint : MagicBlueprints'
    content.vb: Public Class MagicThemeBlueprint Inherits MagicBlueprints
  inheritance:
  - System.Object
  - ToSic.Cre8magic.Settings.SettingsWithInherit
  - ToSic.Cre8magic.Settings.MagicBlueprints
  inheritedMembers:
  - ToSic.Cre8magic.Settings.MagicBlueprints.Parts
  - ToSic.Cre8magic.Settings.SettingsWithInherit.Inherits
  - ToSic.Cre8magic.Settings.SettingsWithInherit.PickFirstNonZeroInt(System.Nullable{System.Int32}[])
- uid: ToSic.Cre8magic.Themes.Settings.MagicThemeBlueprint.PaneIsEmpty
  commentId: P:ToSic.Cre8magic.Themes.Settings.MagicThemeBlueprint.PaneIsEmpty
  id: PaneIsEmpty
  parent: ToSic.Cre8magic.Themes.Settings.MagicThemeBlueprint
  langs:
  - csharp
  - vb
  name: PaneIsEmpty
  nameWithType: MagicThemeBlueprint.PaneIsEmpty
  fullName: ToSic.Cre8magic.Themes.Settings.MagicThemeBlueprint.PaneIsEmpty
  type: Property
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Themes/Settings/MagicThemeBlueprint.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: PaneIsEmpty
    path: ../ToSic.Cre8Magic.Client/Themes/Settings/MagicThemeBlueprint.cs
    startLine: 25
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Themes.Settings
  syntax:
    content: public MagicSettingOnOff? PaneIsEmpty { get; init; }
    parameters: []
    return:
      type: ToSic.Cre8magic.Settings.MagicSettingOnOff
    content.vb: Public Property PaneIsEmpty As MagicSettingOnOff
  overload: ToSic.Cre8magic.Themes.Settings.MagicThemeBlueprint.PaneIsEmpty*
references:
- uid: ToSic.Cre8magic.Themes.Settings
  commentId: N:ToSic.Cre8magic.Themes.Settings
  href: ToSic.html
  name: ToSic.Cre8magic.Themes.Settings
  nameWithType: ToSic.Cre8magic.Themes.Settings
  fullName: ToSic.Cre8magic.Themes.Settings
  spec.csharp:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Themes
    name: Themes
    href: ToSic.Cre8magic.Themes.html
  - name: .
  - uid: ToSic.Cre8magic.Themes.Settings
    name: Settings
    href: ToSic.Cre8magic.Themes.Settings.html
  spec.vb:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Themes
    name: Themes
    href: ToSic.Cre8magic.Themes.html
  - name: .
  - uid: ToSic.Cre8magic.Themes.Settings
    name: Settings
    href: ToSic.Cre8magic.Themes.Settings.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: ToSic.Cre8magic.Settings.SettingsWithInherit
  commentId: T:ToSic.Cre8magic.Settings.SettingsWithInherit
  parent: ToSic.Cre8magic.Settings
  href: ToSic.Cre8magic.Settings.SettingsWithInherit.html
  name: SettingsWithInherit
  nameWithType: SettingsWithInherit
  fullName: ToSic.Cre8magic.Settings.SettingsWithInherit
- uid: ToSic.Cre8magic.Settings.MagicBlueprints
  commentId: T:ToSic.Cre8magic.Settings.MagicBlueprints
  parent: ToSic.Cre8magic.Settings
  href: ToSic.Cre8magic.Settings.MagicBlueprints.html
  name: MagicBlueprints
  nameWithType: MagicBlueprints
  fullName: ToSic.Cre8magic.Settings.MagicBlueprints
- uid: ToSic.Cre8magic.Settings.MagicBlueprints.Parts
  commentId: P:ToSic.Cre8magic.Settings.MagicBlueprints.Parts
  parent: ToSic.Cre8magic.Settings.MagicBlueprints
  href: ToSic.Cre8magic.Settings.MagicBlueprints.html#ToSic_Cre8magic_Settings_MagicBlueprints_Parts
  name: Parts
  nameWithType: MagicBlueprints.Parts
  fullName: ToSic.Cre8magic.Settings.MagicBlueprints.Parts
- uid: ToSic.Cre8magic.Settings.SettingsWithInherit.Inherits
  commentId: P:ToSic.Cre8magic.Settings.SettingsWithInherit.Inherits
  parent: ToSic.Cre8magic.Settings.SettingsWithInherit
  href: ToSic.Cre8magic.Settings.SettingsWithInherit.html#ToSic_Cre8magic_Settings_SettingsWithInherit_Inherits
  name: Inherits
  nameWithType: SettingsWithInherit.Inherits
  fullName: ToSic.Cre8magic.Settings.SettingsWithInherit.Inherits
- uid: ToSic.Cre8magic.Settings.SettingsWithInherit.PickFirstNonZeroInt(System.Nullable{System.Int32}[])
  commentId: M:ToSic.Cre8magic.Settings.SettingsWithInherit.PickFirstNonZeroInt(System.Nullable{System.Int32}[])
  parent: ToSic.Cre8magic.Settings.SettingsWithInherit
  isExternal: true
  href: ToSic.Cre8magic.Settings.SettingsWithInherit.html#ToSic_Cre8magic_Settings_SettingsWithInherit_PickFirstNonZeroInt_System_Nullable_System_Int32____
  name: PickFirstNonZeroInt(int?[])
  nameWithType: SettingsWithInherit.PickFirstNonZeroInt(int?[])
  fullName: ToSic.Cre8magic.Settings.SettingsWithInherit.PickFirstNonZeroInt(int?[])
  nameWithType.vb: SettingsWithInherit.PickFirstNonZeroInt(Integer?())
  fullName.vb: ToSic.Cre8magic.Settings.SettingsWithInherit.PickFirstNonZeroInt(Integer?())
  name.vb: PickFirstNonZeroInt(Integer?())
  spec.csharp:
  - uid: ToSic.Cre8magic.Settings.SettingsWithInherit.PickFirstNonZeroInt(System.Nullable{System.Int32}[])
    name: PickFirstNonZeroInt
    href: ToSic.Cre8magic.Settings.SettingsWithInherit.html#ToSic_Cre8magic_Settings_SettingsWithInherit_PickFirstNonZeroInt_System_Nullable_System_Int32____
  - name: (
  - uid: System.Int32
    name: int
    isExternal: true
  - name: '?'
  - name: '['
  - name: ']'
  - name: )
  spec.vb:
  - uid: ToSic.Cre8magic.Settings.SettingsWithInherit.PickFirstNonZeroInt(System.Nullable{System.Int32}[])
    name: PickFirstNonZeroInt
    href: ToSic.Cre8magic.Settings.SettingsWithInherit.html#ToSic_Cre8magic_Settings_SettingsWithInherit_PickFirstNonZeroInt_System_Nullable_System_Int32____
  - name: (
  - uid: System.Int32
    name: Integer
    isExternal: true
  - name: '?'
  - name: (
  - name: )
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: ToSic.Cre8magic.Settings
  commentId: N:ToSic.Cre8magic.Settings
  href: ToSic.html
  name: ToSic.Cre8magic.Settings
  nameWithType: ToSic.Cre8magic.Settings
  fullName: ToSic.Cre8magic.Settings
  spec.csharp:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
  spec.vb:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
- uid: ToSic.Cre8magic.Themes.Settings.MagicThemeBlueprint.PaneIsEmpty*
  commentId: Overload:ToSic.Cre8magic.Themes.Settings.MagicThemeBlueprint.PaneIsEmpty
  href: ToSic.Cre8magic.Themes.Settings.MagicThemeBlueprint.html#ToSic_Cre8magic_Themes_Settings_MagicThemeBlueprint_PaneIsEmpty
  name: PaneIsEmpty
  nameWithType: MagicThemeBlueprint.PaneIsEmpty
  fullName: ToSic.Cre8magic.Themes.Settings.MagicThemeBlueprint.PaneIsEmpty
- uid: ToSic.Cre8magic.Settings.MagicSettingOnOff
  commentId: T:ToSic.Cre8magic.Settings.MagicSettingOnOff
  parent: ToSic.Cre8magic.Settings
  href: ToSic.Cre8magic.Settings.MagicSettingOnOff.html
  name: MagicSettingOnOff
  nameWithType: MagicSettingOnOff
  fullName: ToSic.Cre8magic.Settings.MagicSettingOnOff
