### YamlMime:ManagedReference
items:
- uid: ToSic.Cre8magic.Settings.MagicPackageSettings
  commentId: T:ToSic.Cre8magic.Settings.MagicPackageSettings
  id: MagicPackageSettings
  parent: ToSic.Cre8magic.Settings
  children:
  - ToSic.Cre8magic.Settings.MagicPackageSettings.Defaults
  - ToSic.Cre8magic.Settings.MagicPackageSettings.PackageName
  - ToSic.Cre8magic.Settings.MagicPackageSettings.SettingsJsonFile
  - ToSic.Cre8magic.Settings.MagicPackageSettings.Url
  - ToSic.Cre8magic.Settings.MagicPackageSettings.WwwRoot
  langs:
  - csharp
  - vb
  name: MagicPackageSettings
  nameWithType: MagicPackageSettings
  fullName: ToSic.Cre8magic.Settings.MagicPackageSettings
  type: Class
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/MagicPackageSettings.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: MagicPackageSettings
    path: ../ToSic.Cre8Magic.Client/Settings/MagicPackageSettings.cs
    startLine: 10
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings
  summary: >-
    Settings for a Theme Package.


    It contains things like


    1. location of assets

    1. configuration for various parts like CSS
  example: []
  syntax:
    content: public record MagicPackageSettings
    content.vb: Public Class MagicPackageSettings
  inheritance:
  - System.Object
- uid: ToSic.Cre8magic.Settings.MagicPackageSettings.Defaults
  commentId: P:ToSic.Cre8magic.Settings.MagicPackageSettings.Defaults
  id: Defaults
  parent: ToSic.Cre8magic.Settings.MagicPackageSettings
  langs:
  - csharp
  - vb
  name: Defaults
  nameWithType: MagicPackageSettings.Defaults
  fullName: ToSic.Cre8magic.Settings.MagicPackageSettings.Defaults
  type: Property
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/MagicPackageSettings.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: Defaults
    path: ../ToSic.Cre8Magic.Client/Settings/MagicPackageSettings.cs
    startLine: 16
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings
  summary: >-
    All kinds of settings for the layout, how it should be etc.

    Should usually only serve as backup in case the JSON fails.
  example: []
  syntax:
    content: public MagicSettingsCatalog? Defaults { get; init; }
    parameters: []
    return:
      type: ToSic.Cre8magic.Settings.MagicSettingsCatalog
    content.vb: Public Property Defaults As MagicSettingsCatalog
  overload: ToSic.Cre8magic.Settings.MagicPackageSettings.Defaults*
- uid: ToSic.Cre8magic.Settings.MagicPackageSettings.WwwRoot
  commentId: P:ToSic.Cre8magic.Settings.MagicPackageSettings.WwwRoot
  id: WwwRoot
  parent: ToSic.Cre8magic.Settings.MagicPackageSettings
  langs:
  - csharp
  - vb
  name: WwwRoot
  nameWithType: MagicPackageSettings.WwwRoot
  fullName: ToSic.Cre8magic.Settings.MagicPackageSettings.WwwRoot
  type: Property
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/MagicPackageSettings.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: WwwRoot
    path: ../ToSic.Cre8Magic.Client/Settings/MagicPackageSettings.cs
    startLine: 18
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings
  syntax:
    content: public string WwwRoot { get; init; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property WwwRoot As String
  overload: ToSic.Cre8magic.Settings.MagicPackageSettings.WwwRoot*
- uid: ToSic.Cre8magic.Settings.MagicPackageSettings.SettingsJsonFile
  commentId: P:ToSic.Cre8magic.Settings.MagicPackageSettings.SettingsJsonFile
  id: SettingsJsonFile
  parent: ToSic.Cre8magic.Settings.MagicPackageSettings
  langs:
  - csharp
  - vb
  name: SettingsJsonFile
  nameWithType: MagicPackageSettings.SettingsJsonFile
  fullName: ToSic.Cre8magic.Settings.MagicPackageSettings.SettingsJsonFile
  type: Property
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/MagicPackageSettings.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: SettingsJsonFile
    path: ../ToSic.Cre8Magic.Client/Settings/MagicPackageSettings.cs
    startLine: 20
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings
  syntax:
    content: public string SettingsJsonFile { get; init; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property SettingsJsonFile As String
  overload: ToSic.Cre8magic.Settings.MagicPackageSettings.SettingsJsonFile*
- uid: ToSic.Cre8magic.Settings.MagicPackageSettings.PackageName
  commentId: P:ToSic.Cre8magic.Settings.MagicPackageSettings.PackageName
  id: PackageName
  parent: ToSic.Cre8magic.Settings.MagicPackageSettings
  langs:
  - csharp
  - vb
  name: PackageName
  nameWithType: MagicPackageSettings.PackageName
  fullName: ToSic.Cre8magic.Settings.MagicPackageSettings.PackageName
  type: Property
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/MagicPackageSettings.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: PackageName
    path: ../ToSic.Cre8Magic.Client/Settings/MagicPackageSettings.cs
    startLine: 22
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings
  syntax:
    content: public string PackageName { get; init; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property PackageName As String
  overload: ToSic.Cre8magic.Settings.MagicPackageSettings.PackageName*
- uid: ToSic.Cre8magic.Settings.MagicPackageSettings.Url
  commentId: P:ToSic.Cre8magic.Settings.MagicPackageSettings.Url
  id: Url
  parent: ToSic.Cre8magic.Settings.MagicPackageSettings
  langs:
  - csharp
  - vb
  name: Url
  nameWithType: MagicPackageSettings.Url
  fullName: ToSic.Cre8magic.Settings.MagicPackageSettings.Url
  type: Property
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/MagicPackageSettings.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: Url
    path: ../ToSic.Cre8Magic.Client/Settings/MagicPackageSettings.cs
    startLine: 24
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings
  syntax:
    content: public string Url { get; init; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Url As String
  overload: ToSic.Cre8magic.Settings.MagicPackageSettings.Url*
references:
- uid: ToSic.Cre8magic.Settings
  commentId: N:ToSic.Cre8magic.Settings
  href: ToSic.html
  name: ToSic.Cre8magic.Settings
  nameWithType: ToSic.Cre8magic.Settings
  fullName: ToSic.Cre8magic.Settings
  spec.csharp:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
  spec.vb:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: ToSic.Cre8magic.Settings.MagicPackageSettings.Defaults*
  commentId: Overload:ToSic.Cre8magic.Settings.MagicPackageSettings.Defaults
  href: ToSic.Cre8magic.Settings.MagicPackageSettings.html#ToSic_Cre8magic_Settings_MagicPackageSettings_Defaults
  name: Defaults
  nameWithType: MagicPackageSettings.Defaults
  fullName: ToSic.Cre8magic.Settings.MagicPackageSettings.Defaults
- uid: ToSic.Cre8magic.Settings.MagicSettingsCatalog
  commentId: T:ToSic.Cre8magic.Settings.MagicSettingsCatalog
  parent: ToSic.Cre8magic.Settings
  href: ToSic.Cre8magic.Settings.MagicSettingsCatalog.html
  name: MagicSettingsCatalog
  nameWithType: MagicSettingsCatalog
  fullName: ToSic.Cre8magic.Settings.MagicSettingsCatalog
- uid: ToSic.Cre8magic.Settings.MagicPackageSettings.WwwRoot*
  commentId: Overload:ToSic.Cre8magic.Settings.MagicPackageSettings.WwwRoot
  href: ToSic.Cre8magic.Settings.MagicPackageSettings.html#ToSic_Cre8magic_Settings_MagicPackageSettings_WwwRoot
  name: WwwRoot
  nameWithType: MagicPackageSettings.WwwRoot
  fullName: ToSic.Cre8magic.Settings.MagicPackageSettings.WwwRoot
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: ToSic.Cre8magic.Settings.MagicPackageSettings.SettingsJsonFile*
  commentId: Overload:ToSic.Cre8magic.Settings.MagicPackageSettings.SettingsJsonFile
  href: ToSic.Cre8magic.Settings.MagicPackageSettings.html#ToSic_Cre8magic_Settings_MagicPackageSettings_SettingsJsonFile
  name: SettingsJsonFile
  nameWithType: MagicPackageSettings.SettingsJsonFile
  fullName: ToSic.Cre8magic.Settings.MagicPackageSettings.SettingsJsonFile
- uid: ToSic.Cre8magic.Settings.MagicPackageSettings.PackageName*
  commentId: Overload:ToSic.Cre8magic.Settings.MagicPackageSettings.PackageName
  href: ToSic.Cre8magic.Settings.MagicPackageSettings.html#ToSic_Cre8magic_Settings_MagicPackageSettings_PackageName
  name: PackageName
  nameWithType: MagicPackageSettings.PackageName
  fullName: ToSic.Cre8magic.Settings.MagicPackageSettings.PackageName
- uid: ToSic.Cre8magic.Settings.MagicPackageSettings.Url*
  commentId: Overload:ToSic.Cre8magic.Settings.MagicPackageSettings.Url
  href: ToSic.Cre8magic.Settings.MagicPackageSettings.html#ToSic_Cre8magic_Settings_MagicPackageSettings_Url
  name: Url
  nameWithType: MagicPackageSettings.Url
  fullName: ToSic.Cre8magic.Settings.MagicPackageSettings.Url
