### YamlMime:ManagedReference
items:
- uid: ToSic.Cre8magic.Settings.Internal
  commentId: N:ToSic.Cre8magic.Settings.Internal
  id: Internal
  parent: ToSic.Cre8magic.Settings
  children:
  - ToSic.Cre8magic.Settings.Internal.ICanClone`1
  - ToSic.Cre8magic.Settings.Internal.IHasSettingsExceptions
  - ToSic.Cre8magic.Settings.Internal.MagicSettingsLoader
  - ToSic.Cre8magic.Settings.Internal.SettingsException
  langs:
  - csharp
  - vb
  name: ToSic.Cre8magic.Settings.Internal
  nameWithType: ToSic.Cre8magic.Settings.Internal
  fullName: ToSic.Cre8magic.Settings.Internal
  type: Namespace
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
references:
- uid: ToSic.Cre8magic.Settings.Internal.ICanClone`1
  commentId: T:ToSic.Cre8magic.Settings.Internal.ICanClone`1
  href: ToSic.Cre8magic.Settings.Internal.ICanClone-1.html
  name: ICanClone<T>
  nameWithType: ICanClone<T>
  fullName: ToSic.Cre8magic.Settings.Internal.ICanClone<T>
  nameWithType.vb: ICanClone(Of T)
  fullName.vb: ToSic.Cre8magic.Settings.Internal.ICanClone(Of T)
  name.vb: ICanClone(Of T)
  spec.csharp:
  - uid: ToSic.Cre8magic.Settings.Internal.ICanClone`1
    name: ICanClone
    href: ToSic.Cre8magic.Settings.Internal.ICanClone-1.html
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: ToSic.Cre8magic.Settings.Internal.ICanClone`1
    name: ICanClone
    href: ToSic.Cre8magic.Settings.Internal.ICanClone-1.html
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: ToSic.Cre8magic.Settings.Internal.IHasSettingsExceptions
  commentId: T:ToSic.Cre8magic.Settings.Internal.IHasSettingsExceptions
  parent: ToSic.Cre8magic.Settings.Internal
  href: ToSic.Cre8magic.Settings.Internal.IHasSettingsExceptions.html
  name: IHasSettingsExceptions
  nameWithType: IHasSettingsExceptions
  fullName: ToSic.Cre8magic.Settings.Internal.IHasSettingsExceptions
- uid: ToSic.Cre8magic.Settings.Internal.MagicSettingsLoader
  commentId: T:ToSic.Cre8magic.Settings.Internal.MagicSettingsLoader
  parent: ToSic.Cre8magic.Settings.Internal
  href: ToSic.Cre8magic.Settings.Internal.MagicSettingsLoader.html
  name: MagicSettingsLoader
  nameWithType: MagicSettingsLoader
  fullName: ToSic.Cre8magic.Settings.Internal.MagicSettingsLoader
- uid: ToSic.Cre8magic.Settings.Internal.SettingsException
  commentId: T:ToSic.Cre8magic.Settings.Internal.SettingsException
  href: ToSic.Cre8magic.Settings.Internal.SettingsException.html
  name: SettingsException
  nameWithType: SettingsException
  fullName: ToSic.Cre8magic.Settings.Internal.SettingsException
- uid: ToSic.Cre8magic.Settings.Internal
  commentId: N:ToSic.Cre8magic.Settings.Internal
  href: ToSic.html
  name: ToSic.Cre8magic.Settings.Internal
  nameWithType: ToSic.Cre8magic.Settings.Internal
  fullName: ToSic.Cre8magic.Settings.Internal
  spec.csharp:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Internal
    name: Internal
    href: ToSic.Cre8magic.Settings.Internal.html
  spec.vb:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Internal
    name: Internal
    href: ToSic.Cre8magic.Settings.Internal.html
