### YamlMime:ManagedReference
items:
- uid: ToSic.Cre8magic.Settings.Internal.Debug.MagicDebugState
  commentId: T:ToSic.Cre8magic.Settings.Internal.Debug.MagicDebugState
  id: MagicDebugState
  parent: ToSic.Cre8magic.Settings.Internal.Debug
  children:
  - ToSic.Cre8magic.Settings.Internal.Debug.MagicDebugState.Show
  langs:
  - csharp
  - vb
  name: MagicDebugState
  nameWithType: MagicDebugState
  fullName: ToSic.Cre8magic.Settings.Internal.Debug.MagicDebugState
  type: Class
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/Internal/Debug/MagicDebugState.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: MagicDebugState
    path: ../ToSic.Cre8Magic.Client/Settings/Internal/Debug/MagicDebugState.cs
    startLine: 5
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings.Internal.Debug
  summary: Current debug state - show/enabled yes no
  example: []
  syntax:
    content: public class MagicDebugState
    content.vb: Public Class MagicDebugState
  inheritance:
  - System.Object
- uid: ToSic.Cre8magic.Settings.Internal.Debug.MagicDebugState.Show
  commentId: P:ToSic.Cre8magic.Settings.Internal.Debug.MagicDebugState.Show
  id: Show
  parent: ToSic.Cre8magic.Settings.Internal.Debug.MagicDebugState
  langs:
  - csharp
  - vb
  name: Show
  nameWithType: MagicDebugState.Show
  fullName: ToSic.Cre8magic.Settings.Internal.Debug.MagicDebugState.Show
  type: Property
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/Internal/Debug/MagicDebugState.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: Show
    path: ../ToSic.Cre8Magic.Client/Settings/Internal/Debug/MagicDebugState.cs
    startLine: 7
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings.Internal.Debug
  syntax:
    content: public bool Show { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property Show As Boolean
  overload: ToSic.Cre8magic.Settings.Internal.Debug.MagicDebugState.Show*
references:
- uid: ToSic.Cre8magic.Settings.Internal.Debug
  commentId: N:ToSic.Cre8magic.Settings.Internal.Debug
  href: ToSic.html
  name: ToSic.Cre8magic.Settings.Internal.Debug
  nameWithType: ToSic.Cre8magic.Settings.Internal.Debug
  fullName: ToSic.Cre8magic.Settings.Internal.Debug
  spec.csharp:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Internal
    name: Internal
    href: ToSic.Cre8magic.Settings.Internal.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Internal.Debug
    name: Debug
    href: ToSic.Cre8magic.Settings.Internal.Debug.html
  spec.vb:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Internal
    name: Internal
    href: ToSic.Cre8magic.Settings.Internal.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Internal.Debug
    name: Debug
    href: ToSic.Cre8magic.Settings.Internal.Debug.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: ToSic.Cre8magic.Settings.Internal.Debug.MagicDebugState.Show*
  commentId: Overload:ToSic.Cre8magic.Settings.Internal.Debug.MagicDebugState.Show
  href: ToSic.Cre8magic.Settings.Internal.Debug.MagicDebugState.html#ToSic_Cre8magic_Settings_Internal_Debug_MagicDebugState_Show
  name: Show
  nameWithType: MagicDebugState.Show
  fullName: ToSic.Cre8magic.Settings.Internal.Debug.MagicDebugState.Show
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
