### YamlMime:ManagedReference
items:
- uid: ToSic.Cre8magic.Settings.Providers.Internal
  commentId: N:ToSic.Cre8magic.Settings.Providers.Internal
  id: Internal
  parent: ToSic.Cre8magic.Settings.Providers
  children:
  - ToSic.Cre8magic.Settings.Providers.Internal.IMagicProviderSectionWithMoreWip`2
  - ToSic.Cre8magic.Settings.Providers.Internal.MagicProviderSection`1
  - ToSic.Cre8magic.Settings.Providers.Internal.ProviderFindWip
  langs:
  - csharp
  - vb
  name: ToSic.Cre8magic.Settings.Providers.Internal
  nameWithType: ToSic.Cre8magic.Settings.Providers.Internal
  fullName: ToSic.Cre8magic.Settings.Providers.Internal
  type: Namespace
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
references:
- uid: ToSic.Cre8magic.Settings.Providers.Internal.IMagicProviderSectionWithMoreWip`2
  commentId: T:ToSic.Cre8magic.Settings.Providers.Internal.IMagicProviderSectionWithMoreWip`2
  href: ToSic.Cre8magic.Settings.Providers.Internal.IMagicProviderSectionWithMoreWip-2.html
  name: IMagicProviderSectionWithMoreWip<TSettings, TProvider>
  nameWithType: IMagicProviderSectionWithMoreWip<TSettings, TProvider>
  fullName: ToSic.Cre8magic.Settings.Providers.Internal.IMagicProviderSectionWithMoreWip<TSettings, TProvider>
  nameWithType.vb: IMagicProviderSectionWithMoreWip(Of TSettings, TProvider)
  fullName.vb: ToSic.Cre8magic.Settings.Providers.Internal.IMagicProviderSectionWithMoreWip(Of TSettings, TProvider)
  name.vb: IMagicProviderSectionWithMoreWip(Of TSettings, TProvider)
  spec.csharp:
  - uid: ToSic.Cre8magic.Settings.Providers.Internal.IMagicProviderSectionWithMoreWip`2
    name: IMagicProviderSectionWithMoreWip
    href: ToSic.Cre8magic.Settings.Providers.Internal.IMagicProviderSectionWithMoreWip-2.html
  - name: <
  - name: TSettings
  - name: ','
  - name: " "
  - name: TProvider
  - name: '>'
  spec.vb:
  - uid: ToSic.Cre8magic.Settings.Providers.Internal.IMagicProviderSectionWithMoreWip`2
    name: IMagicProviderSectionWithMoreWip
    href: ToSic.Cre8magic.Settings.Providers.Internal.IMagicProviderSectionWithMoreWip-2.html
  - name: (
  - name: Of
  - name: " "
  - name: TSettings
  - name: ','
  - name: " "
  - name: TProvider
  - name: )
- uid: ToSic.Cre8magic.Settings.Providers.Internal.MagicProviderSection`1
  commentId: T:ToSic.Cre8magic.Settings.Providers.Internal.MagicProviderSection`1
  href: ToSic.Cre8magic.Settings.Providers.Internal.MagicProviderSection-1.html
  name: MagicProviderSection<T>
  nameWithType: MagicProviderSection<T>
  fullName: ToSic.Cre8magic.Settings.Providers.Internal.MagicProviderSection<T>
  nameWithType.vb: MagicProviderSection(Of T)
  fullName.vb: ToSic.Cre8magic.Settings.Providers.Internal.MagicProviderSection(Of T)
  name.vb: MagicProviderSection(Of T)
  spec.csharp:
  - uid: ToSic.Cre8magic.Settings.Providers.Internal.MagicProviderSection`1
    name: MagicProviderSection
    href: ToSic.Cre8magic.Settings.Providers.Internal.MagicProviderSection-1.html
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: ToSic.Cre8magic.Settings.Providers.Internal.MagicProviderSection`1
    name: MagicProviderSection
    href: ToSic.Cre8magic.Settings.Providers.Internal.MagicProviderSection-1.html
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: ToSic.Cre8magic.Settings.Providers.Internal.ProviderFindWip
  commentId: T:ToSic.Cre8magic.Settings.Providers.Internal.ProviderFindWip
  parent: ToSic.Cre8magic.Settings.Providers.Internal
  href: ToSic.Cre8magic.Settings.Providers.Internal.ProviderFindWip.html
  name: ProviderFindWip
  nameWithType: ProviderFindWip
  fullName: ToSic.Cre8magic.Settings.Providers.Internal.ProviderFindWip
- uid: ToSic.Cre8magic.Settings.Providers.Internal
  commentId: N:ToSic.Cre8magic.Settings.Providers.Internal
  href: ToSic.html
  name: ToSic.Cre8magic.Settings.Providers.Internal
  nameWithType: ToSic.Cre8magic.Settings.Providers.Internal
  fullName: ToSic.Cre8magic.Settings.Providers.Internal
  spec.csharp:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Providers
    name: Providers
    href: ToSic.Cre8magic.Settings.Providers.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Providers.Internal
    name: Internal
    href: ToSic.Cre8magic.Settings.Providers.Internal.html
  spec.vb:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Providers
    name: Providers
    href: ToSic.Cre8magic.Settings.Providers.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Providers.Internal
    name: Internal
    href: ToSic.Cre8magic.Settings.Providers.Internal.html
