### YamlMime:ManagedReference
items:
- uid: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions
  commentId: T:ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions
  id: IDebugSettingsExtensions
  parent: ToSic.Cre8magic.Settings.Internal.Debug
  children:
  - ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.Debug``1(``0)
  - ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.UseCatalog``1(``0,ToSic.Cre8magic.Settings.MagicSettingsCatalog)
  - ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.UseLanguageSettings``1(``0,ToSic.Cre8magic.Languages.MagicLanguageSettings)
  langs:
  - csharp
  - vb
  name: IDebugSettingsExtensions
  nameWithType: IDebugSettingsExtensions
  fullName: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions
  type: Class
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/Internal/Debug/IDebugSettingsExtensions.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: IDebugSettingsExtensions
    path: ../ToSic.Cre8Magic.Client/Settings/Internal/Debug/IDebugSettingsExtensions.cs
    startLine: 2
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings.Internal.Debug
  syntax:
    content: public static class IDebugSettingsExtensions
    content.vb: Public Module IDebugSettingsExtensions
  inheritance:
  - System.Object
- uid: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.Debug``1(``0)
  commentId: M:ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.Debug``1(``0)
  id: Debug``1(``0)
  isExtensionMethod: true
  parent: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions
  langs:
  - csharp
  - vb
  name: Debug<T>(T)
  nameWithType: IDebugSettingsExtensions.Debug<T>(T)
  fullName: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.Debug<T>(T)
  type: Method
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/Internal/Debug/IDebugSettingsExtensions.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: Debug
    path: ../ToSic.Cre8Magic.Client/Settings/Internal/Debug/IDebugSettingsExtensions.cs
    startLine: 4
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings.Internal.Debug
  syntax:
    content: 'public static T Debug<T>(this T settings) where T : IDebugSettings'
    parameters:
    - id: settings
      type: '{T}'
    typeParameters:
    - id: T
    return:
      type: '{T}'
    content.vb: Public Shared Function Debug(Of T As IDebugSettings)(settings As T) As T
  overload: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.Debug*
  nameWithType.vb: IDebugSettingsExtensions.Debug(Of T)(T)
  fullName.vb: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.Debug(Of T)(T)
  name.vb: Debug(Of T)(T)
- uid: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.UseCatalog``1(``0,ToSic.Cre8magic.Settings.MagicSettingsCatalog)
  commentId: M:ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.UseCatalog``1(``0,ToSic.Cre8magic.Settings.MagicSettingsCatalog)
  id: UseCatalog``1(``0,ToSic.Cre8magic.Settings.MagicSettingsCatalog)
  isExtensionMethod: true
  parent: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions
  langs:
  - csharp
  - vb
  name: UseCatalog<T>(T, MagicSettingsCatalog)
  nameWithType: IDebugSettingsExtensions.UseCatalog<T>(T, MagicSettingsCatalog)
  fullName: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.UseCatalog<T>(T, ToSic.Cre8magic.Settings.MagicSettingsCatalog)
  type: Method
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/Internal/Debug/IDebugSettingsExtensions.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: UseCatalog
    path: ../ToSic.Cre8Magic.Client/Settings/Internal/Debug/IDebugSettingsExtensions.cs
    startLine: 10
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings.Internal.Debug
  syntax:
    content: 'public static T UseCatalog<T>(this T settings, MagicSettingsCatalog catalog) where T : IDebugSettings'
    parameters:
    - id: settings
      type: '{T}'
    - id: catalog
      type: ToSic.Cre8magic.Settings.MagicSettingsCatalog
    typeParameters:
    - id: T
    return:
      type: '{T}'
    content.vb: Public Shared Function UseCatalog(Of T As IDebugSettings)(settings As T, catalog As MagicSettingsCatalog) As T
  overload: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.UseCatalog*
  nameWithType.vb: IDebugSettingsExtensions.UseCatalog(Of T)(T, MagicSettingsCatalog)
  fullName.vb: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.UseCatalog(Of T)(T, ToSic.Cre8magic.Settings.MagicSettingsCatalog)
  name.vb: UseCatalog(Of T)(T, MagicSettingsCatalog)
- uid: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.UseLanguageSettings``1(``0,ToSic.Cre8magic.Languages.MagicLanguageSettings)
  commentId: M:ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.UseLanguageSettings``1(``0,ToSic.Cre8magic.Languages.MagicLanguageSettings)
  id: UseLanguageSettings``1(``0,ToSic.Cre8magic.Languages.MagicLanguageSettings)
  isExtensionMethod: true
  parent: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions
  langs:
  - csharp
  - vb
  name: UseLanguageSettings<T>(T, MagicLanguageSettings)
  nameWithType: IDebugSettingsExtensions.UseLanguageSettings<T>(T, MagicLanguageSettings)
  fullName: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.UseLanguageSettings<T>(T, ToSic.Cre8magic.Languages.MagicLanguageSettings)
  type: Method
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/Internal/Debug/IDebugSettingsExtensions.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: UseLanguageSettings
    path: ../ToSic.Cre8Magic.Client/Settings/Internal/Debug/IDebugSettingsExtensions.cs
    startLine: 16
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings.Internal.Debug
  syntax:
    content: 'public static T UseLanguageSettings<T>(this T settings, MagicLanguageSettings languageSettings) where T : IDebugSettings'
    parameters:
    - id: settings
      type: '{T}'
    - id: languageSettings
      type: ToSic.Cre8magic.Languages.MagicLanguageSettings
    typeParameters:
    - id: T
    return:
      type: '{T}'
    content.vb: Public Shared Function UseLanguageSettings(Of T As IDebugSettings)(settings As T, languageSettings As MagicLanguageSettings) As T
  overload: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.UseLanguageSettings*
  nameWithType.vb: IDebugSettingsExtensions.UseLanguageSettings(Of T)(T, MagicLanguageSettings)
  fullName.vb: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.UseLanguageSettings(Of T)(T, ToSic.Cre8magic.Languages.MagicLanguageSettings)
  name.vb: UseLanguageSettings(Of T)(T, MagicLanguageSettings)
references:
- uid: ToSic.Cre8magic.Settings.Internal.Debug
  commentId: N:ToSic.Cre8magic.Settings.Internal.Debug
  href: ToSic.html
  name: ToSic.Cre8magic.Settings.Internal.Debug
  nameWithType: ToSic.Cre8magic.Settings.Internal.Debug
  fullName: ToSic.Cre8magic.Settings.Internal.Debug
  spec.csharp:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Internal
    name: Internal
    href: ToSic.Cre8magic.Settings.Internal.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Internal.Debug
    name: Debug
    href: ToSic.Cre8magic.Settings.Internal.Debug.html
  spec.vb:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Internal
    name: Internal
    href: ToSic.Cre8magic.Settings.Internal.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Internal.Debug
    name: Debug
    href: ToSic.Cre8magic.Settings.Internal.Debug.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.Debug*
  commentId: Overload:ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.Debug
  href: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.html#ToSic_Cre8magic_Settings_Internal_Debug_IDebugSettingsExtensions_Debug__1___0_
  name: Debug
  nameWithType: IDebugSettingsExtensions.Debug
  fullName: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.Debug
- uid: '{T}'
  commentId: '!:T'
  definition: T
  name: T
  nameWithType: T
  fullName: T
- uid: T
  name: T
  nameWithType: T
  fullName: T
- uid: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.UseCatalog*
  commentId: Overload:ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.UseCatalog
  href: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.html#ToSic_Cre8magic_Settings_Internal_Debug_IDebugSettingsExtensions_UseCatalog__1___0_ToSic_Cre8magic_Settings_MagicSettingsCatalog_
  name: UseCatalog
  nameWithType: IDebugSettingsExtensions.UseCatalog
  fullName: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.UseCatalog
- uid: ToSic.Cre8magic.Settings.MagicSettingsCatalog
  commentId: T:ToSic.Cre8magic.Settings.MagicSettingsCatalog
  parent: ToSic.Cre8magic.Settings
  href: ToSic.Cre8magic.Settings.MagicSettingsCatalog.html
  name: MagicSettingsCatalog
  nameWithType: MagicSettingsCatalog
  fullName: ToSic.Cre8magic.Settings.MagicSettingsCatalog
- uid: ToSic.Cre8magic.Settings
  commentId: N:ToSic.Cre8magic.Settings
  href: ToSic.html
  name: ToSic.Cre8magic.Settings
  nameWithType: ToSic.Cre8magic.Settings
  fullName: ToSic.Cre8magic.Settings
  spec.csharp:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
  spec.vb:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
- uid: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.UseLanguageSettings*
  commentId: Overload:ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.UseLanguageSettings
  href: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.html#ToSic_Cre8magic_Settings_Internal_Debug_IDebugSettingsExtensions_UseLanguageSettings__1___0_ToSic_Cre8magic_Languages_MagicLanguageSettings_
  name: UseLanguageSettings
  nameWithType: IDebugSettingsExtensions.UseLanguageSettings
  fullName: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.UseLanguageSettings
- uid: ToSic.Cre8magic.Languages.MagicLanguageSettings
  commentId: T:ToSic.Cre8magic.Languages.MagicLanguageSettings
  parent: ToSic.Cre8magic.Languages
  href: ToSic.Cre8magic.Languages.MagicLanguageSettings.html
  name: MagicLanguageSettings
  nameWithType: MagicLanguageSettings
  fullName: ToSic.Cre8magic.Languages.MagicLanguageSettings
- uid: ToSic.Cre8magic.Languages
  commentId: N:ToSic.Cre8magic.Languages
  href: ToSic.html
  name: ToSic.Cre8magic.Languages
  nameWithType: ToSic.Cre8magic.Languages
  fullName: ToSic.Cre8magic.Languages
  spec.csharp:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Languages
    name: Languages
    href: ToSic.Cre8magic.Languages.html
  spec.vb:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Languages
    name: Languages
    href: ToSic.Cre8magic.Languages.html
