### YamlMime:ManagedReference
items:
- uid: ToSic.Cre8magic.Settings.MagicDebugSettings
  commentId: T:ToSic.Cre8magic.Settings.MagicDebugSettings
  id: MagicDebugSettings
  parent: ToSic.Cre8magic.Settings
  children:
  - ToSic.Cre8magic.Settings.MagicDebugSettings.#ctor(System.Boolean)
  - ToSic.Cre8magic.Settings.MagicDebugSettings.Admin
  - ToSic.Cre8magic.Settings.MagicDebugSettings.Allowed
  - ToSic.Cre8magic.Settings.MagicDebugSettings.Anonymous
  - ToSic.Cre8magic.Settings.MagicDebugSettings.Detailed
  langs:
  - csharp
  - vb
  name: MagicDebugSettings
  nameWithType: MagicDebugSettings
  fullName: ToSic.Cre8magic.Settings.MagicDebugSettings
  type: Class
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/MagicDebugSettings.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: MagicDebugSettings
    path: ../ToSic.Cre8Magic.Client/Settings/MagicDebugSettings.cs
    startLine: 11
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings
  summary: >-
    Debug settings to help during development.


    These settings can also be loaded from the configuration.

    This allows you to do things like enable temporarily for admins, without restarting/recompiling anything.
  example: []
  syntax:
    content: public record MagicDebugSettings
    content.vb: Public Class MagicDebugSettings
  inheritance:
  - System.Object
- uid: ToSic.Cre8magic.Settings.MagicDebugSettings.#ctor(System.Boolean)
  commentId: M:ToSic.Cre8magic.Settings.MagicDebugSettings.#ctor(System.Boolean)
  id: '#ctor(System.Boolean)'
  parent: ToSic.Cre8magic.Settings.MagicDebugSettings
  langs:
  - csharp
  - vb
  name: MagicDebugSettings(bool)
  nameWithType: MagicDebugSettings.MagicDebugSettings(bool)
  fullName: ToSic.Cre8magic.Settings.MagicDebugSettings.MagicDebugSettings(bool)
  type: Constructor
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/MagicDebugSettings.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: .ctor
    path: ../ToSic.Cre8Magic.Client/Settings/MagicDebugSettings.cs
    startLine: 21
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings
  summary: >-
    Create debug settings which set everything to the specified state.

    This is mainly for quick interventions, so you can just do `new(true)` to enable everything.
  example: []
  syntax:
    content: public MagicDebugSettings(bool enable)
    parameters:
    - id: enable
      type: System.Boolean
      description: ''
    content.vb: Public Sub New(enable As Boolean)
  overload: ToSic.Cre8magic.Settings.MagicDebugSettings.#ctor*
  nameWithType.vb: MagicDebugSettings.New(Boolean)
  fullName.vb: ToSic.Cre8magic.Settings.MagicDebugSettings.New(Boolean)
  name.vb: New(Boolean)
- uid: ToSic.Cre8magic.Settings.MagicDebugSettings.Allowed
  commentId: P:ToSic.Cre8magic.Settings.MagicDebugSettings.Allowed
  id: Allowed
  parent: ToSic.Cre8magic.Settings.MagicDebugSettings
  langs:
  - csharp
  - vb
  name: Allowed
  nameWithType: MagicDebugSettings.Allowed
  fullName: ToSic.Cre8magic.Settings.MagicDebugSettings.Allowed
  type: Property
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/MagicDebugSettings.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: Allowed
    path: ../ToSic.Cre8Magic.Client/Settings/MagicDebugSettings.cs
    startLine: 42
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings
  syntax:
    content: public bool? Allowed { get; init; }
    parameters: []
    return:
      type: System.Nullable{System.Boolean}
    content.vb: Public Property Allowed As Boolean?
  overload: ToSic.Cre8magic.Settings.MagicDebugSettings.Allowed*
- uid: ToSic.Cre8magic.Settings.MagicDebugSettings.Anonymous
  commentId: P:ToSic.Cre8magic.Settings.MagicDebugSettings.Anonymous
  id: Anonymous
  parent: ToSic.Cre8magic.Settings.MagicDebugSettings
  langs:
  - csharp
  - vb
  name: Anonymous
  nameWithType: MagicDebugSettings.Anonymous
  fullName: ToSic.Cre8magic.Settings.MagicDebugSettings.Anonymous
  type: Property
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/MagicDebugSettings.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: Anonymous
    path: ../ToSic.Cre8Magic.Client/Settings/MagicDebugSettings.cs
    startLine: 45
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings
  syntax:
    content: public bool? Anonymous { get; init; }
    parameters: []
    return:
      type: System.Nullable{System.Boolean}
    content.vb: Public Property Anonymous As Boolean?
  overload: ToSic.Cre8magic.Settings.MagicDebugSettings.Anonymous*
- uid: ToSic.Cre8magic.Settings.MagicDebugSettings.Admin
  commentId: P:ToSic.Cre8magic.Settings.MagicDebugSettings.Admin
  id: Admin
  parent: ToSic.Cre8magic.Settings.MagicDebugSettings
  langs:
  - csharp
  - vb
  name: Admin
  nameWithType: MagicDebugSettings.Admin
  fullName: ToSic.Cre8magic.Settings.MagicDebugSettings.Admin
  type: Property
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/MagicDebugSettings.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: Admin
    path: ../ToSic.Cre8Magic.Client/Settings/MagicDebugSettings.cs
    startLine: 48
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings
  syntax:
    content: public bool? Admin { get; init; }
    parameters: []
    return:
      type: System.Nullable{System.Boolean}
    content.vb: Public Property Admin As Boolean?
  overload: ToSic.Cre8magic.Settings.MagicDebugSettings.Admin*
- uid: ToSic.Cre8magic.Settings.MagicDebugSettings.Detailed
  commentId: P:ToSic.Cre8magic.Settings.MagicDebugSettings.Detailed
  id: Detailed
  parent: ToSic.Cre8magic.Settings.MagicDebugSettings
  langs:
  - csharp
  - vb
  name: Detailed
  nameWithType: MagicDebugSettings.Detailed
  fullName: ToSic.Cre8magic.Settings.MagicDebugSettings.Detailed
  type: Property
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/MagicDebugSettings.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: Detailed
    path: ../ToSic.Cre8Magic.Client/Settings/MagicDebugSettings.cs
    startLine: 51
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings
  syntax:
    content: public bool? Detailed { get; init; }
    parameters: []
    return:
      type: System.Nullable{System.Boolean}
    content.vb: Public Property Detailed As Boolean?
  overload: ToSic.Cre8magic.Settings.MagicDebugSettings.Detailed*
references:
- uid: ToSic.Cre8magic.Settings
  commentId: N:ToSic.Cre8magic.Settings
  href: ToSic.html
  name: ToSic.Cre8magic.Settings
  nameWithType: ToSic.Cre8magic.Settings
  fullName: ToSic.Cre8magic.Settings
  spec.csharp:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
  spec.vb:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: ToSic.Cre8magic.Settings.MagicDebugSettings.#ctor*
  commentId: Overload:ToSic.Cre8magic.Settings.MagicDebugSettings.#ctor
  href: ToSic.Cre8magic.Settings.MagicDebugSettings.html#ToSic_Cre8magic_Settings_MagicDebugSettings__ctor_System_Boolean_
  name: MagicDebugSettings
  nameWithType: MagicDebugSettings.MagicDebugSettings
  fullName: ToSic.Cre8magic.Settings.MagicDebugSettings.MagicDebugSettings
  nameWithType.vb: MagicDebugSettings.New
  fullName.vb: ToSic.Cre8magic.Settings.MagicDebugSettings.New
  name.vb: New
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: ToSic.Cre8magic.Settings.MagicDebugSettings.Allowed*
  commentId: Overload:ToSic.Cre8magic.Settings.MagicDebugSettings.Allowed
  href: ToSic.Cre8magic.Settings.MagicDebugSettings.html#ToSic_Cre8magic_Settings_MagicDebugSettings_Allowed
  name: Allowed
  nameWithType: MagicDebugSettings.Allowed
  fullName: ToSic.Cre8magic.Settings.MagicDebugSettings.Allowed
- uid: System.Nullable{System.Boolean}
  commentId: T:System.Nullable{System.Boolean}
  parent: System
  definition: System.Nullable`1
  name: bool?
  nameWithType: bool?
  fullName: bool?
  nameWithType.vb: Boolean?
  fullName.vb: Boolean?
  name.vb: Boolean?
  spec.csharp:
  - uid: System.Boolean
    name: bool
    isExternal: true
  - name: '?'
  spec.vb:
  - uid: System.Boolean
    name: Boolean
    isExternal: true
  - name: '?'
- uid: System.Nullable`1
  commentId: T:System.Nullable`1
  isExternal: true
  name: Nullable<T>
  nameWithType: Nullable<T>
  fullName: System.Nullable<T>
  nameWithType.vb: Nullable(Of T)
  fullName.vb: System.Nullable(Of T)
  name.vb: Nullable(Of T)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    isExternal: true
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: ToSic.Cre8magic.Settings.MagicDebugSettings.Anonymous*
  commentId: Overload:ToSic.Cre8magic.Settings.MagicDebugSettings.Anonymous
  href: ToSic.Cre8magic.Settings.MagicDebugSettings.html#ToSic_Cre8magic_Settings_MagicDebugSettings_Anonymous
  name: Anonymous
  nameWithType: MagicDebugSettings.Anonymous
  fullName: ToSic.Cre8magic.Settings.MagicDebugSettings.Anonymous
- uid: ToSic.Cre8magic.Settings.MagicDebugSettings.Admin*
  commentId: Overload:ToSic.Cre8magic.Settings.MagicDebugSettings.Admin
  href: ToSic.Cre8magic.Settings.MagicDebugSettings.html#ToSic_Cre8magic_Settings_MagicDebugSettings_Admin
  name: Admin
  nameWithType: MagicDebugSettings.Admin
  fullName: ToSic.Cre8magic.Settings.MagicDebugSettings.Admin
- uid: ToSic.Cre8magic.Settings.MagicDebugSettings.Detailed*
  commentId: Overload:ToSic.Cre8magic.Settings.MagicDebugSettings.Detailed
  href: ToSic.Cre8magic.Settings.MagicDebugSettings.html#ToSic_Cre8magic_Settings_MagicDebugSettings_Detailed
  name: Detailed
  nameWithType: MagicDebugSettings.Detailed
  fullName: ToSic.Cre8magic.Settings.MagicDebugSettings.Detailed
