### YamlMime:ManagedReference
items:
- uid: ToSic.Cre8magic.Settings.SettingsWithInherit
  commentId: T:ToSic.Cre8magic.Settings.SettingsWithInherit
  id: SettingsWithInherit
  parent: ToSic.Cre8magic.Settings
  children:
  - ToSic.Cre8magic.Settings.SettingsWithInherit.#ctor
  - ToSic.Cre8magic.Settings.SettingsWithInherit.#ctor(ToSic.Cre8magic.Settings.SettingsWithInherit,ToSic.Cre8magic.Settings.SettingsWithInherit)
  - ToSic.Cre8magic.Settings.SettingsWithInherit.Inherits
  - ToSic.Cre8magic.Settings.SettingsWithInherit.PickFirstNonZeroInt(System.Nullable{System.Int32}[])
  langs:
  - csharp
  - vb
  name: SettingsWithInherit
  nameWithType: SettingsWithInherit
  fullName: ToSic.Cre8magic.Settings.SettingsWithInherit
  type: Class
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/SettingsWithInherit.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: SettingsWithInherit
    path: ../ToSic.Cre8Magic.Client/Settings/SettingsWithInherit.cs
    startLine: 5
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings
  syntax:
    content: public abstract record SettingsWithInherit
    content.vb: Public MustInherit Class SettingsWithInherit
  inheritance:
  - System.Object
  derivedClasses:
  - ToSic.Cre8magic.Breadcrumbs.MagicBreadcrumbBlueprint
  - ToSic.Cre8magic.Containers.MagicContainerBlueprint
  - ToSic.Cre8magic.Languages.MagicLanguageBlueprint
  - ToSic.Cre8magic.Menus.MagicMenuBlueprint
  - ToSic.Cre8magic.Settings.MagicSettingsBase
  - ToSic.Cre8magic.Themes.Settings.MagicThemeBlueprint
- uid: ToSic.Cre8magic.Settings.SettingsWithInherit.#ctor
  commentId: M:ToSic.Cre8magic.Settings.SettingsWithInherit.#ctor
  id: '#ctor'
  parent: ToSic.Cre8magic.Settings.SettingsWithInherit
  langs:
  - csharp
  - vb
  name: SettingsWithInherit()
  nameWithType: SettingsWithInherit.SettingsWithInherit()
  fullName: ToSic.Cre8magic.Settings.SettingsWithInherit.SettingsWithInherit()
  type: Constructor
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/SettingsWithInherit.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: .ctor
    path: ../ToSic.Cre8Magic.Client/Settings/SettingsWithInherit.cs
    startLine: 10
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings
  summary: Empty Constructor necessary for deserialization of inheriting classes
  example: []
  syntax:
    content: protected SettingsWithInherit()
    content.vb: Protected Sub New()
  overload: ToSic.Cre8magic.Settings.SettingsWithInherit.#ctor*
  nameWithType.vb: SettingsWithInherit.New()
  fullName.vb: ToSic.Cre8magic.Settings.SettingsWithInherit.New()
  name.vb: New()
- uid: ToSic.Cre8magic.Settings.SettingsWithInherit.#ctor(ToSic.Cre8magic.Settings.SettingsWithInherit,ToSic.Cre8magic.Settings.SettingsWithInherit)
  commentId: M:ToSic.Cre8magic.Settings.SettingsWithInherit.#ctor(ToSic.Cre8magic.Settings.SettingsWithInherit,ToSic.Cre8magic.Settings.SettingsWithInherit)
  id: '#ctor(ToSic.Cre8magic.Settings.SettingsWithInherit,ToSic.Cre8magic.Settings.SettingsWithInherit)'
  parent: ToSic.Cre8magic.Settings.SettingsWithInherit
  langs:
  - csharp
  - vb
  name: SettingsWithInherit(SettingsWithInherit?, SettingsWithInherit?)
  nameWithType: SettingsWithInherit.SettingsWithInherit(SettingsWithInherit?, SettingsWithInherit?)
  fullName: ToSic.Cre8magic.Settings.SettingsWithInherit.SettingsWithInherit(ToSic.Cre8magic.Settings.SettingsWithInherit?, ToSic.Cre8magic.Settings.SettingsWithInherit?)
  type: Constructor
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/SettingsWithInherit.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: .ctor
    path: ../ToSic.Cre8Magic.Client/Settings/SettingsWithInherit.cs
    startLine: 15
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings
  summary: Clone support.
  example: []
  syntax:
    content: protected SettingsWithInherit(SettingsWithInherit? priority, SettingsWithInherit? fallback = null)
    parameters:
    - id: priority
      type: ToSic.Cre8magic.Settings.SettingsWithInherit
    - id: fallback
      type: ToSic.Cre8magic.Settings.SettingsWithInherit
    content.vb: Protected Sub New(priority As SettingsWithInherit, fallback As SettingsWithInherit = Nothing)
  overload: ToSic.Cre8magic.Settings.SettingsWithInherit.#ctor*
  nameWithType.vb: SettingsWithInherit.New(SettingsWithInherit, SettingsWithInherit)
  fullName.vb: ToSic.Cre8magic.Settings.SettingsWithInherit.New(ToSic.Cre8magic.Settings.SettingsWithInherit, ToSic.Cre8magic.Settings.SettingsWithInherit)
  name.vb: New(SettingsWithInherit, SettingsWithInherit)
- uid: ToSic.Cre8magic.Settings.SettingsWithInherit.Inherits
  commentId: P:ToSic.Cre8magic.Settings.SettingsWithInherit.Inherits
  id: Inherits
  parent: ToSic.Cre8magic.Settings.SettingsWithInherit
  langs:
  - csharp
  - vb
  name: Inherits
  nameWithType: SettingsWithInherit.Inherits
  fullName: ToSic.Cre8magic.Settings.SettingsWithInherit.Inherits
  type: Property
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/SettingsWithInherit.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: Inherits
    path: ../ToSic.Cre8Magic.Client/Settings/SettingsWithInherit.cs
    startLine: 21
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings
  syntax:
    content: >-
      [JsonPropertyName("@inherits")]

      public string? Inherits { get; init; }
    parameters: []
    return:
      type: System.String
    content.vb: >-
      <JsonPropertyName("@inherits")>

      Public Property [Inherits] As String
  overload: ToSic.Cre8magic.Settings.SettingsWithInherit.Inherits*
  attributes:
  - type: System.Text.Json.Serialization.JsonPropertyNameAttribute
    ctor: System.Text.Json.Serialization.JsonPropertyNameAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: '@inherits'
- uid: ToSic.Cre8magic.Settings.SettingsWithInherit.PickFirstNonZeroInt(System.Nullable{System.Int32}[])
  commentId: M:ToSic.Cre8magic.Settings.SettingsWithInherit.PickFirstNonZeroInt(System.Nullable{System.Int32}[])
  id: PickFirstNonZeroInt(System.Nullable{System.Int32}[])
  parent: ToSic.Cre8magic.Settings.SettingsWithInherit
  langs:
  - csharp
  - vb
  name: PickFirstNonZeroInt(int?[])
  nameWithType: SettingsWithInherit.PickFirstNonZeroInt(int?[])
  fullName: ToSic.Cre8magic.Settings.SettingsWithInherit.PickFirstNonZeroInt(int?[])
  type: Method
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/SettingsWithInherit.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: PickFirstNonZeroInt
    path: ../ToSic.Cre8Magic.Client/Settings/SettingsWithInherit.cs
    startLine: 25
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings
  syntax:
    content: protected static int PickFirstNonZeroInt(int?[] values)
    parameters:
    - id: values
      type: System.Nullable{System.Int32}[]
    return:
      type: System.Int32
    content.vb: Protected Shared Function PickFirstNonZeroInt(values As Integer?()) As Integer
  overload: ToSic.Cre8magic.Settings.SettingsWithInherit.PickFirstNonZeroInt*
  nameWithType.vb: SettingsWithInherit.PickFirstNonZeroInt(Integer?())
  fullName.vb: ToSic.Cre8magic.Settings.SettingsWithInherit.PickFirstNonZeroInt(Integer?())
  name.vb: PickFirstNonZeroInt(Integer?())
references:
- uid: ToSic.Cre8magic.Settings
  commentId: N:ToSic.Cre8magic.Settings
  href: ToSic.html
  name: ToSic.Cre8magic.Settings
  nameWithType: ToSic.Cre8magic.Settings
  fullName: ToSic.Cre8magic.Settings
  spec.csharp:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
  spec.vb:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: ToSic.Cre8magic.Settings.SettingsWithInherit.#ctor*
  commentId: Overload:ToSic.Cre8magic.Settings.SettingsWithInherit.#ctor
  href: ToSic.Cre8magic.Settings.SettingsWithInherit.html#ToSic_Cre8magic_Settings_SettingsWithInherit__ctor
  name: SettingsWithInherit
  nameWithType: SettingsWithInherit.SettingsWithInherit
  fullName: ToSic.Cre8magic.Settings.SettingsWithInherit.SettingsWithInherit
  nameWithType.vb: SettingsWithInherit.New
  fullName.vb: ToSic.Cre8magic.Settings.SettingsWithInherit.New
  name.vb: New
- uid: ToSic.Cre8magic.Settings.SettingsWithInherit
  commentId: T:ToSic.Cre8magic.Settings.SettingsWithInherit
  parent: ToSic.Cre8magic.Settings
  href: ToSic.Cre8magic.Settings.SettingsWithInherit.html
  name: SettingsWithInherit
  nameWithType: SettingsWithInherit
  fullName: ToSic.Cre8magic.Settings.SettingsWithInherit
- uid: ToSic.Cre8magic.Settings.SettingsWithInherit.Inherits*
  commentId: Overload:ToSic.Cre8magic.Settings.SettingsWithInherit.Inherits
  href: ToSic.Cre8magic.Settings.SettingsWithInherit.html#ToSic_Cre8magic_Settings_SettingsWithInherit_Inherits
  name: Inherits
  nameWithType: SettingsWithInherit.Inherits
  fullName: ToSic.Cre8magic.Settings.SettingsWithInherit.Inherits
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: ToSic.Cre8magic.Settings.SettingsWithInherit.PickFirstNonZeroInt*
  commentId: Overload:ToSic.Cre8magic.Settings.SettingsWithInherit.PickFirstNonZeroInt
  href: ToSic.Cre8magic.Settings.SettingsWithInherit.html#ToSic_Cre8magic_Settings_SettingsWithInherit_PickFirstNonZeroInt_System_Nullable_System_Int32____
  name: PickFirstNonZeroInt
  nameWithType: SettingsWithInherit.PickFirstNonZeroInt
  fullName: ToSic.Cre8magic.Settings.SettingsWithInherit.PickFirstNonZeroInt
- uid: System.Nullable{System.Int32}[]
  isExternal: true
  name: int?[]
  nameWithType: int?[]
  fullName: int?[]
  nameWithType.vb: Integer?()
  fullName.vb: Integer?()
  name.vb: Integer?()
  spec.csharp:
  - uid: System.Int32
    name: int
    isExternal: true
  - name: '?'
  - name: '['
  - name: ']'
  spec.vb:
  - uid: System.Int32
    name: Integer
    isExternal: true
  - name: '?'
  - name: (
  - name: )
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
