### YamlMime:ManagedReference
items:
- uid: ToSic.Cre8magic.Settings.MagicSettingOnOff
  commentId: T:ToSic.Cre8magic.Settings.MagicSettingOnOff
  id: MagicSettingOnOff
  parent: ToSic.Cre8magic.Settings
  children:
  - ToSic.Cre8magic.Settings.MagicSettingOnOff.#ctor(System.String,System.String)
  - ToSic.Cre8magic.Settings.MagicSettingOnOff.Off
  - ToSic.Cre8magic.Settings.MagicSettingOnOff.On
  langs:
  - csharp
  - vb
  name: MagicSettingOnOff
  nameWithType: MagicSettingOnOff
  fullName: ToSic.Cre8magic.Settings.MagicSettingOnOff
  type: Class
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/MagicSettingOnOff.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: MagicSettingOnOff
    path: ../ToSic.Cre8Magic.Client/Settings/MagicSettingOnOff.cs
    startLine: 13
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings
  summary: >-
    Special Setting containing a value to be used when a state is on or off.

    Typically used to specify strings to place in classes when something:

    * is active

    * is home

    * etc.
  example: []
  syntax:
    content: >-
      [JsonConverter(typeof(SettingOnOffJsonConverter))]

      public record MagicSettingOnOff
    content.vb: >-
      <JsonConverter(GetType(SettingOnOffJsonConverter))>

      Public Class MagicSettingOnOff
  inheritance:
  - System.Object
- uid: ToSic.Cre8magic.Settings.MagicSettingOnOff.#ctor(System.String,System.String)
  commentId: M:ToSic.Cre8magic.Settings.MagicSettingOnOff.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: ToSic.Cre8magic.Settings.MagicSettingOnOff
  langs:
  - csharp
  - vb
  name: MagicSettingOnOff(string?, string?)
  nameWithType: MagicSettingOnOff.MagicSettingOnOff(string?, string?)
  fullName: ToSic.Cre8magic.Settings.MagicSettingOnOff.MagicSettingOnOff(string?, string?)
  type: Constructor
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/MagicSettingOnOff.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: .ctor
    path: ../ToSic.Cre8Magic.Client/Settings/MagicSettingOnOff.cs
    startLine: 22
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings
  syntax:
    content: public MagicSettingOnOff(string? on, string? off = null)
    parameters:
    - id: on
      type: System.String
    - id: off
      type: System.String
    content.vb: Public Sub New([on] As String, off As String = Nothing)
  overload: ToSic.Cre8magic.Settings.MagicSettingOnOff.#ctor*
  nameWithType.vb: MagicSettingOnOff.New(String, String)
  fullName.vb: ToSic.Cre8magic.Settings.MagicSettingOnOff.New(String, String)
  name.vb: New(String, String)
- uid: ToSic.Cre8magic.Settings.MagicSettingOnOff.On
  commentId: P:ToSic.Cre8magic.Settings.MagicSettingOnOff.On
  id: On
  parent: ToSic.Cre8magic.Settings.MagicSettingOnOff
  langs:
  - csharp
  - vb
  name: On
  nameWithType: MagicSettingOnOff.On
  fullName: ToSic.Cre8magic.Settings.MagicSettingOnOff.On
  type: Property
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/MagicSettingOnOff.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: On
    path: ../ToSic.Cre8Magic.Client/Settings/MagicSettingOnOff.cs
    startLine: 31
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings
  summary: Value / Class to add if the setting is on
  example: []
  syntax:
    content: public string? On { get; init; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property [On] As String
  overload: ToSic.Cre8magic.Settings.MagicSettingOnOff.On*
- uid: ToSic.Cre8magic.Settings.MagicSettingOnOff.Off
  commentId: P:ToSic.Cre8magic.Settings.MagicSettingOnOff.Off
  id: Off
  parent: ToSic.Cre8magic.Settings.MagicSettingOnOff
  langs:
  - csharp
  - vb
  name: Off
  nameWithType: MagicSettingOnOff.Off
  fullName: ToSic.Cre8magic.Settings.MagicSettingOnOff.Off
  type: Property
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/MagicSettingOnOff.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: Off
    path: ../ToSic.Cre8Magic.Client/Settings/MagicSettingOnOff.cs
    startLine: 36
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings
  summary: Value / Class to add if the setting is off
  example: []
  syntax:
    content: public string? Off { get; init; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Off As String
  overload: ToSic.Cre8magic.Settings.MagicSettingOnOff.Off*
references:
- uid: ToSic.Cre8magic.Settings
  commentId: N:ToSic.Cre8magic.Settings
  href: ToSic.html
  name: ToSic.Cre8magic.Settings
  nameWithType: ToSic.Cre8magic.Settings
  fullName: ToSic.Cre8magic.Settings
  spec.csharp:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
  spec.vb:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: ToSic.Cre8magic.Settings.MagicSettingOnOff.#ctor*
  commentId: Overload:ToSic.Cre8magic.Settings.MagicSettingOnOff.#ctor
  href: ToSic.Cre8magic.Settings.MagicSettingOnOff.html#ToSic_Cre8magic_Settings_MagicSettingOnOff__ctor_System_String_System_String_
  name: MagicSettingOnOff
  nameWithType: MagicSettingOnOff.MagicSettingOnOff
  fullName: ToSic.Cre8magic.Settings.MagicSettingOnOff.MagicSettingOnOff
  nameWithType.vb: MagicSettingOnOff.New
  fullName.vb: ToSic.Cre8magic.Settings.MagicSettingOnOff.New
  name.vb: New
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: ToSic.Cre8magic.Settings.MagicSettingOnOff.On*
  commentId: Overload:ToSic.Cre8magic.Settings.MagicSettingOnOff.On
  href: ToSic.Cre8magic.Settings.MagicSettingOnOff.html#ToSic_Cre8magic_Settings_MagicSettingOnOff_On
  name: On
  nameWithType: MagicSettingOnOff.On
  fullName: ToSic.Cre8magic.Settings.MagicSettingOnOff.On
- uid: ToSic.Cre8magic.Settings.MagicSettingOnOff.Off*
  commentId: Overload:ToSic.Cre8magic.Settings.MagicSettingOnOff.Off
  href: ToSic.Cre8magic.Settings.MagicSettingOnOff.html#ToSic_Cre8magic_Settings_MagicSettingOnOff_Off
  name: Off
  nameWithType: MagicSettingOnOff.Off
  fullName: ToSic.Cre8magic.Settings.MagicSettingOnOff.Off
