### YamlMime:ManagedReference
items:
- uid: ToSic.Cre8magic.Settings.MagicSettingsExtensions
  commentId: T:ToSic.Cre8magic.Settings.MagicSettingsExtensions
  id: MagicSettingsExtensions
  parent: ToSic.Cre8magic.Settings
  children:
  - ToSic.Cre8magic.Settings.MagicSettingsExtensions.With``1(``0,Oqtane.UI.PageState,System.Boolean)
  - ToSic.Cre8magic.Settings.MagicSettingsExtensions.With``2(``0,``1,System.Boolean)
  langs:
  - csharp
  - vb
  name: MagicSettingsExtensions
  nameWithType: MagicSettingsExtensions
  fullName: ToSic.Cre8magic.Settings.MagicSettingsExtensions
  type: Class
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/MagicSettingsExtensions.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: MagicSettingsExtensions
    path: ../ToSic.Cre8Magic.Client/Settings/MagicSettingsExtensions.cs
    startLine: 5
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings
  syntax:
    content: public static class MagicSettingsExtensions
    content.vb: Public Module MagicSettingsExtensions
  inheritance:
  - System.Object
- uid: ToSic.Cre8magic.Settings.MagicSettingsExtensions.With``1(``0,Oqtane.UI.PageState,System.Boolean)
  commentId: M:ToSic.Cre8magic.Settings.MagicSettingsExtensions.With``1(``0,Oqtane.UI.PageState,System.Boolean)
  id: With``1(``0,Oqtane.UI.PageState,System.Boolean)
  isExtensionMethod: true
  parent: ToSic.Cre8magic.Settings.MagicSettingsExtensions
  langs:
  - csharp
  - vb
  name: With<TSettings>(TSettings?, PageState, bool)
  nameWithType: MagicSettingsExtensions.With<TSettings>(TSettings?, PageState, bool)
  fullName: ToSic.Cre8magic.Settings.MagicSettingsExtensions.With<TSettings>(TSettings?, Oqtane.UI.PageState, bool)
  type: Method
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/MagicSettingsExtensions.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: With
    path: ../ToSic.Cre8Magic.Client/Settings/MagicSettingsExtensions.cs
    startLine: 16
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings
  summary: >-
    Add a PageState to a settings object.

    This uses normal record `with` manipulations, so it creates a new object but preserves all other settings.
  example: []
  syntax:
    content: 'public static TSettings With<TSettings>(this TSettings? settings, PageState pageState, bool overwrite = false) where TSettings : MagicSettingsBase, new()'
    parameters:
    - id: settings
      type: '{TSettings}'
      description: The initial settings object - can be null (in which case a fresh one is created)
    - id: pageState
      type: Oqtane.UI.PageState
      description: The PageState
    - id: overwrite
      type: System.Boolean
      description: Determines if an existing value should be overwritten. If `false` (default) any original value is preserved.
    typeParameters:
    - id: TSettings
      description: The type of settings we're expanding with this PageState data.
    return:
      type: '{TSettings}'
      description: ''
    content.vb: Public Shared Function [With](Of TSettings As {MagicSettingsBase, New})(settings As TSettings, pageState As PageState, overwrite As Boolean = False) As TSettings
  overload: ToSic.Cre8magic.Settings.MagicSettingsExtensions.With*
  nameWithType.vb: MagicSettingsExtensions.With(Of TSettings)(TSettings, PageState, Boolean)
  fullName.vb: ToSic.Cre8magic.Settings.MagicSettingsExtensions.With(Of TSettings)(TSettings, Oqtane.UI.PageState, Boolean)
  name.vb: With(Of TSettings)(TSettings, PageState, Boolean)
- uid: ToSic.Cre8magic.Settings.MagicSettingsExtensions.With``2(``0,``1,System.Boolean)
  commentId: M:ToSic.Cre8magic.Settings.MagicSettingsExtensions.With``2(``0,``1,System.Boolean)
  id: With``2(``0,``1,System.Boolean)
  isExtensionMethod: true
  parent: ToSic.Cre8magic.Settings.MagicSettingsExtensions
  langs:
  - csharp
  - vb
  name: With<TSettings, TWith>(TSettings?, TWith?, bool)
  nameWithType: MagicSettingsExtensions.With<TSettings, TWith>(TSettings?, TWith?, bool)
  fullName: ToSic.Cre8magic.Settings.MagicSettingsExtensions.With<TSettings, TWith>(TSettings?, TWith?, bool)
  type: Method
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/MagicSettingsExtensions.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: With
    path: ../ToSic.Cre8Magic.Client/Settings/MagicSettingsExtensions.cs
    startLine: 25
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings
  syntax:
    content: 'public static TSettings With<TSettings, TWith>(this TSettings? settings, TWith? addition, bool overwrite = false) where TSettings : MagicSettingsBase, IWith<TWith>, new() where TWith : class'
    parameters:
    - id: settings
      type: '{TSettings}'
    - id: addition
      type: '{TWith}'
    - id: overwrite
      type: System.Boolean
    typeParameters:
    - id: TSettings
    - id: TWith
    return:
      type: '{TSettings}'
    content.vb: Public Shared Function [With](Of TSettings As {MagicSettingsBase, IWith(Of TWith), New}, TWith As Class)(settings As TSettings, addition As TWith, overwrite As Boolean = False) As TSettings
  overload: ToSic.Cre8magic.Settings.MagicSettingsExtensions.With*
  nameWithType.vb: MagicSettingsExtensions.With(Of TSettings, TWith)(TSettings, TWith, Boolean)
  fullName.vb: ToSic.Cre8magic.Settings.MagicSettingsExtensions.With(Of TSettings, TWith)(TSettings, TWith, Boolean)
  name.vb: With(Of TSettings, TWith)(TSettings, TWith, Boolean)
references:
- uid: ToSic.Cre8magic.Settings
  commentId: N:ToSic.Cre8magic.Settings
  href: ToSic.html
  name: ToSic.Cre8magic.Settings
  nameWithType: ToSic.Cre8magic.Settings
  fullName: ToSic.Cre8magic.Settings
  spec.csharp:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
  spec.vb:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: ToSic.Cre8magic.Settings.MagicSettingsExtensions.With*
  commentId: Overload:ToSic.Cre8magic.Settings.MagicSettingsExtensions.With
  href: ToSic.Cre8magic.Settings.MagicSettingsExtensions.html#ToSic_Cre8magic_Settings_MagicSettingsExtensions_With__1___0_Oqtane_UI_PageState_System_Boolean_
  name: With
  nameWithType: MagicSettingsExtensions.With
  fullName: ToSic.Cre8magic.Settings.MagicSettingsExtensions.With
- uid: '{TSettings}'
  commentId: '!:TSettings'
  definition: TSettings
  name: TSettings
  nameWithType: TSettings
  fullName: TSettings
- uid: Oqtane.UI.PageState
  commentId: T:Oqtane.UI.PageState
  parent: Oqtane.UI
  isExternal: true
  href: https://github.com/sbwalker/oqtane.framework/blob/5e9567158f0f5ea11a746a02b9359695423d7608/Oqtane.Client/UI/PageState.cs
  name: PageState
  nameWithType: PageState
  fullName: Oqtane.UI.PageState
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: TSettings
  name: TSettings
  nameWithType: TSettings
  fullName: TSettings
- uid: Oqtane.UI
  commentId: N:Oqtane.UI
  isExternal: true
  name: Oqtane.UI
  nameWithType: Oqtane.UI
  fullName: Oqtane.UI
  spec.csharp:
  - uid: Oqtane
    name: Oqtane
    isExternal: true
  - name: .
  - uid: Oqtane.UI
    name: UI
    isExternal: true
  spec.vb:
  - uid: Oqtane
    name: Oqtane
    isExternal: true
  - name: .
  - uid: Oqtane.UI
    name: UI
    isExternal: true
- uid: '{TWith}'
  commentId: '!:TWith'
  definition: TWith
  name: TWith
  nameWithType: TWith
  fullName: TWith
- uid: TWith
  commentId: '!:TWith'
  name: TWith
  nameWithType: TWith
  fullName: TWith
