### YamlMime:ManagedReference
items:
- uid: ToSic.Cre8magic.Settings.Internal.IWith`1
  commentId: T:ToSic.Cre8magic.Settings.Internal.IWith`1
  id: IWith`1
  parent: ToSic.Cre8magic.Settings.Internal
  children:
  - ToSic.Cre8magic.Settings.Internal.IWith`1.WithData
  langs:
  - csharp
  - vb
  name: IWith<T>
  nameWithType: IWith<T>
  fullName: ToSic.Cre8magic.Settings.Internal.IWith<T>
  type: Interface
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/Internal/IWith_T.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: IWith
    path: ../ToSic.Cre8Magic.Client/Settings/Internal/IWith_T.cs
    startLine: 2
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings.Internal
  syntax:
    content: public interface IWith<T>
    typeParameters:
    - id: T
    content.vb: Public Interface IWith(Of T)
  nameWithType.vb: IWith(Of T)
  fullName.vb: ToSic.Cre8magic.Settings.Internal.IWith(Of T)
  name.vb: IWith(Of T)
- uid: ToSic.Cre8magic.Settings.Internal.IWith`1.WithData
  commentId: P:ToSic.Cre8magic.Settings.Internal.IWith`1.WithData
  id: WithData
  parent: ToSic.Cre8magic.Settings.Internal.IWith`1
  langs:
  - csharp
  - vb
  name: WithData
  nameWithType: IWith<T>.WithData
  fullName: ToSic.Cre8magic.Settings.Internal.IWith<T>.WithData
  type: Property
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/Internal/IWith_T.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: WithData
    path: ../ToSic.Cre8Magic.Client/Settings/Internal/IWith_T.cs
    startLine: 4
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings.Internal
  syntax:
    content: T? WithData { get; init; }
    parameters: []
    return:
      type: '{T}'
    content.vb: Property WithData As T
  overload: ToSic.Cre8magic.Settings.Internal.IWith`1.WithData*
  nameWithType.vb: IWith(Of T).WithData
  fullName.vb: ToSic.Cre8magic.Settings.Internal.IWith(Of T).WithData
references:
- uid: ToSic.Cre8magic.Settings.Internal
  commentId: N:ToSic.Cre8magic.Settings.Internal
  href: ToSic.html
  name: ToSic.Cre8magic.Settings.Internal
  nameWithType: ToSic.Cre8magic.Settings.Internal
  fullName: ToSic.Cre8magic.Settings.Internal
  spec.csharp:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Internal
    name: Internal
    href: ToSic.Cre8magic.Settings.Internal.html
  spec.vb:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Internal
    name: Internal
    href: ToSic.Cre8magic.Settings.Internal.html
- uid: ToSic.Cre8magic.Settings.Internal.IWith`1.WithData*
  commentId: Overload:ToSic.Cre8magic.Settings.Internal.IWith`1.WithData
  href: ToSic.Cre8magic.Settings.Internal.IWith-1.html#ToSic_Cre8magic_Settings_Internal_IWith_1_WithData
  name: WithData
  nameWithType: IWith<T>.WithData
  fullName: ToSic.Cre8magic.Settings.Internal.IWith<T>.WithData
  nameWithType.vb: IWith(Of T).WithData
  fullName.vb: ToSic.Cre8magic.Settings.Internal.IWith(Of T).WithData
- uid: '{T}'
  commentId: '!:T'
  definition: T
  name: T
  nameWithType: T
  fullName: T
- uid: T
  name: T
  nameWithType: T
  fullName: T
