### YamlMime:ManagedReference
items:
- uid: ToSic.Cre8magic.Pages.IMagicPageSetSettings
  commentId: T:ToSic.Cre8magic.Pages.IMagicPageSetSettings
  id: IMagicPageSetSettings
  parent: ToSic.Cre8magic.Pages
  children:
  - ToSic.Cre8magic.Pages.IMagicPageSetSettings.Id
  - ToSic.Cre8magic.Pages.IMagicPageSetSettings.MenuId
  - ToSic.Cre8magic.Pages.IMagicPageSetSettings.Variant
  langs:
  - csharp
  - vb
  name: IMagicPageSetSettings
  nameWithType: IMagicPageSetSettings
  fullName: ToSic.Cre8magic.Pages.IMagicPageSetSettings
  type: Interface
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Pages/IMagicPageSetSettings.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: IMagicPageSetSettings
    path: ../ToSic.Cre8Magic.Client/Pages/IMagicPageSetSettings.cs
    startLine: 7
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Pages
  summary: >-
    WIP

    TODO: naming not final
  example: []
  syntax:
    content: public interface IMagicPageSetSettings
    content.vb: Public Interface IMagicPageSetSettings
- uid: ToSic.Cre8magic.Pages.IMagicPageSetSettings.Id
  commentId: P:ToSic.Cre8magic.Pages.IMagicPageSetSettings.Id
  id: Id
  parent: ToSic.Cre8magic.Pages.IMagicPageSetSettings
  langs:
  - csharp
  - vb
  name: Id
  nameWithType: IMagicPageSetSettings.Id
  fullName: ToSic.Cre8magic.Pages.IMagicPageSetSettings.Id
  type: Property
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Pages/IMagicPageSetSettings.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: Id
    path: ../ToSic.Cre8Magic.Client/Pages/IMagicPageSetSettings.cs
    startLine: 14
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Pages
  summary: >-
    Id of the settings, usually a random number


    TODO: UNCLEAR difference to MenuId - or could be the same?
  example: []
  syntax:
    content: string? Id { get; }
    parameters: []
    return:
      type: System.String
    content.vb: ReadOnly Property Id As String
  overload: ToSic.Cre8magic.Pages.IMagicPageSetSettings.Id*
- uid: ToSic.Cre8magic.Pages.IMagicPageSetSettings.MenuId
  commentId: P:ToSic.Cre8magic.Pages.IMagicPageSetSettings.MenuId
  id: MenuId
  parent: ToSic.Cre8magic.Pages.IMagicPageSetSettings
  langs:
  - csharp
  - vb
  name: MenuId
  nameWithType: IMagicPageSetSettings.MenuId
  fullName: ToSic.Cre8magic.Pages.IMagicPageSetSettings.MenuId
  type: Property
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Pages/IMagicPageSetSettings.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: MenuId
    path: ../ToSic.Cre8Magic.Client/Pages/IMagicPageSetSettings.cs
    startLine: 20
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Pages
  summary: >-
    Menu ID for use in JavaScript etc.

    Usually predefined OR a random number
  example: []
  syntax:
    content: string MenuId { get; }
    parameters: []
    return:
      type: System.String
    content.vb: ReadOnly Property MenuId As String
  overload: ToSic.Cre8magic.Pages.IMagicPageSetSettings.MenuId*
- uid: ToSic.Cre8magic.Pages.IMagicPageSetSettings.Variant
  commentId: P:ToSic.Cre8magic.Pages.IMagicPageSetSettings.Variant
  id: Variant
  parent: ToSic.Cre8magic.Pages.IMagicPageSetSettings
  langs:
  - csharp
  - vb
  name: Variant
  nameWithType: IMagicPageSetSettings.Variant
  fullName: ToSic.Cre8magic.Pages.IMagicPageSetSettings.Variant
  type: Property
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Pages/IMagicPageSetSettings.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: Variant
    path: ../ToSic.Cre8Magic.Client/Pages/IMagicPageSetSettings.cs
    startLine: 22
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Pages
  syntax:
    content: string? Variant { get; }
    parameters: []
    return:
      type: System.String
    content.vb: ReadOnly Property [Variant] As String
  overload: ToSic.Cre8magic.Pages.IMagicPageSetSettings.Variant*
references:
- uid: ToSic.Cre8magic.Pages
  commentId: N:ToSic.Cre8magic.Pages
  href: ToSic.html
  name: ToSic.Cre8magic.Pages
  nameWithType: ToSic.Cre8magic.Pages
  fullName: ToSic.Cre8magic.Pages
  spec.csharp:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Pages
    name: Pages
    href: ToSic.Cre8magic.Pages.html
  spec.vb:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Pages
    name: Pages
    href: ToSic.Cre8magic.Pages.html
- uid: ToSic.Cre8magic.Pages.IMagicPageSetSettings.Id*
  commentId: Overload:ToSic.Cre8magic.Pages.IMagicPageSetSettings.Id
  href: ToSic.Cre8magic.Pages.IMagicPageSetSettings.html#ToSic_Cre8magic_Pages_IMagicPageSetSettings_Id
  name: Id
  nameWithType: IMagicPageSetSettings.Id
  fullName: ToSic.Cre8magic.Pages.IMagicPageSetSettings.Id
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: ToSic.Cre8magic.Pages.IMagicPageSetSettings.MenuId*
  commentId: Overload:ToSic.Cre8magic.Pages.IMagicPageSetSettings.MenuId
  href: ToSic.Cre8magic.Pages.IMagicPageSetSettings.html#ToSic_Cre8magic_Pages_IMagicPageSetSettings_MenuId
  name: MenuId
  nameWithType: IMagicPageSetSettings.MenuId
  fullName: ToSic.Cre8magic.Pages.IMagicPageSetSettings.MenuId
- uid: ToSic.Cre8magic.Pages.IMagicPageSetSettings.Variant*
  commentId: Overload:ToSic.Cre8magic.Pages.IMagicPageSetSettings.Variant
  href: ToSic.Cre8magic.Pages.IMagicPageSetSettings.html#ToSic_Cre8magic_Pages_IMagicPageSetSettings_Variant
  name: Variant
  nameWithType: IMagicPageSetSettings.Variant
  fullName: ToSic.Cre8magic.Pages.IMagicPageSetSettings.Variant
