### YamlMime:ManagedReference
items:
- uid: ToSic.Cre8magic.Settings.Internal.Debug.MagicSettingsDebugExtensions
  commentId: T:ToSic.Cre8magic.Settings.Internal.Debug.MagicSettingsDebugExtensions
  id: MagicSettingsDebugExtensions
  parent: ToSic.Cre8magic.Settings.Internal.Debug
  children:
  - ToSic.Cre8magic.Settings.Internal.Debug.MagicSettingsDebugExtensions.NoCachingForDebug``1(ToSic.Cre8magic.Settings.IMagicSettingsService,System.Func{ToSic.Cre8magic.Settings.IMagicSettingsService,``0})
  langs:
  - csharp
  - vb
  name: MagicSettingsDebugExtensions
  nameWithType: MagicSettingsDebugExtensions
  fullName: ToSic.Cre8magic.Settings.Internal.Debug.MagicSettingsDebugExtensions
  type: Class
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/Internal/Debug/MagicSettingsDebugExtensions.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: MagicSettingsDebugExtensions
    path: ../ToSic.Cre8Magic.Client/Settings/Internal/Debug/MagicSettingsDebugExtensions.cs
    startLine: 2
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings.Internal.Debug
  syntax:
    content: public static class MagicSettingsDebugExtensions
    content.vb: Public Module MagicSettingsDebugExtensions
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: ToSic.Cre8magic.Settings.Internal.Debug.MagicSettingsDebugExtensions.NoCachingForDebug``1(ToSic.Cre8magic.Settings.IMagicSettingsService,System.Func{ToSic.Cre8magic.Settings.IMagicSettingsService,``0})
  commentId: M:ToSic.Cre8magic.Settings.Internal.Debug.MagicSettingsDebugExtensions.NoCachingForDebug``1(ToSic.Cre8magic.Settings.IMagicSettingsService,System.Func{ToSic.Cre8magic.Settings.IMagicSettingsService,``0})
  id: NoCachingForDebug``1(ToSic.Cre8magic.Settings.IMagicSettingsService,System.Func{ToSic.Cre8magic.Settings.IMagicSettingsService,``0})
  isExtensionMethod: true
  parent: ToSic.Cre8magic.Settings.Internal.Debug.MagicSettingsDebugExtensions
  langs:
  - csharp
  - vb
  name: NoCachingForDebug<TDebug>(IMagicSettingsService, Func<IMagicSettingsService, TDebug>)
  nameWithType: MagicSettingsDebugExtensions.NoCachingForDebug<TDebug>(IMagicSettingsService, Func<IMagicSettingsService, TDebug>)
  fullName: ToSic.Cre8magic.Settings.Internal.Debug.MagicSettingsDebugExtensions.NoCachingForDebug<TDebug>(ToSic.Cre8magic.Settings.IMagicSettingsService, System.Func<ToSic.Cre8magic.Settings.IMagicSettingsService, TDebug>)
  type: Method
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/Internal/Debug/MagicSettingsDebugExtensions.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: NoCachingForDebug
    path: ../ToSic.Cre8Magic.Client/Settings/Internal/Debug/MagicSettingsDebugExtensions.cs
    startLine: 4
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings.Internal.Debug
  syntax:
    content: public static TDebug NoCachingForDebug<TDebug>(this IMagicSettingsService settings, Func<IMagicSettingsService, TDebug> func)
    parameters:
    - id: settings
      type: ToSic.Cre8magic.Settings.IMagicSettingsService
    - id: func
      type: System.Func{ToSic.Cre8magic.Settings.IMagicSettingsService,{TDebug}}
    typeParameters:
    - id: TDebug
    return:
      type: '{TDebug}'
    content.vb: Public Shared Function NoCachingForDebug(Of TDebug)(settings As IMagicSettingsService, func As Func(Of IMagicSettingsService, TDebug)) As TDebug
  overload: ToSic.Cre8magic.Settings.Internal.Debug.MagicSettingsDebugExtensions.NoCachingForDebug*
  nameWithType.vb: MagicSettingsDebugExtensions.NoCachingForDebug(Of TDebug)(IMagicSettingsService, Func(Of IMagicSettingsService, TDebug))
  fullName.vb: ToSic.Cre8magic.Settings.Internal.Debug.MagicSettingsDebugExtensions.NoCachingForDebug(Of TDebug)(ToSic.Cre8magic.Settings.IMagicSettingsService, System.Func(Of ToSic.Cre8magic.Settings.IMagicSettingsService, TDebug))
  name.vb: NoCachingForDebug(Of TDebug)(IMagicSettingsService, Func(Of IMagicSettingsService, TDebug))
references:
- uid: ToSic.Cre8magic.Settings.Internal.Debug
  commentId: N:ToSic.Cre8magic.Settings.Internal.Debug
  href: ToSic.html
  name: ToSic.Cre8magic.Settings.Internal.Debug
  nameWithType: ToSic.Cre8magic.Settings.Internal.Debug
  fullName: ToSic.Cre8magic.Settings.Internal.Debug
  spec.csharp:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Internal
    name: Internal
    href: ToSic.Cre8magic.Settings.Internal.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Internal.Debug
    name: Debug
    href: ToSic.Cre8magic.Settings.Internal.Debug.html
  spec.vb:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Internal
    name: Internal
    href: ToSic.Cre8magic.Settings.Internal.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Internal.Debug
    name: Debug
    href: ToSic.Cre8magic.Settings.Internal.Debug.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: ToSic.Cre8magic.Settings.Internal.Debug.MagicSettingsDebugExtensions.NoCachingForDebug*
  commentId: Overload:ToSic.Cre8magic.Settings.Internal.Debug.MagicSettingsDebugExtensions.NoCachingForDebug
  href: ToSic.Cre8magic.Settings.Internal.Debug.MagicSettingsDebugExtensions.html#ToSic_Cre8magic_Settings_Internal_Debug_MagicSettingsDebugExtensions_NoCachingForDebug__1_ToSic_Cre8magic_Settings_IMagicSettingsService_System_Func_ToSic_Cre8magic_Settings_IMagicSettingsService___0__
  name: NoCachingForDebug
  nameWithType: MagicSettingsDebugExtensions.NoCachingForDebug
  fullName: ToSic.Cre8magic.Settings.Internal.Debug.MagicSettingsDebugExtensions.NoCachingForDebug
- uid: ToSic.Cre8magic.Settings.IMagicSettingsService
  commentId: T:ToSic.Cre8magic.Settings.IMagicSettingsService
  parent: ToSic.Cre8magic.Settings
  href: ToSic.Cre8magic.Settings.IMagicSettingsService.html
  name: IMagicSettingsService
  nameWithType: IMagicSettingsService
  fullName: ToSic.Cre8magic.Settings.IMagicSettingsService
- uid: System.Func{ToSic.Cre8magic.Settings.IMagicSettingsService,{TDebug}}
  commentId: T:System.Func{ToSic.Cre8magic.Settings.IMagicSettingsService,``0}
  parent: System
  definition: System.Func`2
  href: https://learn.microsoft.com/dotnet/api/system.func-2
  name: Func<IMagicSettingsService, TDebug>
  nameWithType: Func<IMagicSettingsService, TDebug>
  fullName: System.Func<ToSic.Cre8magic.Settings.IMagicSettingsService, TDebug>
  nameWithType.vb: Func(Of IMagicSettingsService, TDebug)
  fullName.vb: System.Func(Of ToSic.Cre8magic.Settings.IMagicSettingsService, TDebug)
  name.vb: Func(Of IMagicSettingsService, TDebug)
  spec.csharp:
  - uid: System.Func`2
    name: Func
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.func-2
  - name: <
  - uid: ToSic.Cre8magic.Settings.IMagicSettingsService
    name: IMagicSettingsService
    href: ToSic.Cre8magic.Settings.IMagicSettingsService.html
  - name: ','
  - name: " "
  - name: TDebug
  - name: '>'
  spec.vb:
  - uid: System.Func`2
    name: Func
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.func-2
  - name: (
  - name: Of
  - name: " "
  - uid: ToSic.Cre8magic.Settings.IMagicSettingsService
    name: IMagicSettingsService
    href: ToSic.Cre8magic.Settings.IMagicSettingsService.html
  - name: ','
  - name: " "
  - name: TDebug
  - name: )
- uid: '{TDebug}'
  commentId: '!:TDebug'
  definition: TDebug
  name: TDebug
  nameWithType: TDebug
  fullName: TDebug
- uid: ToSic.Cre8magic.Settings
  commentId: N:ToSic.Cre8magic.Settings
  href: ToSic.html
  name: ToSic.Cre8magic.Settings
  nameWithType: ToSic.Cre8magic.Settings
  fullName: ToSic.Cre8magic.Settings
  spec.csharp:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
  spec.vb:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
- uid: System.Func`2
  commentId: T:System.Func`2
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.func-2
  name: Func<T, TResult>
  nameWithType: Func<T, TResult>
  fullName: System.Func<T, TResult>
  nameWithType.vb: Func(Of T, TResult)
  fullName.vb: System.Func(Of T, TResult)
  name.vb: Func(Of T, TResult)
  spec.csharp:
  - uid: System.Func`2
    name: Func
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.func-2
  - name: <
  - name: T
  - name: ','
  - name: " "
  - name: TResult
  - name: '>'
  spec.vb:
  - uid: System.Func`2
    name: Func
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.func-2
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: ','
  - name: " "
  - name: TResult
  - name: )
- uid: TDebug
  commentId: '!:TDebug'
  name: TDebug
  nameWithType: TDebug
  fullName: TDebug
