### YamlMime:ManagedReference
items:
- uid: ToSic.Cre8magic.Breadcrumb.Settings
  commentId: N:ToSic.Cre8magic.Breadcrumb.Settings
  id: Settings
  parent: ToSic.Cre8magic.Breadcrumb
  children:
  - ToSic.Cre8magic.Breadcrumb.Settings.MagicBreadcrumbDesign
  - ToSic.Cre8magic.Breadcrumb.Settings.MagicBreadcrumbDesigner
  - ToSic.Cre8magic.Breadcrumb.Settings.MagicBreadcrumbSettings
  langs:
  - csharp
  - vb
  name: ToSic.Cre8magic.Breadcrumb.Settings
  nameWithType: ToSic.Cre8magic.Breadcrumb.Settings
  fullName: ToSic.Cre8magic.Breadcrumb.Settings
  type: Namespace
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
references:
- uid: ToSic.Cre8magic.Breadcrumb.Settings.MagicBreadcrumbDesign
  commentId: T:ToSic.Cre8magic.Breadcrumb.Settings.MagicBreadcrumbDesign
  parent: ToSic.Cre8magic.Breadcrumb.Settings
  href: ToSic.Cre8magic.Breadcrumb.Settings.MagicBreadcrumbDesign.html
  name: MagicBreadcrumbDesign
  nameWithType: MagicBreadcrumbDesign
  fullName: ToSic.Cre8magic.Breadcrumb.Settings.MagicBreadcrumbDesign
- uid: ToSic.Cre8magic.Breadcrumb.Settings.MagicBreadcrumbDesigner
  commentId: T:ToSic.Cre8magic.Breadcrumb.Settings.MagicBreadcrumbDesigner
  href: ToSic.Cre8magic.Breadcrumb.Settings.MagicBreadcrumbDesigner.html
  name: MagicBreadcrumbDesigner
  nameWithType: MagicBreadcrumbDesigner
  fullName: ToSic.Cre8magic.Breadcrumb.Settings.MagicBreadcrumbDesigner
- uid: ToSic.Cre8magic.Breadcrumb.Settings.MagicBreadcrumbSettings
  commentId: T:ToSic.Cre8magic.Breadcrumb.Settings.MagicBreadcrumbSettings
  parent: ToSic.Cre8magic.Breadcrumb.Settings
  href: ToSic.Cre8magic.Breadcrumb.Settings.MagicBreadcrumbSettings.html
  name: MagicBreadcrumbSettings
  nameWithType: MagicBreadcrumbSettings
  fullName: ToSic.Cre8magic.Breadcrumb.Settings.MagicBreadcrumbSettings
- uid: ToSic.Cre8magic.Breadcrumb.Settings
  commentId: N:ToSic.Cre8magic.Breadcrumb.Settings
  href: ToSic.html
  name: ToSic.Cre8magic.Breadcrumb.Settings
  nameWithType: ToSic.Cre8magic.Breadcrumb.Settings
  fullName: ToSic.Cre8magic.Breadcrumb.Settings
  spec.csharp:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Breadcrumb
    name: Breadcrumb
    href: ToSic.Cre8magic.Breadcrumb.html
  - name: .
  - uid: ToSic.Cre8magic.Breadcrumb.Settings
    name: Settings
    href: ToSic.Cre8magic.Breadcrumb.Settings.html
  spec.vb:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Breadcrumb
    name: Breadcrumb
    href: ToSic.Cre8magic.Breadcrumb.html
  - name: .
  - uid: ToSic.Cre8magic.Breadcrumb.Settings
    name: Settings
    href: ToSic.Cre8magic.Breadcrumb.Settings.html
