### YamlMime:ManagedReference
items:
- uid: ToSic.Cre8magic.Settings.PairOnOff
  commentId: T:ToSic.Cre8magic.Settings.PairOnOff
  id: PairOnOff
  parent: ToSic.Cre8magic.Settings
  children:
  - ToSic.Cre8magic.Settings.PairOnOff.#ctor
  - ToSic.Cre8magic.Settings.PairOnOff.#ctor(System.String,System.String)
  - ToSic.Cre8magic.Settings.PairOnOff.CloneUnder(ToSic.Cre8magic.Settings.PairOnOff,System.Boolean)
  - ToSic.Cre8magic.Settings.PairOnOff.Off
  - ToSic.Cre8magic.Settings.PairOnOff.On
  langs:
  - csharp
  - vb
  name: PairOnOff
  nameWithType: PairOnOff
  fullName: ToSic.Cre8magic.Settings.PairOnOff
  type: Class
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/PairOnOff.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: PairOnOff
    path: ../ToSic.Cre8Magic.Client/Settings/PairOnOff.cs
    startLine: 8
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings
  summary: >-
    Simple Object containing a setting to be used when a value is on or off.

    Typically used to specify strings to place in classes when something is active, is home, etc.
  example: []
  syntax:
    content: public class PairOnOff
    content.vb: Public Class PairOnOff
  inheritance:
  - System.Object
  extensionMethods:
  - ToSic.Cre8magic.Settings.PairOnOff.ToSic.Cre8magic.Settings.PairOnOffExtensions.Get(System.Nullable{System.Boolean})
- uid: ToSic.Cre8magic.Settings.PairOnOff.#ctor
  commentId: M:ToSic.Cre8magic.Settings.PairOnOff.#ctor
  id: '#ctor'
  parent: ToSic.Cre8magic.Settings.PairOnOff
  langs:
  - csharp
  - vb
  name: PairOnOff()
  nameWithType: PairOnOff.PairOnOff()
  fullName: ToSic.Cre8magic.Settings.PairOnOff.PairOnOff()
  type: Constructor
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/PairOnOff.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: .ctor
    path: ../ToSic.Cre8Magic.Client/Settings/PairOnOff.cs
    startLine: 13
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings
  summary: Empty constructor for JSON serialization
  example: []
  syntax:
    content: public PairOnOff()
    content.vb: Public Sub New()
  overload: ToSic.Cre8magic.Settings.PairOnOff.#ctor*
  nameWithType.vb: PairOnOff.New()
  fullName.vb: ToSic.Cre8magic.Settings.PairOnOff.New()
  name.vb: New()
- uid: ToSic.Cre8magic.Settings.PairOnOff.#ctor(System.String,System.String)
  commentId: M:ToSic.Cre8magic.Settings.PairOnOff.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: ToSic.Cre8magic.Settings.PairOnOff
  langs:
  - csharp
  - vb
  name: PairOnOff(string?, string?)
  nameWithType: PairOnOff.PairOnOff(string?, string?)
  fullName: ToSic.Cre8magic.Settings.PairOnOff.PairOnOff(string?, string?)
  type: Constructor
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/PairOnOff.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: .ctor
    path: ../ToSic.Cre8Magic.Client/Settings/PairOnOff.cs
    startLine: 15
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings
  syntax:
    content: public PairOnOff(string? on, string? off = null)
    parameters:
    - id: on
      type: System.String
    - id: off
      type: System.String
    content.vb: Public Sub New([on] As String, off As String = Nothing)
  overload: ToSic.Cre8magic.Settings.PairOnOff.#ctor*
  nameWithType.vb: PairOnOff.New(String, String)
  fullName.vb: ToSic.Cre8magic.Settings.PairOnOff.New(String, String)
  name.vb: New(String, String)
- uid: ToSic.Cre8magic.Settings.PairOnOff.On
  commentId: P:ToSic.Cre8magic.Settings.PairOnOff.On
  id: On
  parent: ToSic.Cre8magic.Settings.PairOnOff
  langs:
  - csharp
  - vb
  name: On
  nameWithType: PairOnOff.On
  fullName: ToSic.Cre8magic.Settings.PairOnOff.On
  type: Property
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/PairOnOff.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: On
    path: ../ToSic.Cre8Magic.Client/Settings/PairOnOff.cs
    startLine: 24
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings
  summary: Value / Class to add if the setting is on
  example: []
  syntax:
    content: public string? On { get; init; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property [On] As String
  overload: ToSic.Cre8magic.Settings.PairOnOff.On*
- uid: ToSic.Cre8magic.Settings.PairOnOff.Off
  commentId: P:ToSic.Cre8magic.Settings.PairOnOff.Off
  id: Off
  parent: ToSic.Cre8magic.Settings.PairOnOff
  langs:
  - csharp
  - vb
  name: Off
  nameWithType: PairOnOff.Off
  fullName: ToSic.Cre8magic.Settings.PairOnOff.Off
  type: Property
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/PairOnOff.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: Off
    path: ../ToSic.Cre8Magic.Client/Settings/PairOnOff.cs
    startLine: 29
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings
  summary: Value / Class to add if the setting is off
  example: []
  syntax:
    content: public string? Off { get; init; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Off As String
  overload: ToSic.Cre8magic.Settings.PairOnOff.Off*
- uid: ToSic.Cre8magic.Settings.PairOnOff.CloneUnder(ToSic.Cre8magic.Settings.PairOnOff,System.Boolean)
  commentId: M:ToSic.Cre8magic.Settings.PairOnOff.CloneUnder(ToSic.Cre8magic.Settings.PairOnOff,System.Boolean)
  id: CloneUnder(ToSic.Cre8magic.Settings.PairOnOff,System.Boolean)
  parent: ToSic.Cre8magic.Settings.PairOnOff
  langs:
  - csharp
  - vb
  name: CloneUnder(PairOnOff?, bool)
  nameWithType: PairOnOff.CloneUnder(PairOnOff?, bool)
  fullName: ToSic.Cre8magic.Settings.PairOnOff.CloneUnder(ToSic.Cre8magic.Settings.PairOnOff?, bool)
  type: Method
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/PairOnOff.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: CloneUnder
    path: ../ToSic.Cre8Magic.Client/Settings/PairOnOff.cs
    startLine: 31
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings
  example: []
  syntax:
    content: public PairOnOff CloneUnder(PairOnOff? priority, bool forceCopy = false)
    parameters:
    - id: priority
      type: ToSic.Cre8magic.Settings.PairOnOff
    - id: forceCopy
      type: System.Boolean
    return:
      type: ToSic.Cre8magic.Settings.PairOnOff
    content.vb: Public Function CloneUnder(priority As PairOnOff, forceCopy As Boolean = False) As PairOnOff
  overload: ToSic.Cre8magic.Settings.PairOnOff.CloneUnder*
  nameWithType.vb: PairOnOff.CloneUnder(PairOnOff, Boolean)
  fullName.vb: ToSic.Cre8magic.Settings.PairOnOff.CloneUnder(ToSic.Cre8magic.Settings.PairOnOff, Boolean)
  name.vb: CloneUnder(PairOnOff, Boolean)
references:
- uid: ToSic.Cre8magic.Settings
  commentId: N:ToSic.Cre8magic.Settings
  href: ToSic.html
  name: ToSic.Cre8magic.Settings
  nameWithType: ToSic.Cre8magic.Settings
  fullName: ToSic.Cre8magic.Settings
  spec.csharp:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
  spec.vb:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: ToSic.Cre8magic.Settings.PairOnOff.ToSic.Cre8magic.Settings.PairOnOffExtensions.Get(System.Nullable{System.Boolean})
  commentId: M:ToSic.Cre8magic.Settings.PairOnOffExtensions.Get(ToSic.Cre8magic.Settings.PairOnOff,System.Nullable{System.Boolean})
  parent: ToSic.Cre8magic.Settings.PairOnOffExtensions
  definition: ToSic.Cre8magic.Settings.PairOnOffExtensions.Get(ToSic.Cre8magic.Settings.PairOnOff,System.Nullable{System.Boolean})
  href: ToSic.Cre8magic.Settings.PairOnOffExtensions.html#ToSic_Cre8magic_Settings_PairOnOffExtensions_Get_ToSic_Cre8magic_Settings_PairOnOff_System_Nullable_System_Boolean__
  name: Get(PairOnOff, bool?)
  nameWithType: PairOnOffExtensions.Get(PairOnOff, bool?)
  fullName: ToSic.Cre8magic.Settings.PairOnOffExtensions.Get(ToSic.Cre8magic.Settings.PairOnOff, bool?)
  nameWithType.vb: PairOnOffExtensions.Get(PairOnOff, Boolean?)
  fullName.vb: ToSic.Cre8magic.Settings.PairOnOffExtensions.Get(ToSic.Cre8magic.Settings.PairOnOff, Boolean?)
  name.vb: Get(PairOnOff, Boolean?)
  spec.csharp:
  - uid: ToSic.Cre8magic.Settings.PairOnOffExtensions.Get(ToSic.Cre8magic.Settings.PairOnOff,System.Nullable{System.Boolean})
    name: Get
    href: ToSic.Cre8magic.Settings.PairOnOffExtensions.html#ToSic_Cre8magic_Settings_PairOnOffExtensions_Get_ToSic_Cre8magic_Settings_PairOnOff_System_Nullable_System_Boolean__
  - name: (
  - uid: ToSic.Cre8magic.Settings.PairOnOff
    name: PairOnOff
    href: ToSic.Cre8magic.Settings.PairOnOff.html
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: bool
    isExternal: true
  - name: '?'
  - name: )
  spec.vb:
  - uid: ToSic.Cre8magic.Settings.PairOnOffExtensions.Get(ToSic.Cre8magic.Settings.PairOnOff,System.Nullable{System.Boolean})
    name: Get
    href: ToSic.Cre8magic.Settings.PairOnOffExtensions.html#ToSic_Cre8magic_Settings_PairOnOffExtensions_Get_ToSic_Cre8magic_Settings_PairOnOff_System_Nullable_System_Boolean__
  - name: (
  - uid: ToSic.Cre8magic.Settings.PairOnOff
    name: PairOnOff
    href: ToSic.Cre8magic.Settings.PairOnOff.html
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: Boolean
    isExternal: true
  - name: '?'
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: ToSic.Cre8magic.Settings.PairOnOffExtensions.Get(ToSic.Cre8magic.Settings.PairOnOff,System.Nullable{System.Boolean})
  commentId: M:ToSic.Cre8magic.Settings.PairOnOffExtensions.Get(ToSic.Cre8magic.Settings.PairOnOff,System.Nullable{System.Boolean})
  isExternal: true
  href: ToSic.Cre8magic.Settings.PairOnOffExtensions.html#ToSic_Cre8magic_Settings_PairOnOffExtensions_Get_ToSic_Cre8magic_Settings_PairOnOff_System_Nullable_System_Boolean__
  name: Get(PairOnOff, bool?)
  nameWithType: PairOnOffExtensions.Get(PairOnOff, bool?)
  fullName: ToSic.Cre8magic.Settings.PairOnOffExtensions.Get(ToSic.Cre8magic.Settings.PairOnOff, bool?)
  nameWithType.vb: PairOnOffExtensions.Get(PairOnOff, Boolean?)
  fullName.vb: ToSic.Cre8magic.Settings.PairOnOffExtensions.Get(ToSic.Cre8magic.Settings.PairOnOff, Boolean?)
  name.vb: Get(PairOnOff, Boolean?)
  spec.csharp:
  - uid: ToSic.Cre8magic.Settings.PairOnOffExtensions.Get(ToSic.Cre8magic.Settings.PairOnOff,System.Nullable{System.Boolean})
    name: Get
    href: ToSic.Cre8magic.Settings.PairOnOffExtensions.html#ToSic_Cre8magic_Settings_PairOnOffExtensions_Get_ToSic_Cre8magic_Settings_PairOnOff_System_Nullable_System_Boolean__
  - name: (
  - uid: ToSic.Cre8magic.Settings.PairOnOff
    name: PairOnOff
    href: ToSic.Cre8magic.Settings.PairOnOff.html
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: bool
    isExternal: true
  - name: '?'
  - name: )
  spec.vb:
  - uid: ToSic.Cre8magic.Settings.PairOnOffExtensions.Get(ToSic.Cre8magic.Settings.PairOnOff,System.Nullable{System.Boolean})
    name: Get
    href: ToSic.Cre8magic.Settings.PairOnOffExtensions.html#ToSic_Cre8magic_Settings_PairOnOffExtensions_Get_ToSic_Cre8magic_Settings_PairOnOff_System_Nullable_System_Boolean__
  - name: (
  - uid: ToSic.Cre8magic.Settings.PairOnOff
    name: PairOnOff
    href: ToSic.Cre8magic.Settings.PairOnOff.html
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: Boolean
    isExternal: true
  - name: '?'
  - name: )
- uid: ToSic.Cre8magic.Settings.PairOnOffExtensions
  commentId: T:ToSic.Cre8magic.Settings.PairOnOffExtensions
  parent: ToSic.Cre8magic.Settings
  href: ToSic.Cre8magic.Settings.PairOnOffExtensions.html
  name: PairOnOffExtensions
  nameWithType: PairOnOffExtensions
  fullName: ToSic.Cre8magic.Settings.PairOnOffExtensions
- uid: ToSic.Cre8magic.Settings.PairOnOff.#ctor*
  commentId: Overload:ToSic.Cre8magic.Settings.PairOnOff.#ctor
  href: ToSic.Cre8magic.Settings.PairOnOff.html#ToSic_Cre8magic_Settings_PairOnOff__ctor
  name: PairOnOff
  nameWithType: PairOnOff.PairOnOff
  fullName: ToSic.Cre8magic.Settings.PairOnOff.PairOnOff
  nameWithType.vb: PairOnOff.New
  fullName.vb: ToSic.Cre8magic.Settings.PairOnOff.New
  name.vb: New
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: ToSic.Cre8magic.Settings.PairOnOff.On*
  commentId: Overload:ToSic.Cre8magic.Settings.PairOnOff.On
  href: ToSic.Cre8magic.Settings.PairOnOff.html#ToSic_Cre8magic_Settings_PairOnOff_On
  name: On
  nameWithType: PairOnOff.On
  fullName: ToSic.Cre8magic.Settings.PairOnOff.On
- uid: ToSic.Cre8magic.Settings.PairOnOff.Off*
  commentId: Overload:ToSic.Cre8magic.Settings.PairOnOff.Off
  href: ToSic.Cre8magic.Settings.PairOnOff.html#ToSic_Cre8magic_Settings_PairOnOff_Off
  name: Off
  nameWithType: PairOnOff.Off
  fullName: ToSic.Cre8magic.Settings.PairOnOff.Off
- uid: ToSic.Cre8magic.Settings.PairOnOff.CloneUnder*
  commentId: Overload:ToSic.Cre8magic.Settings.PairOnOff.CloneUnder
  href: ToSic.Cre8magic.Settings.PairOnOff.html#ToSic_Cre8magic_Settings_PairOnOff_CloneUnder_ToSic_Cre8magic_Settings_PairOnOff_System_Boolean_
  name: CloneUnder
  nameWithType: PairOnOff.CloneUnder
  fullName: ToSic.Cre8magic.Settings.PairOnOff.CloneUnder
- uid: ToSic.Cre8magic.Settings.PairOnOff
  commentId: T:ToSic.Cre8magic.Settings.PairOnOff
  parent: ToSic.Cre8magic.Settings
  href: ToSic.Cre8magic.Settings.PairOnOff.html
  name: PairOnOff
  nameWithType: PairOnOff
  fullName: ToSic.Cre8magic.Settings.PairOnOff
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
