### YamlMime:ManagedReference
items:
- uid: ToSic.Cre8magic.Themes.Settings.MagicThemePartSettings
  commentId: T:ToSic.Cre8magic.Themes.Settings.MagicThemePartSettings
  id: MagicThemePartSettings
  parent: ToSic.Cre8magic.Themes.Settings
  children:
  - ToSic.Cre8magic.Themes.Settings.MagicThemePartSettings.#ctor(System.Boolean)
  - ToSic.Cre8magic.Themes.Settings.MagicThemePartSettings.#ctor(System.String)
  - ToSic.Cre8magic.Themes.Settings.MagicThemePartSettings.Design
  - ToSic.Cre8magic.Themes.Settings.MagicThemePartSettings.Settings
  - ToSic.Cre8magic.Themes.Settings.MagicThemePartSettings.Show
  langs:
  - csharp
  - vb
  name: MagicThemePartSettings
  nameWithType: MagicThemePartSettings
  fullName: ToSic.Cre8magic.Themes.Settings.MagicThemePartSettings
  type: Class
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Themes/Settings/MagicThemePartSettings.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: MagicThemePartSettings
    path: ../ToSic.Cre8Magic.Client/Themes/Settings/MagicThemePartSettings.cs
    startLine: 6
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Themes.Settings
  syntax:
    content: >-
      [JsonConverter(typeof(ThemePartJsonConverter))]

      public record MagicThemePartSettings
    content.vb: >-
      <JsonConverter(GetType(ThemePartJsonConverter))>

      Public Class MagicThemePartSettings
  inheritance:
  - System.Object
- uid: ToSic.Cre8magic.Themes.Settings.MagicThemePartSettings.#ctor(System.Boolean)
  commentId: M:ToSic.Cre8magic.Themes.Settings.MagicThemePartSettings.#ctor(System.Boolean)
  id: '#ctor(System.Boolean)'
  parent: ToSic.Cre8magic.Themes.Settings.MagicThemePartSettings
  langs:
  - csharp
  - vb
  name: MagicThemePartSettings(bool)
  nameWithType: MagicThemePartSettings.MagicThemePartSettings(bool)
  fullName: ToSic.Cre8magic.Themes.Settings.MagicThemePartSettings.MagicThemePartSettings(bool)
  type: Constructor
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Themes/Settings/MagicThemePartSettings.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: .ctor
    path: ../ToSic.Cre8Magic.Client/Themes/Settings/MagicThemePartSettings.cs
    startLine: 24
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Themes.Settings
  syntax:
    content: public MagicThemePartSettings(bool show)
    parameters:
    - id: show
      type: System.Boolean
    content.vb: Public Sub New(show As Boolean)
  overload: ToSic.Cre8magic.Themes.Settings.MagicThemePartSettings.#ctor*
  nameWithType.vb: MagicThemePartSettings.New(Boolean)
  fullName.vb: ToSic.Cre8magic.Themes.Settings.MagicThemePartSettings.New(Boolean)
  name.vb: New(Boolean)
- uid: ToSic.Cre8magic.Themes.Settings.MagicThemePartSettings.#ctor(System.String)
  commentId: M:ToSic.Cre8magic.Themes.Settings.MagicThemePartSettings.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: ToSic.Cre8magic.Themes.Settings.MagicThemePartSettings
  langs:
  - csharp
  - vb
  name: MagicThemePartSettings(string)
  nameWithType: MagicThemePartSettings.MagicThemePartSettings(string)
  fullName: ToSic.Cre8magic.Themes.Settings.MagicThemePartSettings.MagicThemePartSettings(string)
  type: Constructor
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Themes/Settings/MagicThemePartSettings.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: .ctor
    path: ../ToSic.Cre8Magic.Client/Themes/Settings/MagicThemePartSettings.cs
    startLine: 31
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Themes.Settings
  syntax:
    content: public MagicThemePartSettings(string name)
    parameters:
    - id: name
      type: System.String
    content.vb: Public Sub New(name As String)
  overload: ToSic.Cre8magic.Themes.Settings.MagicThemePartSettings.#ctor*
  nameWithType.vb: MagicThemePartSettings.New(String)
  fullName.vb: ToSic.Cre8magic.Themes.Settings.MagicThemePartSettings.New(String)
  name.vb: New(String)
- uid: ToSic.Cre8magic.Themes.Settings.MagicThemePartSettings.Show
  commentId: P:ToSic.Cre8magic.Themes.Settings.MagicThemePartSettings.Show
  id: Show
  parent: ToSic.Cre8magic.Themes.Settings.MagicThemePartSettings
  langs:
  - csharp
  - vb
  name: Show
  nameWithType: MagicThemePartSettings.Show
  fullName: ToSic.Cre8magic.Themes.Settings.MagicThemePartSettings.Show
  type: Property
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Themes/Settings/MagicThemePartSettings.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: Show
    path: ../ToSic.Cre8Magic.Client/Themes/Settings/MagicThemePartSettings.cs
    startLine: 43
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Themes.Settings
  summary: >-
    Determines if this part should be shown or not.


    This allows you to configure to show / not show certain bits like breadcrumbs in certain scenarios.
  example: []
  syntax:
    content: public bool? Show { get; init; }
    parameters: []
    return:
      type: System.Nullable{System.Boolean}
    content.vb: Public Property Show As Boolean?
  overload: ToSic.Cre8magic.Themes.Settings.MagicThemePartSettings.Show*
- uid: ToSic.Cre8magic.Themes.Settings.MagicThemePartSettings.Design
  commentId: P:ToSic.Cre8magic.Themes.Settings.MagicThemePartSettings.Design
  id: Design
  parent: ToSic.Cre8magic.Themes.Settings.MagicThemePartSettings
  langs:
  - csharp
  - vb
  name: Design
  nameWithType: MagicThemePartSettings.Design
  fullName: ToSic.Cre8magic.Themes.Settings.MagicThemePartSettings.Design
  type: Property
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Themes/Settings/MagicThemePartSettings.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: Design
    path: ../ToSic.Cre8Magic.Client/Themes/Settings/MagicThemePartSettings.cs
    startLine: 48
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Themes.Settings
  summary: Name of the design settings to look up.
  example: []
  syntax:
    content: public string? Design { get; init; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Design As String
  overload: ToSic.Cre8magic.Themes.Settings.MagicThemePartSettings.Design*
- uid: ToSic.Cre8magic.Themes.Settings.MagicThemePartSettings.Settings
  commentId: P:ToSic.Cre8magic.Themes.Settings.MagicThemePartSettings.Settings
  id: Settings
  parent: ToSic.Cre8magic.Themes.Settings.MagicThemePartSettings
  langs:
  - csharp
  - vb
  name: Settings
  nameWithType: MagicThemePartSettings.Settings
  fullName: ToSic.Cre8magic.Themes.Settings.MagicThemePartSettings.Settings
  type: Property
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Themes/Settings/MagicThemePartSettings.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: Settings
    path: ../ToSic.Cre8Magic.Client/Themes/Settings/MagicThemePartSettings.cs
    startLine: 53
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Themes.Settings
  summary: Name of the settings to look up.
  example: []
  syntax:
    content: public string? Settings { get; init; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Settings As String
  overload: ToSic.Cre8magic.Themes.Settings.MagicThemePartSettings.Settings*
references:
- uid: ToSic.Cre8magic.Themes.Settings
  commentId: N:ToSic.Cre8magic.Themes.Settings
  href: ToSic.html
  name: ToSic.Cre8magic.Themes.Settings
  nameWithType: ToSic.Cre8magic.Themes.Settings
  fullName: ToSic.Cre8magic.Themes.Settings
  spec.csharp:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Themes
    name: Themes
    href: ToSic.Cre8magic.Themes.html
  - name: .
  - uid: ToSic.Cre8magic.Themes.Settings
    name: Settings
    href: ToSic.Cre8magic.Themes.Settings.html
  spec.vb:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Themes
    name: Themes
    href: ToSic.Cre8magic.Themes.html
  - name: .
  - uid: ToSic.Cre8magic.Themes.Settings
    name: Settings
    href: ToSic.Cre8magic.Themes.Settings.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: ToSic.Cre8magic.Themes.Settings.MagicThemePartSettings.#ctor*
  commentId: Overload:ToSic.Cre8magic.Themes.Settings.MagicThemePartSettings.#ctor
  href: ToSic.Cre8magic.Themes.Settings.MagicThemePartSettings.html#ToSic_Cre8magic_Themes_Settings_MagicThemePartSettings__ctor_System_Boolean_
  name: MagicThemePartSettings
  nameWithType: MagicThemePartSettings.MagicThemePartSettings
  fullName: ToSic.Cre8magic.Themes.Settings.MagicThemePartSettings.MagicThemePartSettings
  nameWithType.vb: MagicThemePartSettings.New
  fullName.vb: ToSic.Cre8magic.Themes.Settings.MagicThemePartSettings.New
  name.vb: New
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: ToSic.Cre8magic.Themes.Settings.MagicThemePartSettings.Show*
  commentId: Overload:ToSic.Cre8magic.Themes.Settings.MagicThemePartSettings.Show
  href: ToSic.Cre8magic.Themes.Settings.MagicThemePartSettings.html#ToSic_Cre8magic_Themes_Settings_MagicThemePartSettings_Show
  name: Show
  nameWithType: MagicThemePartSettings.Show
  fullName: ToSic.Cre8magic.Themes.Settings.MagicThemePartSettings.Show
- uid: System.Nullable{System.Boolean}
  commentId: T:System.Nullable{System.Boolean}
  parent: System
  definition: System.Nullable`1
  name: bool?
  nameWithType: bool?
  fullName: bool?
  nameWithType.vb: Boolean?
  fullName.vb: Boolean?
  name.vb: Boolean?
  spec.csharp:
  - uid: System.Boolean
    name: bool
    isExternal: true
  - name: '?'
  spec.vb:
  - uid: System.Boolean
    name: Boolean
    isExternal: true
  - name: '?'
- uid: System.Nullable`1
  commentId: T:System.Nullable`1
  isExternal: true
  name: Nullable<T>
  nameWithType: Nullable<T>
  fullName: System.Nullable<T>
  nameWithType.vb: Nullable(Of T)
  fullName.vb: System.Nullable(Of T)
  name.vb: Nullable(Of T)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    isExternal: true
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: ToSic.Cre8magic.Themes.Settings.MagicThemePartSettings.Design*
  commentId: Overload:ToSic.Cre8magic.Themes.Settings.MagicThemePartSettings.Design
  href: ToSic.Cre8magic.Themes.Settings.MagicThemePartSettings.html#ToSic_Cre8magic_Themes_Settings_MagicThemePartSettings_Design
  name: Design
  nameWithType: MagicThemePartSettings.Design
  fullName: ToSic.Cre8magic.Themes.Settings.MagicThemePartSettings.Design
- uid: ToSic.Cre8magic.Themes.Settings.MagicThemePartSettings.Settings*
  commentId: Overload:ToSic.Cre8magic.Themes.Settings.MagicThemePartSettings.Settings
  href: ToSic.Cre8magic.Themes.Settings.MagicThemePartSettings.html#ToSic_Cre8magic_Themes_Settings_MagicThemePartSettings_Settings
  name: Settings
  nameWithType: MagicThemePartSettings.Settings
  fullName: ToSic.Cre8magic.Themes.Settings.MagicThemePartSettings.Settings
