### YamlMime:ManagedReference
items:
- uid: ToSic.Cre8magic.Settings.Internal.Json.MagicSettingsCatalogLoaderJson
  commentId: T:ToSic.Cre8magic.Settings.Internal.Json.MagicSettingsCatalogLoaderJson
  id: MagicSettingsCatalogLoaderJson
  parent: ToSic.Cre8magic.Settings.Internal.Json
  children:
  - ToSic.Cre8magic.Settings.Internal.Json.MagicSettingsCatalogLoaderJson.#ctor(Microsoft.Extensions.Logging.ILogger{ToSic.Cre8magic.Settings.Internal.Json.MagicSettingsCatalogLoaderJson})
  - ToSic.Cre8magic.Settings.Internal.Json.MagicSettingsCatalogLoaderJson.LoadJson(ToSic.Cre8magic.Themes.MagicThemePackage)
  - ToSic.Cre8magic.Settings.Internal.Json.MagicSettingsCatalogLoaderJson.Logger
  langs:
  - csharp
  - vb
  name: MagicSettingsCatalogLoaderJson
  nameWithType: MagicSettingsCatalogLoaderJson
  fullName: ToSic.Cre8magic.Settings.Internal.Json.MagicSettingsCatalogLoaderJson
  type: Class
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/Internal/Json/MagicSettingsCatalogLoaderJson.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: MagicSettingsCatalogLoaderJson
    path: ../ToSic.Cre8Magic.Client/Settings/Internal/Json/MagicSettingsCatalogLoaderJson.cs
    startLine: 8
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings.Internal.Json
  syntax:
    content: public class MagicSettingsCatalogLoaderJson
    content.vb: Public Class MagicSettingsCatalogLoaderJson
  inheritance:
  - System.Object
- uid: ToSic.Cre8magic.Settings.Internal.Json.MagicSettingsCatalogLoaderJson.#ctor(Microsoft.Extensions.Logging.ILogger{ToSic.Cre8magic.Settings.Internal.Json.MagicSettingsCatalogLoaderJson})
  commentId: M:ToSic.Cre8magic.Settings.Internal.Json.MagicSettingsCatalogLoaderJson.#ctor(Microsoft.Extensions.Logging.ILogger{ToSic.Cre8magic.Settings.Internal.Json.MagicSettingsCatalogLoaderJson})
  id: '#ctor(Microsoft.Extensions.Logging.ILogger{ToSic.Cre8magic.Settings.Internal.Json.MagicSettingsCatalogLoaderJson})'
  parent: ToSic.Cre8magic.Settings.Internal.Json.MagicSettingsCatalogLoaderJson
  langs:
  - csharp
  - vb
  name: MagicSettingsCatalogLoaderJson(ILogger<MagicSettingsCatalogLoaderJson>)
  nameWithType: MagicSettingsCatalogLoaderJson.MagicSettingsCatalogLoaderJson(ILogger<MagicSettingsCatalogLoaderJson>)
  fullName: ToSic.Cre8magic.Settings.Internal.Json.MagicSettingsCatalogLoaderJson.MagicSettingsCatalogLoaderJson(Microsoft.Extensions.Logging.ILogger<ToSic.Cre8magic.Settings.Internal.Json.MagicSettingsCatalogLoaderJson>)
  type: Constructor
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/Internal/Json/MagicSettingsCatalogLoaderJson.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: .ctor
    path: ../ToSic.Cre8Magic.Client/Settings/Internal/Json/MagicSettingsCatalogLoaderJson.cs
    startLine: 8
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings.Internal.Json
  syntax:
    content: public MagicSettingsCatalogLoaderJson(ILogger<MagicSettingsCatalogLoaderJson> logger)
    parameters:
    - id: logger
      type: Microsoft.Extensions.Logging.ILogger{ToSic.Cre8magic.Settings.Internal.Json.MagicSettingsCatalogLoaderJson}
    content.vb: Public Sub New(logger As ILogger(Of MagicSettingsCatalogLoaderJson))
  overload: ToSic.Cre8magic.Settings.Internal.Json.MagicSettingsCatalogLoaderJson.#ctor*
  nameWithType.vb: MagicSettingsCatalogLoaderJson.New(ILogger(Of MagicSettingsCatalogLoaderJson))
  fullName.vb: ToSic.Cre8magic.Settings.Internal.Json.MagicSettingsCatalogLoaderJson.New(Microsoft.Extensions.Logging.ILogger(Of ToSic.Cre8magic.Settings.Internal.Json.MagicSettingsCatalogLoaderJson))
  name.vb: New(ILogger(Of MagicSettingsCatalogLoaderJson))
- uid: ToSic.Cre8magic.Settings.Internal.Json.MagicSettingsCatalogLoaderJson.Logger
  commentId: P:ToSic.Cre8magic.Settings.Internal.Json.MagicSettingsCatalogLoaderJson.Logger
  id: Logger
  parent: ToSic.Cre8magic.Settings.Internal.Json.MagicSettingsCatalogLoaderJson
  langs:
  - csharp
  - vb
  name: Logger
  nameWithType: MagicSettingsCatalogLoaderJson.Logger
  fullName: ToSic.Cre8magic.Settings.Internal.Json.MagicSettingsCatalogLoaderJson.Logger
  type: Property
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/Internal/Json/MagicSettingsCatalogLoaderJson.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: Logger
    path: ../ToSic.Cre8Magic.Client/Settings/Internal/Json/MagicSettingsCatalogLoaderJson.cs
    startLine: 10
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings.Internal.Json
  syntax:
    content: public ILogger<MagicSettingsCatalogLoaderJson> Logger { get; }
    parameters: []
    return:
      type: Microsoft.Extensions.Logging.ILogger{ToSic.Cre8magic.Settings.Internal.Json.MagicSettingsCatalogLoaderJson}
    content.vb: Public ReadOnly Property Logger As ILogger(Of MagicSettingsCatalogLoaderJson)
  overload: ToSic.Cre8magic.Settings.Internal.Json.MagicSettingsCatalogLoaderJson.Logger*
- uid: ToSic.Cre8magic.Settings.Internal.Json.MagicSettingsCatalogLoaderJson.LoadJson(ToSic.Cre8magic.Themes.MagicThemePackage)
  commentId: M:ToSic.Cre8magic.Settings.Internal.Json.MagicSettingsCatalogLoaderJson.LoadJson(ToSic.Cre8magic.Themes.MagicThemePackage)
  id: LoadJson(ToSic.Cre8magic.Themes.MagicThemePackage)
  parent: ToSic.Cre8magic.Settings.Internal.Json.MagicSettingsCatalogLoaderJson
  langs:
  - csharp
  - vb
  name: LoadJson(MagicThemePackage)
  nameWithType: MagicSettingsCatalogLoaderJson.LoadJson(MagicThemePackage)
  fullName: ToSic.Cre8magic.Settings.Internal.Json.MagicSettingsCatalogLoaderJson.LoadJson(ToSic.Cre8magic.Themes.MagicThemePackage)
  type: Method
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/Internal/Json/MagicSettingsCatalogLoaderJson.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: LoadJson
    path: ../ToSic.Cre8Magic.Client/Settings/Internal/Json/MagicSettingsCatalogLoaderJson.cs
    startLine: 12
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings.Internal.Json
  syntax:
    content: public DataWithJournal<MagicSettingsCatalog> LoadJson(MagicThemePackage themeConfig)
    parameters:
    - id: themeConfig
      type: ToSic.Cre8magic.Themes.MagicThemePackage
    return:
      type: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal{ToSic.Cre8magic.Settings.MagicSettingsCatalog}
    content.vb: Public Function LoadJson(themeConfig As MagicThemePackage) As DataWithJournal(Of MagicSettingsCatalog)
  overload: ToSic.Cre8magic.Settings.Internal.Json.MagicSettingsCatalogLoaderJson.LoadJson*
references:
- uid: ToSic.Cre8magic.Settings.Internal.Json
  commentId: N:ToSic.Cre8magic.Settings.Internal.Json
  href: ToSic.html
  name: ToSic.Cre8magic.Settings.Internal.Json
  nameWithType: ToSic.Cre8magic.Settings.Internal.Json
  fullName: ToSic.Cre8magic.Settings.Internal.Json
  spec.csharp:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Internal
    name: Internal
    href: ToSic.Cre8magic.Settings.Internal.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Internal.Json
    name: Json
    href: ToSic.Cre8magic.Settings.Internal.Json.html
  spec.vb:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Internal
    name: Internal
    href: ToSic.Cre8magic.Settings.Internal.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Internal.Json
    name: Json
    href: ToSic.Cre8magic.Settings.Internal.Json.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: ToSic.Cre8magic.Settings.Internal.Json.MagicSettingsCatalogLoaderJson.#ctor*
  commentId: Overload:ToSic.Cre8magic.Settings.Internal.Json.MagicSettingsCatalogLoaderJson.#ctor
  href: ToSic.Cre8magic.Settings.Internal.Json.MagicSettingsCatalogLoaderJson.html#ToSic_Cre8magic_Settings_Internal_Json_MagicSettingsCatalogLoaderJson__ctor_Microsoft_Extensions_Logging_ILogger_ToSic_Cre8magic_Settings_Internal_Json_MagicSettingsCatalogLoaderJson__
  name: MagicSettingsCatalogLoaderJson
  nameWithType: MagicSettingsCatalogLoaderJson.MagicSettingsCatalogLoaderJson
  fullName: ToSic.Cre8magic.Settings.Internal.Json.MagicSettingsCatalogLoaderJson.MagicSettingsCatalogLoaderJson
  nameWithType.vb: MagicSettingsCatalogLoaderJson.New
  fullName.vb: ToSic.Cre8magic.Settings.Internal.Json.MagicSettingsCatalogLoaderJson.New
  name.vb: New
- uid: Microsoft.Extensions.Logging.ILogger{ToSic.Cre8magic.Settings.Internal.Json.MagicSettingsCatalogLoaderJson}
  commentId: T:Microsoft.Extensions.Logging.ILogger{ToSic.Cre8magic.Settings.Internal.Json.MagicSettingsCatalogLoaderJson}
  parent: Microsoft.Extensions.Logging
  definition: Microsoft.Extensions.Logging.ILogger`1
  href: https://learn.microsoft.com/dotnet/api/microsoft.extensions.logging.ilogger-1
  name: ILogger<MagicSettingsCatalogLoaderJson>
  nameWithType: ILogger<MagicSettingsCatalogLoaderJson>
  fullName: Microsoft.Extensions.Logging.ILogger<ToSic.Cre8magic.Settings.Internal.Json.MagicSettingsCatalogLoaderJson>
  nameWithType.vb: ILogger(Of MagicSettingsCatalogLoaderJson)
  fullName.vb: Microsoft.Extensions.Logging.ILogger(Of ToSic.Cre8magic.Settings.Internal.Json.MagicSettingsCatalogLoaderJson)
  name.vb: ILogger(Of MagicSettingsCatalogLoaderJson)
  spec.csharp:
  - uid: Microsoft.Extensions.Logging.ILogger`1
    name: ILogger
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.extensions.logging.ilogger-1
  - name: <
  - uid: ToSic.Cre8magic.Settings.Internal.Json.MagicSettingsCatalogLoaderJson
    name: MagicSettingsCatalogLoaderJson
    href: ToSic.Cre8magic.Settings.Internal.Json.MagicSettingsCatalogLoaderJson.html
  - name: '>'
  spec.vb:
  - uid: Microsoft.Extensions.Logging.ILogger`1
    name: ILogger
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.extensions.logging.ilogger-1
  - name: (
  - name: Of
  - name: " "
  - uid: ToSic.Cre8magic.Settings.Internal.Json.MagicSettingsCatalogLoaderJson
    name: MagicSettingsCatalogLoaderJson
    href: ToSic.Cre8magic.Settings.Internal.Json.MagicSettingsCatalogLoaderJson.html
  - name: )
- uid: Microsoft.Extensions.Logging.ILogger`1
  commentId: T:Microsoft.Extensions.Logging.ILogger`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/microsoft.extensions.logging.ilogger-1
  name: ILogger<TCategoryName>
  nameWithType: ILogger<TCategoryName>
  fullName: Microsoft.Extensions.Logging.ILogger<TCategoryName>
  nameWithType.vb: ILogger(Of TCategoryName)
  fullName.vb: Microsoft.Extensions.Logging.ILogger(Of TCategoryName)
  name.vb: ILogger(Of TCategoryName)
  spec.csharp:
  - uid: Microsoft.Extensions.Logging.ILogger`1
    name: ILogger
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.extensions.logging.ilogger-1
  - name: <
  - name: TCategoryName
  - name: '>'
  spec.vb:
  - uid: Microsoft.Extensions.Logging.ILogger`1
    name: ILogger
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.extensions.logging.ilogger-1
  - name: (
  - name: Of
  - name: " "
  - name: TCategoryName
  - name: )
- uid: Microsoft.Extensions.Logging
  commentId: N:Microsoft.Extensions.Logging
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/microsoft
  name: Microsoft.Extensions.Logging
  nameWithType: Microsoft.Extensions.Logging
  fullName: Microsoft.Extensions.Logging
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft
  - name: .
  - uid: Microsoft.Extensions
    name: Extensions
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.extensions
  - name: .
  - uid: Microsoft.Extensions.Logging
    name: Logging
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.extensions.logging
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft
  - name: .
  - uid: Microsoft.Extensions
    name: Extensions
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.extensions
  - name: .
  - uid: Microsoft.Extensions.Logging
    name: Logging
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.extensions.logging
- uid: ToSic.Cre8magic.Settings.Internal.Json.MagicSettingsCatalogLoaderJson.Logger*
  commentId: Overload:ToSic.Cre8magic.Settings.Internal.Json.MagicSettingsCatalogLoaderJson.Logger
  href: ToSic.Cre8magic.Settings.Internal.Json.MagicSettingsCatalogLoaderJson.html#ToSic_Cre8magic_Settings_Internal_Json_MagicSettingsCatalogLoaderJson_Logger
  name: Logger
  nameWithType: MagicSettingsCatalogLoaderJson.Logger
  fullName: ToSic.Cre8magic.Settings.Internal.Json.MagicSettingsCatalogLoaderJson.Logger
- uid: ToSic.Cre8magic.Settings.Internal.Json.MagicSettingsCatalogLoaderJson.LoadJson*
  commentId: Overload:ToSic.Cre8magic.Settings.Internal.Json.MagicSettingsCatalogLoaderJson.LoadJson
  href: ToSic.Cre8magic.Settings.Internal.Json.MagicSettingsCatalogLoaderJson.html#ToSic_Cre8magic_Settings_Internal_Json_MagicSettingsCatalogLoaderJson_LoadJson_ToSic_Cre8magic_Themes_MagicThemePackage_
  name: LoadJson
  nameWithType: MagicSettingsCatalogLoaderJson.LoadJson
  fullName: ToSic.Cre8magic.Settings.Internal.Json.MagicSettingsCatalogLoaderJson.LoadJson
- uid: ToSic.Cre8magic.Themes.MagicThemePackage
  commentId: T:ToSic.Cre8magic.Themes.MagicThemePackage
  parent: ToSic.Cre8magic.Themes
  href: ToSic.Cre8magic.Themes.MagicThemePackage.html
  name: MagicThemePackage
  nameWithType: MagicThemePackage
  fullName: ToSic.Cre8magic.Themes.MagicThemePackage
- uid: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal{ToSic.Cre8magic.Settings.MagicSettingsCatalog}
  commentId: T:ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal{ToSic.Cre8magic.Settings.MagicSettingsCatalog}
  parent: ToSic.Cre8magic.Settings.Internal.Journal
  definition: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal`1
  href: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal-1.html
  name: DataWithJournal<MagicSettingsCatalog>
  nameWithType: DataWithJournal<MagicSettingsCatalog>
  fullName: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal<ToSic.Cre8magic.Settings.MagicSettingsCatalog>
  nameWithType.vb: DataWithJournal(Of MagicSettingsCatalog)
  fullName.vb: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal(Of ToSic.Cre8magic.Settings.MagicSettingsCatalog)
  name.vb: DataWithJournal(Of MagicSettingsCatalog)
  spec.csharp:
  - uid: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal`1
    name: DataWithJournal
    href: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal-1.html
  - name: <
  - uid: ToSic.Cre8magic.Settings.MagicSettingsCatalog
    name: MagicSettingsCatalog
    href: ToSic.Cre8magic.Settings.MagicSettingsCatalog.html
  - name: '>'
  spec.vb:
  - uid: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal`1
    name: DataWithJournal
    href: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal-1.html
  - name: (
  - name: Of
  - name: " "
  - uid: ToSic.Cre8magic.Settings.MagicSettingsCatalog
    name: MagicSettingsCatalog
    href: ToSic.Cre8magic.Settings.MagicSettingsCatalog.html
  - name: )
- uid: ToSic.Cre8magic.Themes
  commentId: N:ToSic.Cre8magic.Themes
  href: ToSic.html
  name: ToSic.Cre8magic.Themes
  nameWithType: ToSic.Cre8magic.Themes
  fullName: ToSic.Cre8magic.Themes
  spec.csharp:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Themes
    name: Themes
    href: ToSic.Cre8magic.Themes.html
  spec.vb:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Themes
    name: Themes
    href: ToSic.Cre8magic.Themes.html
- uid: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal`1
  commentId: T:ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal`1
  href: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal-1.html
  name: DataWithJournal<T>
  nameWithType: DataWithJournal<T>
  fullName: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal<T>
  nameWithType.vb: DataWithJournal(Of T)
  fullName.vb: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal(Of T)
  name.vb: DataWithJournal(Of T)
  spec.csharp:
  - uid: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal`1
    name: DataWithJournal
    href: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal-1.html
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal`1
    name: DataWithJournal
    href: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal-1.html
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: ToSic.Cre8magic.Settings.Internal.Journal
  commentId: N:ToSic.Cre8magic.Settings.Internal.Journal
  href: ToSic.html
  name: ToSic.Cre8magic.Settings.Internal.Journal
  nameWithType: ToSic.Cre8magic.Settings.Internal.Journal
  fullName: ToSic.Cre8magic.Settings.Internal.Journal
  spec.csharp:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Internal
    name: Internal
    href: ToSic.Cre8magic.Settings.Internal.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Internal.Journal
    name: Journal
    href: ToSic.Cre8magic.Settings.Internal.Journal.html
  spec.vb:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Internal
    name: Internal
    href: ToSic.Cre8magic.Settings.Internal.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Internal.Journal
    name: Journal
    href: ToSic.Cre8magic.Settings.Internal.Journal.html
