### YamlMime:ManagedReference
items:
- uid: ToSic.Cre8magic.Settings
  commentId: N:ToSic.Cre8magic.Settings
  id: Settings
  parent: ToSic.Cre8magic
  children:
  - ToSic.Cre8magic.Settings.IMagicSettingsProvider
  - ToSic.Cre8magic.Settings.IMagicSettingsProviderSection`1
  - ToSic.Cre8magic.Settings.MagicBlueprintPart
  - ToSic.Cre8magic.Settings.MagicBlueprints
  - ToSic.Cre8magic.Settings.MagicDebugSettings
  - ToSic.Cre8magic.Settings.MagicSettingOnOff
  - ToSic.Cre8magic.Settings.MagicSettingsBase
  - ToSic.Cre8magic.Settings.MagicSettingsCatalog
  - ToSic.Cre8magic.Settings.MagicSettingsLookup
  - ToSic.Cre8magic.Settings.SettingsWithInherit
  langs:
  - csharp
  - vb
  name: ToSic.Cre8magic.Settings
  nameWithType: ToSic.Cre8magic.Settings
  fullName: ToSic.Cre8magic.Settings
  type: Namespace
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
references:
- uid: ToSic.Cre8magic.Settings.IMagicSettingsProvider
  commentId: T:ToSic.Cre8magic.Settings.IMagicSettingsProvider
  parent: ToSic.Cre8magic.Settings
  href: ToSic.Cre8magic.Settings.IMagicSettingsProvider.html
  name: IMagicSettingsProvider
  nameWithType: IMagicSettingsProvider
  fullName: ToSic.Cre8magic.Settings.IMagicSettingsProvider
- uid: ToSic.Cre8magic.Settings.IMagicSettingsProviderSection`1
  commentId: T:ToSic.Cre8magic.Settings.IMagicSettingsProviderSection`1
  href: ToSic.Cre8magic.Settings.IMagicSettingsProviderSection-1.html
  name: IMagicSettingsProviderSection<TSettings>
  nameWithType: IMagicSettingsProviderSection<TSettings>
  fullName: ToSic.Cre8magic.Settings.IMagicSettingsProviderSection<TSettings>
  nameWithType.vb: IMagicSettingsProviderSection(Of TSettings)
  fullName.vb: ToSic.Cre8magic.Settings.IMagicSettingsProviderSection(Of TSettings)
  name.vb: IMagicSettingsProviderSection(Of TSettings)
  spec.csharp:
  - uid: ToSic.Cre8magic.Settings.IMagicSettingsProviderSection`1
    name: IMagicSettingsProviderSection
    href: ToSic.Cre8magic.Settings.IMagicSettingsProviderSection-1.html
  - name: <
  - name: TSettings
  - name: '>'
  spec.vb:
  - uid: ToSic.Cre8magic.Settings.IMagicSettingsProviderSection`1
    name: IMagicSettingsProviderSection
    href: ToSic.Cre8magic.Settings.IMagicSettingsProviderSection-1.html
  - name: (
  - name: Of
  - name: " "
  - name: TSettings
  - name: )
- uid: ToSic.Cre8magic.Settings.MagicBlueprintPart
  commentId: T:ToSic.Cre8magic.Settings.MagicBlueprintPart
  parent: ToSic.Cre8magic.Settings
  href: ToSic.Cre8magic.Settings.MagicBlueprintPart.html
  name: MagicBlueprintPart
  nameWithType: MagicBlueprintPart
  fullName: ToSic.Cre8magic.Settings.MagicBlueprintPart
- uid: ToSic.Cre8magic.Settings.MagicBlueprints
  commentId: T:ToSic.Cre8magic.Settings.MagicBlueprints
  parent: ToSic.Cre8magic.Settings
  href: ToSic.Cre8magic.Settings.MagicBlueprints.html
  name: MagicBlueprints
  nameWithType: MagicBlueprints
  fullName: ToSic.Cre8magic.Settings.MagicBlueprints
- uid: ToSic.Cre8magic.Settings.MagicDebugSettings
  commentId: T:ToSic.Cre8magic.Settings.MagicDebugSettings
  parent: ToSic.Cre8magic.Settings
  href: ToSic.Cre8magic.Settings.MagicDebugSettings.html
  name: MagicDebugSettings
  nameWithType: MagicDebugSettings
  fullName: ToSic.Cre8magic.Settings.MagicDebugSettings
- uid: ToSic.Cre8magic.Settings.MagicSettingOnOff
  commentId: T:ToSic.Cre8magic.Settings.MagicSettingOnOff
  parent: ToSic.Cre8magic.Settings
  href: ToSic.Cre8magic.Settings.MagicSettingOnOff.html
  name: MagicSettingOnOff
  nameWithType: MagicSettingOnOff
  fullName: ToSic.Cre8magic.Settings.MagicSettingOnOff
- uid: ToSic.Cre8magic.Settings.MagicSettingsBase
  commentId: T:ToSic.Cre8magic.Settings.MagicSettingsBase
  parent: ToSic.Cre8magic.Settings
  href: ToSic.Cre8magic.Settings.MagicSettingsBase.html
  name: MagicSettingsBase
  nameWithType: MagicSettingsBase
  fullName: ToSic.Cre8magic.Settings.MagicSettingsBase
- uid: ToSic.Cre8magic.Settings.MagicSettingsCatalog
  commentId: T:ToSic.Cre8magic.Settings.MagicSettingsCatalog
  parent: ToSic.Cre8magic.Settings
  href: ToSic.Cre8magic.Settings.MagicSettingsCatalog.html
  name: MagicSettingsCatalog
  nameWithType: MagicSettingsCatalog
  fullName: ToSic.Cre8magic.Settings.MagicSettingsCatalog
- uid: ToSic.Cre8magic.Settings.MagicSettingsLookup
  commentId: T:ToSic.Cre8magic.Settings.MagicSettingsLookup
  parent: ToSic.Cre8magic.Settings
  href: ToSic.Cre8magic.Settings.MagicSettingsLookup.html
  name: MagicSettingsLookup
  nameWithType: MagicSettingsLookup
  fullName: ToSic.Cre8magic.Settings.MagicSettingsLookup
- uid: ToSic.Cre8magic.Settings.SettingsWithInherit
  commentId: T:ToSic.Cre8magic.Settings.SettingsWithInherit
  parent: ToSic.Cre8magic.Settings
  href: ToSic.Cre8magic.Settings.SettingsWithInherit.html
  name: SettingsWithInherit
  nameWithType: SettingsWithInherit
  fullName: ToSic.Cre8magic.Settings.SettingsWithInherit
- uid: ToSic.Cre8magic.Settings
  commentId: N:ToSic.Cre8magic.Settings
  href: ToSic.html
  name: ToSic.Cre8magic.Settings
  nameWithType: ToSic.Cre8magic.Settings
  fullName: ToSic.Cre8magic.Settings
  spec.csharp:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
  spec.vb:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
