### YamlMime:ManagedReference
items:
- uid: ToSic.Cre8magic.Settings.Internal.Sources.MagicSettingsSourcePackageDefaults
  commentId: T:ToSic.Cre8magic.Settings.Internal.Sources.MagicSettingsSourcePackageDefaults
  id: MagicSettingsSourcePackageDefaults
  parent: ToSic.Cre8magic.Settings.Internal.Sources
  children:
  - ToSic.Cre8magic.Settings.Internal.Sources.MagicSettingsSourcePackageDefaults.Catalogs(ToSic.Cre8magic.Themes.MagicThemePackage)
  - ToSic.Cre8magic.Settings.Internal.Sources.MagicSettingsSourcePackageDefaults.Priority
  langs:
  - csharp
  - vb
  name: MagicSettingsSourcePackageDefaults
  nameWithType: MagicSettingsSourcePackageDefaults
  fullName: ToSic.Cre8magic.Settings.Internal.Sources.MagicSettingsSourcePackageDefaults
  type: Class
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/Internal/Sources/MagicSettingsSourcePackageDefaults.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: MagicSettingsSourcePackageDefaults
    path: ../ToSic.Cre8Magic.Client/Settings/Internal/Sources/MagicSettingsSourcePackageDefaults.cs
    startLine: 9
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings.Internal.Sources
  summary: >-
    Load the package settings defaults.


    Fairly trivial, but the goal is that all sources implement the same interface.
  example: []
  syntax:
    content: 'public class MagicSettingsSourcePackageDefaults : IMagicSettingsSource'
    content.vb: Public Class MagicSettingsSourcePackageDefaults Implements IMagicSettingsSource
  inheritance:
  - System.Object
  implements:
  - ToSic.Cre8magic.Settings.Internal.Sources.IMagicSettingsSource
- uid: ToSic.Cre8magic.Settings.Internal.Sources.MagicSettingsSourcePackageDefaults.Priority
  commentId: P:ToSic.Cre8magic.Settings.Internal.Sources.MagicSettingsSourcePackageDefaults.Priority
  id: Priority
  parent: ToSic.Cre8magic.Settings.Internal.Sources.MagicSettingsSourcePackageDefaults
  langs:
  - csharp
  - vb
  name: Priority
  nameWithType: MagicSettingsSourcePackageDefaults.Priority
  fullName: ToSic.Cre8magic.Settings.Internal.Sources.MagicSettingsSourcePackageDefaults.Priority
  type: Property
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/Internal/Sources/MagicSettingsSourcePackageDefaults.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: Priority
    path: ../ToSic.Cre8Magic.Client/Settings/Internal/Sources/MagicSettingsSourcePackageDefaults.cs
    startLine: 11
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings.Internal.Sources
  summary: Priority, high number means higher priority
  example: []
  syntax:
    content: public int Priority { get; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public ReadOnly Property Priority As Integer
  overload: ToSic.Cre8magic.Settings.Internal.Sources.MagicSettingsSourcePackageDefaults.Priority*
  implements:
  - ToSic.Cre8magic.Settings.Internal.Sources.IMagicSettingsSource.Priority
- uid: ToSic.Cre8magic.Settings.Internal.Sources.MagicSettingsSourcePackageDefaults.Catalogs(ToSic.Cre8magic.Themes.MagicThemePackage)
  commentId: M:ToSic.Cre8magic.Settings.Internal.Sources.MagicSettingsSourcePackageDefaults.Catalogs(ToSic.Cre8magic.Themes.MagicThemePackage)
  id: Catalogs(ToSic.Cre8magic.Themes.MagicThemePackage)
  parent: ToSic.Cre8magic.Settings.Internal.Sources.MagicSettingsSourcePackageDefaults
  langs:
  - csharp
  - vb
  name: Catalogs(MagicThemePackage)
  nameWithType: MagicSettingsSourcePackageDefaults.Catalogs(MagicThemePackage)
  fullName: ToSic.Cre8magic.Settings.Internal.Sources.MagicSettingsSourcePackageDefaults.Catalogs(ToSic.Cre8magic.Themes.MagicThemePackage)
  type: Method
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/Internal/Sources/MagicSettingsSourcePackageDefaults.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: Catalogs
    path: ../ToSic.Cre8Magic.Client/Settings/Internal/Sources/MagicSettingsSourcePackageDefaults.cs
    startLine: 13
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings.Internal.Sources
  example: []
  syntax:
    content: public List<DataWithJournal<MagicSettingsCatalog>> Catalogs(MagicThemePackage themePackage)
    parameters:
    - id: themePackage
      type: ToSic.Cre8magic.Themes.MagicThemePackage
    return:
      type: System.Collections.Generic.List{ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal{ToSic.Cre8magic.Settings.MagicSettingsCatalog}}
    content.vb: Public Function Catalogs(themePackage As MagicThemePackage) As List(Of DataWithJournal(Of MagicSettingsCatalog))
  overload: ToSic.Cre8magic.Settings.Internal.Sources.MagicSettingsSourcePackageDefaults.Catalogs*
  implements:
  - ToSic.Cre8magic.Settings.Internal.Sources.IMagicSettingsSource.Catalogs(ToSic.Cre8magic.Themes.MagicThemePackage)
references:
- uid: ToSic.Cre8magic.Settings.Internal.Sources
  commentId: N:ToSic.Cre8magic.Settings.Internal.Sources
  href: ToSic.html
  name: ToSic.Cre8magic.Settings.Internal.Sources
  nameWithType: ToSic.Cre8magic.Settings.Internal.Sources
  fullName: ToSic.Cre8magic.Settings.Internal.Sources
  spec.csharp:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Internal
    name: Internal
    href: ToSic.Cre8magic.Settings.Internal.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Internal.Sources
    name: Sources
    href: ToSic.Cre8magic.Settings.Internal.Sources.html
  spec.vb:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Internal
    name: Internal
    href: ToSic.Cre8magic.Settings.Internal.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Internal.Sources
    name: Sources
    href: ToSic.Cre8magic.Settings.Internal.Sources.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: ToSic.Cre8magic.Settings.Internal.Sources.IMagicSettingsSource
  commentId: T:ToSic.Cre8magic.Settings.Internal.Sources.IMagicSettingsSource
  parent: ToSic.Cre8magic.Settings.Internal.Sources
  href: ToSic.Cre8magic.Settings.Internal.Sources.IMagicSettingsSource.html
  name: IMagicSettingsSource
  nameWithType: IMagicSettingsSource
  fullName: ToSic.Cre8magic.Settings.Internal.Sources.IMagicSettingsSource
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: ToSic.Cre8magic.Settings.Internal.Sources.MagicSettingsSourcePackageDefaults.Priority*
  commentId: Overload:ToSic.Cre8magic.Settings.Internal.Sources.MagicSettingsSourcePackageDefaults.Priority
  href: ToSic.Cre8magic.Settings.Internal.Sources.MagicSettingsSourcePackageDefaults.html#ToSic_Cre8magic_Settings_Internal_Sources_MagicSettingsSourcePackageDefaults_Priority
  name: Priority
  nameWithType: MagicSettingsSourcePackageDefaults.Priority
  fullName: ToSic.Cre8magic.Settings.Internal.Sources.MagicSettingsSourcePackageDefaults.Priority
- uid: ToSic.Cre8magic.Settings.Internal.Sources.IMagicSettingsSource.Priority
  commentId: P:ToSic.Cre8magic.Settings.Internal.Sources.IMagicSettingsSource.Priority
  parent: ToSic.Cre8magic.Settings.Internal.Sources.IMagicSettingsSource
  href: ToSic.Cre8magic.Settings.Internal.Sources.IMagicSettingsSource.html#ToSic_Cre8magic_Settings_Internal_Sources_IMagicSettingsSource_Priority
  name: Priority
  nameWithType: IMagicSettingsSource.Priority
  fullName: ToSic.Cre8magic.Settings.Internal.Sources.IMagicSettingsSource.Priority
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
- uid: ToSic.Cre8magic.Settings.Internal.Sources.MagicSettingsSourcePackageDefaults.Catalogs*
  commentId: Overload:ToSic.Cre8magic.Settings.Internal.Sources.MagicSettingsSourcePackageDefaults.Catalogs
  href: ToSic.Cre8magic.Settings.Internal.Sources.MagicSettingsSourcePackageDefaults.html#ToSic_Cre8magic_Settings_Internal_Sources_MagicSettingsSourcePackageDefaults_Catalogs_ToSic_Cre8magic_Themes_MagicThemePackage_
  name: Catalogs
  nameWithType: MagicSettingsSourcePackageDefaults.Catalogs
  fullName: ToSic.Cre8magic.Settings.Internal.Sources.MagicSettingsSourcePackageDefaults.Catalogs
- uid: ToSic.Cre8magic.Settings.Internal.Sources.IMagicSettingsSource.Catalogs(ToSic.Cre8magic.Themes.MagicThemePackage)
  commentId: M:ToSic.Cre8magic.Settings.Internal.Sources.IMagicSettingsSource.Catalogs(ToSic.Cre8magic.Themes.MagicThemePackage)
  parent: ToSic.Cre8magic.Settings.Internal.Sources.IMagicSettingsSource
  href: ToSic.Cre8magic.Settings.Internal.Sources.IMagicSettingsSource.html#ToSic_Cre8magic_Settings_Internal_Sources_IMagicSettingsSource_Catalogs_ToSic_Cre8magic_Themes_MagicThemePackage_
  name: Catalogs(MagicThemePackage)
  nameWithType: IMagicSettingsSource.Catalogs(MagicThemePackage)
  fullName: ToSic.Cre8magic.Settings.Internal.Sources.IMagicSettingsSource.Catalogs(ToSic.Cre8magic.Themes.MagicThemePackage)
  spec.csharp:
  - uid: ToSic.Cre8magic.Settings.Internal.Sources.IMagicSettingsSource.Catalogs(ToSic.Cre8magic.Themes.MagicThemePackage)
    name: Catalogs
    href: ToSic.Cre8magic.Settings.Internal.Sources.IMagicSettingsSource.html#ToSic_Cre8magic_Settings_Internal_Sources_IMagicSettingsSource_Catalogs_ToSic_Cre8magic_Themes_MagicThemePackage_
  - name: (
  - uid: ToSic.Cre8magic.Themes.MagicThemePackage
    name: MagicThemePackage
    href: ToSic.Cre8magic.Themes.MagicThemePackage.html
  - name: )
  spec.vb:
  - uid: ToSic.Cre8magic.Settings.Internal.Sources.IMagicSettingsSource.Catalogs(ToSic.Cre8magic.Themes.MagicThemePackage)
    name: Catalogs
    href: ToSic.Cre8magic.Settings.Internal.Sources.IMagicSettingsSource.html#ToSic_Cre8magic_Settings_Internal_Sources_IMagicSettingsSource_Catalogs_ToSic_Cre8magic_Themes_MagicThemePackage_
  - name: (
  - uid: ToSic.Cre8magic.Themes.MagicThemePackage
    name: MagicThemePackage
    href: ToSic.Cre8magic.Themes.MagicThemePackage.html
  - name: )
- uid: ToSic.Cre8magic.Themes.MagicThemePackage
  commentId: T:ToSic.Cre8magic.Themes.MagicThemePackage
  parent: ToSic.Cre8magic.Themes
  href: ToSic.Cre8magic.Themes.MagicThemePackage.html
  name: MagicThemePackage
  nameWithType: MagicThemePackage
  fullName: ToSic.Cre8magic.Themes.MagicThemePackage
- uid: System.Collections.Generic.List{ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal{ToSic.Cre8magic.Settings.MagicSettingsCatalog}}
  commentId: T:System.Collections.Generic.List{ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal{ToSic.Cre8magic.Settings.MagicSettingsCatalog}}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.List`1
  href: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal-1.html
  name: List<DataWithJournal<MagicSettingsCatalog>>
  nameWithType: List<DataWithJournal<MagicSettingsCatalog>>
  fullName: System.Collections.Generic.List<ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal<ToSic.Cre8magic.Settings.MagicSettingsCatalog>>
  nameWithType.vb: List(Of DataWithJournal(Of MagicSettingsCatalog))
  fullName.vb: System.Collections.Generic.List(Of ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal(Of ToSic.Cre8magic.Settings.MagicSettingsCatalog))
  name.vb: List(Of DataWithJournal(Of MagicSettingsCatalog))
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
  - name: <
  - uid: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal`1
    name: DataWithJournal
    href: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal-1.html
  - name: <
  - uid: ToSic.Cre8magic.Settings.MagicSettingsCatalog
    name: MagicSettingsCatalog
    href: ToSic.Cre8magic.Settings.MagicSettingsCatalog.html
  - name: '>'
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - uid: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal`1
    name: DataWithJournal
    href: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal-1.html
  - name: (
  - name: Of
  - name: " "
  - uid: ToSic.Cre8magic.Settings.MagicSettingsCatalog
    name: MagicSettingsCatalog
    href: ToSic.Cre8magic.Settings.MagicSettingsCatalog.html
  - name: )
  - name: )
- uid: ToSic.Cre8magic.Themes
  commentId: N:ToSic.Cre8magic.Themes
  href: ToSic.html
  name: ToSic.Cre8magic.Themes
  nameWithType: ToSic.Cre8magic.Themes
  fullName: ToSic.Cre8magic.Themes
  spec.csharp:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Themes
    name: Themes
    href: ToSic.Cre8magic.Themes.html
  spec.vb:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Themes
    name: Themes
    href: ToSic.Cre8magic.Themes.html
- uid: System.Collections.Generic.List`1
  commentId: T:System.Collections.Generic.List`1
  isExternal: true
  name: List<T>
  nameWithType: List<T>
  fullName: System.Collections.Generic.List<T>
  nameWithType.vb: List(Of T)
  fullName.vb: System.Collections.Generic.List(Of T)
  name.vb: List(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
