### YamlMime:ManagedReference
items:
- uid: ToSic.Cre8magic.Settings.Json
  commentId: N:ToSic.Cre8magic.Settings.Json
  id: Json
  parent: ToSic.Cre8magic.Settings
  children:
  - ToSic.Cre8magic.Settings.Json.DesignSettingsJsonConverter`1
  - ToSic.Cre8magic.Settings.Json.JsonConverterBase`1
  - ToSic.Cre8magic.Settings.Json.MagicSettingsJsonService
  - ToSic.Cre8magic.Settings.Json.PairOnOffJsonConverter
  langs:
  - csharp
  - vb
  name: ToSic.Cre8magic.Settings.Json
  nameWithType: ToSic.Cre8magic.Settings.Json
  fullName: ToSic.Cre8magic.Settings.Json
  type: Namespace
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
references:
- uid: ToSic.Cre8magic.Settings.Json.DesignSettingsJsonConverter`1
  commentId: T:ToSic.Cre8magic.Settings.Json.DesignSettingsJsonConverter`1
  parent: ToSic.Cre8magic.Settings.Json
  href: ToSic.Cre8magic.Settings.Json.DesignSettingsJsonConverter-1.html
  name: DesignSettingsJsonConverter<T>
  nameWithType: DesignSettingsJsonConverter<T>
  fullName: ToSic.Cre8magic.Settings.Json.DesignSettingsJsonConverter<T>
  nameWithType.vb: DesignSettingsJsonConverter(Of T)
  fullName.vb: ToSic.Cre8magic.Settings.Json.DesignSettingsJsonConverter(Of T)
  name.vb: DesignSettingsJsonConverter(Of T)
  spec.csharp:
  - uid: ToSic.Cre8magic.Settings.Json.DesignSettingsJsonConverter`1
    name: DesignSettingsJsonConverter
    href: ToSic.Cre8magic.Settings.Json.DesignSettingsJsonConverter-1.html
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: ToSic.Cre8magic.Settings.Json.DesignSettingsJsonConverter`1
    name: DesignSettingsJsonConverter
    href: ToSic.Cre8magic.Settings.Json.DesignSettingsJsonConverter-1.html
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: ToSic.Cre8magic.Settings.Json.JsonConverterBase`1
  commentId: T:ToSic.Cre8magic.Settings.Json.JsonConverterBase`1
  href: ToSic.Cre8magic.Settings.Json.JsonConverterBase-1.html
  name: JsonConverterBase<T>
  nameWithType: JsonConverterBase<T>
  fullName: ToSic.Cre8magic.Settings.Json.JsonConverterBase<T>
  nameWithType.vb: JsonConverterBase(Of T)
  fullName.vb: ToSic.Cre8magic.Settings.Json.JsonConverterBase(Of T)
  name.vb: JsonConverterBase(Of T)
  spec.csharp:
  - uid: ToSic.Cre8magic.Settings.Json.JsonConverterBase`1
    name: JsonConverterBase
    href: ToSic.Cre8magic.Settings.Json.JsonConverterBase-1.html
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: ToSic.Cre8magic.Settings.Json.JsonConverterBase`1
    name: JsonConverterBase
    href: ToSic.Cre8magic.Settings.Json.JsonConverterBase-1.html
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: ToSic.Cre8magic.Settings.Json.MagicSettingsJsonService
  commentId: T:ToSic.Cre8magic.Settings.Json.MagicSettingsJsonService
  parent: ToSic.Cre8magic.Settings.Json
  href: ToSic.Cre8magic.Settings.Json.MagicSettingsJsonService.html
  name: MagicSettingsJsonService
  nameWithType: MagicSettingsJsonService
  fullName: ToSic.Cre8magic.Settings.Json.MagicSettingsJsonService
- uid: ToSic.Cre8magic.Settings.Json.PairOnOffJsonConverter
  commentId: T:ToSic.Cre8magic.Settings.Json.PairOnOffJsonConverter
  parent: ToSic.Cre8magic.Settings.Json
  href: ToSic.Cre8magic.Settings.Json.PairOnOffJsonConverter.html
  name: PairOnOffJsonConverter
  nameWithType: PairOnOffJsonConverter
  fullName: ToSic.Cre8magic.Settings.Json.PairOnOffJsonConverter
- uid: ToSic.Cre8magic.Settings.Json
  commentId: N:ToSic.Cre8magic.Settings.Json
  href: ToSic.html
  name: ToSic.Cre8magic.Settings.Json
  nameWithType: ToSic.Cre8magic.Settings.Json
  fullName: ToSic.Cre8magic.Settings.Json
  spec.csharp:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Json
    name: Json
    href: ToSic.Cre8magic.Settings.Json.html
  spec.vb:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Json
    name: Json
    href: ToSic.Cre8magic.Settings.Json.html
