### YamlMime:ManagedReference
items:
- uid: ToSic.Cre8magic.Settings.Internal.Sources.TestTestTest
  commentId: T:ToSic.Cre8magic.Settings.Internal.Sources.TestTestTest
  id: TestTestTest
  parent: ToSic.Cre8magic.Settings.Internal.Sources
  children: []
  langs:
  - csharp
  - vb
  name: TestTestTest
  nameWithType: TestTestTest
  fullName: ToSic.Cre8magic.Settings.Internal.Sources.TestTestTest
  type: Class
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/Internal/Sources/TestTestTest.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: TestTestTest
    path: ../ToSic.Cre8Magic.Client/Settings/Internal/Sources/TestTestTest.cs
    startLine: 2
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings.Internal.Sources
  syntax:
    content: public class TestTestTest
    content.vb: Public Class TestTestTest
  inheritance:
  - System.Object
references:
- uid: ToSic.Cre8magic.Settings.Internal.Sources
  commentId: N:ToSic.Cre8magic.Settings.Internal.Sources
  href: ToSic.html
  name: ToSic.Cre8magic.Settings.Internal.Sources
  nameWithType: ToSic.Cre8magic.Settings.Internal.Sources
  fullName: ToSic.Cre8magic.Settings.Internal.Sources
  spec.csharp:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Internal
    name: Internal
    href: ToSic.Cre8magic.Settings.Internal.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Internal.Sources
    name: Sources
    href: ToSic.Cre8magic.Settings.Internal.Sources.html
  spec.vb:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Internal
    name: Internal
    href: ToSic.Cre8magic.Settings.Internal.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Internal.Sources
    name: Sources
    href: ToSic.Cre8magic.Settings.Internal.Sources.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
