### YamlMime:ManagedReference
items:
- uid: ToSic.Cre8magic.Settings.MagicSettingsLookup
  commentId: T:ToSic.Cre8magic.Settings.MagicSettingsLookup
  id: MagicSettingsLookup
  parent: ToSic.Cre8magic.Settings
  children:
  - ToSic.Cre8magic.Settings.MagicSettingsLookup.DesignName
  - ToSic.Cre8magic.Settings.MagicSettingsLookup.PartName
  - ToSic.Cre8magic.Settings.MagicSettingsLookup.SettingsName
  langs:
  - csharp
  - vb
  name: MagicSettingsLookup
  nameWithType: MagicSettingsLookup
  fullName: ToSic.Cre8magic.Settings.MagicSettingsLookup
  type: Class
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/MagicSettingsLookup.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: MagicSettingsLookup
    path: ../ToSic.Cre8Magic.Client/Settings/MagicSettingsLookup.cs
    startLine: 2
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings
  syntax:
    content: public record MagicSettingsLookup
    content.vb: Public Class MagicSettingsLookup
  inheritance:
  - System.Object
- uid: ToSic.Cre8magic.Settings.MagicSettingsLookup.PartName
  commentId: P:ToSic.Cre8magic.Settings.MagicSettingsLookup.PartName
  id: PartName
  parent: ToSic.Cre8magic.Settings.MagicSettingsLookup
  langs:
  - csharp
  - vb
  name: PartName
  nameWithType: MagicSettingsLookup.PartName
  fullName: ToSic.Cre8magic.Settings.MagicSettingsLookup.PartName
  type: Property
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/MagicSettingsLookup.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: PartName
    path: ../ToSic.Cre8Magic.Client/Settings/MagicSettingsLookup.cs
    startLine: 4
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings
  syntax:
    content: public string? PartName { get; init; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property PartName As String
  overload: ToSic.Cre8magic.Settings.MagicSettingsLookup.PartName*
- uid: ToSic.Cre8magic.Settings.MagicSettingsLookup.SettingsName
  commentId: P:ToSic.Cre8magic.Settings.MagicSettingsLookup.SettingsName
  id: SettingsName
  parent: ToSic.Cre8magic.Settings.MagicSettingsLookup
  langs:
  - csharp
  - vb
  name: SettingsName
  nameWithType: MagicSettingsLookup.SettingsName
  fullName: ToSic.Cre8magic.Settings.MagicSettingsLookup.SettingsName
  type: Property
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/MagicSettingsLookup.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: SettingsName
    path: ../ToSic.Cre8Magic.Client/Settings/MagicSettingsLookup.cs
    startLine: 6
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings
  syntax:
    content: public string? SettingsName { get; init; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property SettingsName As String
  overload: ToSic.Cre8magic.Settings.MagicSettingsLookup.SettingsName*
- uid: ToSic.Cre8magic.Settings.MagicSettingsLookup.DesignName
  commentId: P:ToSic.Cre8magic.Settings.MagicSettingsLookup.DesignName
  id: DesignName
  parent: ToSic.Cre8magic.Settings.MagicSettingsLookup
  langs:
  - csharp
  - vb
  name: DesignName
  nameWithType: MagicSettingsLookup.DesignName
  fullName: ToSic.Cre8magic.Settings.MagicSettingsLookup.DesignName
  type: Property
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/MagicSettingsLookup.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: DesignName
    path: ../ToSic.Cre8Magic.Client/Settings/MagicSettingsLookup.cs
    startLine: 8
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings
  syntax:
    content: public string? DesignName { get; init; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property DesignName As String
  overload: ToSic.Cre8magic.Settings.MagicSettingsLookup.DesignName*
references:
- uid: ToSic.Cre8magic.Settings
  commentId: N:ToSic.Cre8magic.Settings
  href: ToSic.html
  name: ToSic.Cre8magic.Settings
  nameWithType: ToSic.Cre8magic.Settings
  fullName: ToSic.Cre8magic.Settings
  spec.csharp:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
  spec.vb:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: ToSic.Cre8magic.Settings.MagicSettingsLookup.PartName*
  commentId: Overload:ToSic.Cre8magic.Settings.MagicSettingsLookup.PartName
  href: ToSic.Cre8magic.Settings.MagicSettingsLookup.html#ToSic_Cre8magic_Settings_MagicSettingsLookup_PartName
  name: PartName
  nameWithType: MagicSettingsLookup.PartName
  fullName: ToSic.Cre8magic.Settings.MagicSettingsLookup.PartName
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: ToSic.Cre8magic.Settings.MagicSettingsLookup.SettingsName*
  commentId: Overload:ToSic.Cre8magic.Settings.MagicSettingsLookup.SettingsName
  href: ToSic.Cre8magic.Settings.MagicSettingsLookup.html#ToSic_Cre8magic_Settings_MagicSettingsLookup_SettingsName
  name: SettingsName
  nameWithType: MagicSettingsLookup.SettingsName
  fullName: ToSic.Cre8magic.Settings.MagicSettingsLookup.SettingsName
- uid: ToSic.Cre8magic.Settings.MagicSettingsLookup.DesignName*
  commentId: Overload:ToSic.Cre8magic.Settings.MagicSettingsLookup.DesignName
  href: ToSic.Cre8magic.Settings.MagicSettingsLookup.html#ToSic_Cre8magic_Settings_MagicSettingsLookup_DesignName
  name: DesignName
  nameWithType: MagicSettingsLookup.DesignName
  fullName: ToSic.Cre8magic.Settings.MagicSettingsLookup.DesignName
