### YamlMime:ManagedReference
items:
- uid: ToSic.Cre8magic.Containers.MagicContainerSettingsExtensions
  commentId: T:ToSic.Cre8magic.Containers.MagicContainerSettingsExtensions
  id: MagicContainerSettingsExtensions
  parent: ToSic.Cre8magic.Containers
  children:
  - ToSic.Cre8magic.Containers.MagicContainerSettingsExtensions.With(ToSic.Cre8magic.Containers.MagicContainerSettings,Oqtane.Models.Module)
  - ToSic.Cre8magic.Containers.MagicContainerSettingsExtensions.With(ToSic.Cre8magic.Containers.MagicContainerSettings,Oqtane.UI.PageState,Oqtane.Models.Module)
  langs:
  - csharp
  - vb
  name: MagicContainerSettingsExtensions
  nameWithType: MagicContainerSettingsExtensions
  fullName: ToSic.Cre8magic.Containers.MagicContainerSettingsExtensions
  type: Class
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Containers/MagicContainerSettingsExtensions.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: MagicContainerSettingsExtensions
    path: ../ToSic.Cre8Magic.Client/Containers/MagicContainerSettingsExtensions.cs
    startLine: 5
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Containers
  syntax:
    content: public static class MagicContainerSettingsExtensions
    content.vb: Public Module MagicContainerSettingsExtensions
  inheritance:
  - System.Object
- uid: ToSic.Cre8magic.Containers.MagicContainerSettingsExtensions.With(ToSic.Cre8magic.Containers.MagicContainerSettings,Oqtane.Models.Module)
  commentId: M:ToSic.Cre8magic.Containers.MagicContainerSettingsExtensions.With(ToSic.Cre8magic.Containers.MagicContainerSettings,Oqtane.Models.Module)
  id: With(ToSic.Cre8magic.Containers.MagicContainerSettings,Oqtane.Models.Module)
  isExtensionMethod: true
  parent: ToSic.Cre8magic.Containers.MagicContainerSettingsExtensions
  langs:
  - csharp
  - vb
  name: With(MagicContainerSettings?, Module)
  nameWithType: MagicContainerSettingsExtensions.With(MagicContainerSettings?, Module)
  fullName: ToSic.Cre8magic.Containers.MagicContainerSettingsExtensions.With(ToSic.Cre8magic.Containers.MagicContainerSettings?, Oqtane.Models.Module)
  type: Method
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Containers/MagicContainerSettingsExtensions.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: With
    path: ../ToSic.Cre8Magic.Client/Containers/MagicContainerSettingsExtensions.cs
    startLine: 7
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Containers
  syntax:
    content: public static MagicContainerSettings With(this MagicContainerSettings? settings, Module moduleState)
    parameters:
    - id: settings
      type: ToSic.Cre8magic.Containers.MagicContainerSettings
    - id: moduleState
      type: Oqtane.Models.Module
    return:
      type: ToSic.Cre8magic.Containers.MagicContainerSettings
    content.vb: Public Shared Function [With](settings As MagicContainerSettings, moduleState As [Module]) As MagicContainerSettings
  overload: ToSic.Cre8magic.Containers.MagicContainerSettingsExtensions.With*
  nameWithType.vb: MagicContainerSettingsExtensions.With(MagicContainerSettings, Module)
  fullName.vb: ToSic.Cre8magic.Containers.MagicContainerSettingsExtensions.With(ToSic.Cre8magic.Containers.MagicContainerSettings, Oqtane.Models.Module)
  name.vb: With(MagicContainerSettings, Module)
- uid: ToSic.Cre8magic.Containers.MagicContainerSettingsExtensions.With(ToSic.Cre8magic.Containers.MagicContainerSettings,Oqtane.UI.PageState,Oqtane.Models.Module)
  commentId: M:ToSic.Cre8magic.Containers.MagicContainerSettingsExtensions.With(ToSic.Cre8magic.Containers.MagicContainerSettings,Oqtane.UI.PageState,Oqtane.Models.Module)
  id: With(ToSic.Cre8magic.Containers.MagicContainerSettings,Oqtane.UI.PageState,Oqtane.Models.Module)
  isExtensionMethod: true
  parent: ToSic.Cre8magic.Containers.MagicContainerSettingsExtensions
  langs:
  - csharp
  - vb
  name: With(MagicContainerSettings?, PageState, Module)
  nameWithType: MagicContainerSettingsExtensions.With(MagicContainerSettings?, PageState, Module)
  fullName: ToSic.Cre8magic.Containers.MagicContainerSettingsExtensions.With(ToSic.Cre8magic.Containers.MagicContainerSettings?, Oqtane.UI.PageState, Oqtane.Models.Module)
  type: Method
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Containers/MagicContainerSettingsExtensions.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: With
    path: ../ToSic.Cre8Magic.Client/Containers/MagicContainerSettingsExtensions.cs
    startLine: 13
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Containers
  syntax:
    content: public static MagicContainerSettings With(this MagicContainerSettings? settings, PageState pageState, Module moduleState)
    parameters:
    - id: settings
      type: ToSic.Cre8magic.Containers.MagicContainerSettings
    - id: pageState
      type: Oqtane.UI.PageState
    - id: moduleState
      type: Oqtane.Models.Module
    return:
      type: ToSic.Cre8magic.Containers.MagicContainerSettings
    content.vb: Public Shared Function [With](settings As MagicContainerSettings, pageState As PageState, moduleState As [Module]) As MagicContainerSettings
  overload: ToSic.Cre8magic.Containers.MagicContainerSettingsExtensions.With*
  nameWithType.vb: MagicContainerSettingsExtensions.With(MagicContainerSettings, PageState, Module)
  fullName.vb: ToSic.Cre8magic.Containers.MagicContainerSettingsExtensions.With(ToSic.Cre8magic.Containers.MagicContainerSettings, Oqtane.UI.PageState, Oqtane.Models.Module)
  name.vb: With(MagicContainerSettings, PageState, Module)
references:
- uid: ToSic.Cre8magic.Containers
  commentId: N:ToSic.Cre8magic.Containers
  href: ToSic.html
  name: ToSic.Cre8magic.Containers
  nameWithType: ToSic.Cre8magic.Containers
  fullName: ToSic.Cre8magic.Containers
  spec.csharp:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Containers
    name: Containers
    href: ToSic.Cre8magic.Containers.html
  spec.vb:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Containers
    name: Containers
    href: ToSic.Cre8magic.Containers.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: ToSic.Cre8magic.Containers.MagicContainerSettingsExtensions.With*
  commentId: Overload:ToSic.Cre8magic.Containers.MagicContainerSettingsExtensions.With
  href: ToSic.Cre8magic.Containers.MagicContainerSettingsExtensions.html#ToSic_Cre8magic_Containers_MagicContainerSettingsExtensions_With_ToSic_Cre8magic_Containers_MagicContainerSettings_Oqtane_Models_Module_
  name: With
  nameWithType: MagicContainerSettingsExtensions.With
  fullName: ToSic.Cre8magic.Containers.MagicContainerSettingsExtensions.With
- uid: ToSic.Cre8magic.Containers.MagicContainerSettings
  commentId: T:ToSic.Cre8magic.Containers.MagicContainerSettings
  parent: ToSic.Cre8magic.Containers
  href: ToSic.Cre8magic.Containers.MagicContainerSettings.html
  name: MagicContainerSettings
  nameWithType: MagicContainerSettings
  fullName: ToSic.Cre8magic.Containers.MagicContainerSettings
- uid: Oqtane.Models.Module
  commentId: T:Oqtane.Models.Module
  parent: Oqtane.Models
  name: Module
  nameWithType: Module
  fullName: Oqtane.Models.Module
- uid: Oqtane.Models
  commentId: N:Oqtane.Models
  name: Oqtane.Models
  nameWithType: Oqtane.Models
  fullName: Oqtane.Models
  spec.csharp:
  - uid: Oqtane
    name: Oqtane
  - name: .
  - uid: Oqtane.Models
    name: Models
  spec.vb:
  - uid: Oqtane
    name: Oqtane
  - name: .
  - uid: Oqtane.Models
    name: Models
- uid: Oqtane.UI.PageState
  commentId: T:Oqtane.UI.PageState
  parent: Oqtane.UI
  isExternal: true
  href: https://github.com/sbwalker/oqtane.framework/blob/5e9567158f0f5ea11a746a02b9359695423d7608/Oqtane.Client/UI/PageState.cs
  name: PageState
  nameWithType: PageState
  fullName: Oqtane.UI.PageState
- uid: Oqtane.UI
  commentId: N:Oqtane.UI
  isExternal: true
  name: Oqtane.UI
  nameWithType: Oqtane.UI
  fullName: Oqtane.UI
  spec.csharp:
  - uid: Oqtane
    name: Oqtane
    isExternal: true
  - name: .
  - uid: Oqtane.UI
    name: UI
    isExternal: true
  spec.vb:
  - uid: Oqtane
    name: Oqtane
    isExternal: true
  - name: .
  - uid: Oqtane.UI
    name: UI
    isExternal: true
