### YamlMime:ManagedReference
items:
- uid: ToSic.Cre8magic.Settings.Internal.Sources.IMagicSettingsSource
  commentId: T:ToSic.Cre8magic.Settings.Internal.Sources.IMagicSettingsSource
  id: IMagicSettingsSource
  parent: ToSic.Cre8magic.Settings.Internal.Sources
  children:
  - ToSic.Cre8magic.Settings.Internal.Sources.IMagicSettingsSource.Catalog(ToSic.Cre8magic.Settings.MagicPackageSettings)
  - ToSic.Cre8magic.Settings.Internal.Sources.IMagicSettingsSource.Priority
  langs:
  - csharp
  - vb
  name: IMagicSettingsSource
  nameWithType: IMagicSettingsSource
  fullName: ToSic.Cre8magic.Settings.Internal.Sources.IMagicSettingsSource
  type: Interface
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/Internal/Sources/IMagicSettingsSource.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: IMagicSettingsSource
    path: ../ToSic.Cre8Magic.Client/Settings/Internal/Sources/IMagicSettingsSource.cs
    startLine: 4
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings.Internal.Sources
  syntax:
    content: public interface IMagicSettingsSource
    content.vb: Public Interface IMagicSettingsSource
- uid: ToSic.Cre8magic.Settings.Internal.Sources.IMagicSettingsSource.Catalog(ToSic.Cre8magic.Settings.MagicPackageSettings)
  commentId: M:ToSic.Cre8magic.Settings.Internal.Sources.IMagicSettingsSource.Catalog(ToSic.Cre8magic.Settings.MagicPackageSettings)
  id: Catalog(ToSic.Cre8magic.Settings.MagicPackageSettings)
  parent: ToSic.Cre8magic.Settings.Internal.Sources.IMagicSettingsSource
  langs:
  - csharp
  - vb
  name: Catalog(MagicPackageSettings)
  nameWithType: IMagicSettingsSource.Catalog(MagicPackageSettings)
  fullName: ToSic.Cre8magic.Settings.Internal.Sources.IMagicSettingsSource.Catalog(ToSic.Cre8magic.Settings.MagicPackageSettings)
  type: Method
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/Internal/Sources/IMagicSettingsSource.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: Catalog
    path: ../ToSic.Cre8Magic.Client/Settings/Internal/Sources/IMagicSettingsSource.cs
    startLine: 6
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings.Internal.Sources
  syntax:
    content: List<DataWithJournal<MagicSettingsCatalog>> Catalog(MagicPackageSettings packageSettings)
    parameters:
    - id: packageSettings
      type: ToSic.Cre8magic.Settings.MagicPackageSettings
    return:
      type: System.Collections.Generic.List{ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal{ToSic.Cre8magic.Settings.MagicSettingsCatalog}}
    content.vb: Function Catalog(packageSettings As MagicPackageSettings) As List(Of DataWithJournal(Of MagicSettingsCatalog))
  overload: ToSic.Cre8magic.Settings.Internal.Sources.IMagicSettingsSource.Catalog*
- uid: ToSic.Cre8magic.Settings.Internal.Sources.IMagicSettingsSource.Priority
  commentId: P:ToSic.Cre8magic.Settings.Internal.Sources.IMagicSettingsSource.Priority
  id: Priority
  parent: ToSic.Cre8magic.Settings.Internal.Sources.IMagicSettingsSource
  langs:
  - csharp
  - vb
  name: Priority
  nameWithType: IMagicSettingsSource.Priority
  fullName: ToSic.Cre8magic.Settings.Internal.Sources.IMagicSettingsSource.Priority
  type: Property
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/Internal/Sources/IMagicSettingsSource.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: Priority
    path: ../ToSic.Cre8Magic.Client/Settings/Internal/Sources/IMagicSettingsSource.cs
    startLine: 11
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings.Internal.Sources
  summary: Priority, high number means higher priority
  example: []
  syntax:
    content: int Priority { get; }
    parameters: []
    return:
      type: System.Int32
    content.vb: ReadOnly Property Priority As Integer
  overload: ToSic.Cre8magic.Settings.Internal.Sources.IMagicSettingsSource.Priority*
references:
- uid: ToSic.Cre8magic.Settings.Internal.Sources
  commentId: N:ToSic.Cre8magic.Settings.Internal.Sources
  href: ToSic.html
  name: ToSic.Cre8magic.Settings.Internal.Sources
  nameWithType: ToSic.Cre8magic.Settings.Internal.Sources
  fullName: ToSic.Cre8magic.Settings.Internal.Sources
  spec.csharp:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Internal
    name: Internal
    href: ToSic.Cre8magic.Settings.Internal.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Internal.Sources
    name: Sources
    href: ToSic.Cre8magic.Settings.Internal.Sources.html
  spec.vb:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Internal
    name: Internal
    href: ToSic.Cre8magic.Settings.Internal.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Internal.Sources
    name: Sources
    href: ToSic.Cre8magic.Settings.Internal.Sources.html
- uid: ToSic.Cre8magic.Settings.Internal.Sources.IMagicSettingsSource.Catalog*
  commentId: Overload:ToSic.Cre8magic.Settings.Internal.Sources.IMagicSettingsSource.Catalog
  href: ToSic.Cre8magic.Settings.Internal.Sources.IMagicSettingsSource.html#ToSic_Cre8magic_Settings_Internal_Sources_IMagicSettingsSource_Catalog_ToSic_Cre8magic_Settings_MagicPackageSettings_
  name: Catalog
  nameWithType: IMagicSettingsSource.Catalog
  fullName: ToSic.Cre8magic.Settings.Internal.Sources.IMagicSettingsSource.Catalog
- uid: ToSic.Cre8magic.Settings.MagicPackageSettings
  commentId: T:ToSic.Cre8magic.Settings.MagicPackageSettings
  parent: ToSic.Cre8magic.Settings
  href: ToSic.Cre8magic.Settings.MagicPackageSettings.html
  name: MagicPackageSettings
  nameWithType: MagicPackageSettings
  fullName: ToSic.Cre8magic.Settings.MagicPackageSettings
- uid: System.Collections.Generic.List{ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal{ToSic.Cre8magic.Settings.MagicSettingsCatalog}}
  commentId: T:System.Collections.Generic.List{ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal{ToSic.Cre8magic.Settings.MagicSettingsCatalog}}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.List`1
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  name: List<DataWithJournal<MagicSettingsCatalog>>
  nameWithType: List<DataWithJournal<MagicSettingsCatalog>>
  fullName: System.Collections.Generic.List<ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal<ToSic.Cre8magic.Settings.MagicSettingsCatalog>>
  nameWithType.vb: List(Of DataWithJournal(Of MagicSettingsCatalog))
  fullName.vb: System.Collections.Generic.List(Of ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal(Of ToSic.Cre8magic.Settings.MagicSettingsCatalog))
  name.vb: List(Of DataWithJournal(Of MagicSettingsCatalog))
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: <
  - uid: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal`1
    name: DataWithJournal
    href: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal-1.html
  - name: <
  - uid: ToSic.Cre8magic.Settings.MagicSettingsCatalog
    name: MagicSettingsCatalog
    href: ToSic.Cre8magic.Settings.MagicSettingsCatalog.html
  - name: '>'
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: (
  - name: Of
  - name: " "
  - uid: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal`1
    name: DataWithJournal
    href: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal-1.html
  - name: (
  - name: Of
  - name: " "
  - uid: ToSic.Cre8magic.Settings.MagicSettingsCatalog
    name: MagicSettingsCatalog
    href: ToSic.Cre8magic.Settings.MagicSettingsCatalog.html
  - name: )
  - name: )
- uid: ToSic.Cre8magic.Settings
  commentId: N:ToSic.Cre8magic.Settings
  href: ToSic.html
  name: ToSic.Cre8magic.Settings
  nameWithType: ToSic.Cre8magic.Settings
  fullName: ToSic.Cre8magic.Settings
  spec.csharp:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
  spec.vb:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
- uid: System.Collections.Generic.List`1
  commentId: T:System.Collections.Generic.List`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  name: List<T>
  nameWithType: List<T>
  fullName: System.Collections.Generic.List<T>
  nameWithType.vb: List(Of T)
  fullName.vb: System.Collections.Generic.List(Of T)
  name.vb: List(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
- uid: ToSic.Cre8magic.Settings.Internal.Sources.IMagicSettingsSource.Priority*
  commentId: Overload:ToSic.Cre8magic.Settings.Internal.Sources.IMagicSettingsSource.Priority
  href: ToSic.Cre8magic.Settings.Internal.Sources.IMagicSettingsSource.html#ToSic_Cre8magic_Settings_Internal_Sources_IMagicSettingsSource_Priority
  name: Priority
  nameWithType: IMagicSettingsSource.Priority
  fullName: ToSic.Cre8magic.Settings.Internal.Sources.IMagicSettingsSource.Priority
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
