### YamlMime:ManagedReference
items:
- uid: ToSic.Cre8magic.Themes.Settings
  commentId: N:ToSic.Cre8magic.Themes.Settings
  id: Settings
  parent: ToSic.Cre8magic.Themes
  children:
  - ToSic.Cre8magic.Themes.Settings.MagicThemeBlueprint
  - ToSic.Cre8magic.Themes.Settings.MagicThemePartSettings
  langs:
  - csharp
  - vb
  name: ToSic.Cre8magic.Themes.Settings
  nameWithType: ToSic.Cre8magic.Themes.Settings
  fullName: ToSic.Cre8magic.Themes.Settings
  type: Namespace
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
references:
- uid: ToSic.Cre8magic.Themes.Settings.MagicThemeBlueprint
  commentId: T:ToSic.Cre8magic.Themes.Settings.MagicThemeBlueprint
  href: ToSic.Cre8magic.Themes.Settings.MagicThemeBlueprint.html
  name: MagicThemeBlueprint
  nameWithType: MagicThemeBlueprint
  fullName: ToSic.Cre8magic.Themes.Settings.MagicThemeBlueprint
- uid: ToSic.Cre8magic.Themes.Settings.MagicThemePartSettings
  commentId: T:ToSic.Cre8magic.Themes.Settings.MagicThemePartSettings
  href: ToSic.Cre8magic.Themes.Settings.MagicThemePartSettings.html
  name: MagicThemePartSettings
  nameWithType: MagicThemePartSettings
  fullName: ToSic.Cre8magic.Themes.Settings.MagicThemePartSettings
