### YamlMime:ManagedReference
items:
- uid: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal`1
  commentId: T:ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal`1
  id: DataWithJournal`1
  parent: ToSic.Cre8magic.Settings.Internal.Journal
  children:
  - ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal`1.#ctor(`0,ToSic.Cre8magic.Settings.Internal.Journal.Journal)
  - ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal`1.Data
  - ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal`1.Journal
  langs:
  - csharp
  - vb
  name: DataWithJournal<T>
  nameWithType: DataWithJournal<T>
  fullName: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal<T>
  type: Class
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/Internal/Journal/DataWithJournalOfT.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: DataWithJournal
    path: ../ToSic.Cre8Magic.Client/Settings/Internal/Journal/DataWithJournalOfT.cs
    startLine: 2
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings.Internal.Journal
  syntax:
    content: 'public record DataWithJournal<T> : IEquatable<DataWithJournal<T>>'
    typeParameters:
    - id: T
    content.vb: Public Class DataWithJournal(Of T) Implements IEquatable(Of DataWithJournal(Of T))
  inheritance:
  - System.Object
  implements:
  - System.IEquatable{ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal`1}
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  nameWithType.vb: DataWithJournal(Of T)
  fullName.vb: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal(Of T)
  name.vb: DataWithJournal(Of T)
- uid: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal`1.#ctor(`0,ToSic.Cre8magic.Settings.Internal.Journal.Journal)
  commentId: M:ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal`1.#ctor(`0,ToSic.Cre8magic.Settings.Internal.Journal.Journal)
  id: '#ctor(`0,ToSic.Cre8magic.Settings.Internal.Journal.Journal)'
  parent: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal`1
  langs:
  - csharp
  - vb
  name: DataWithJournal(T, Journal)
  nameWithType: DataWithJournal<T>.DataWithJournal(T, Journal)
  fullName: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal<T>.DataWithJournal(T, ToSic.Cre8magic.Settings.Internal.Journal.Journal)
  type: Constructor
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/Internal/Journal/DataWithJournalOfT.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: .ctor
    path: ../ToSic.Cre8Magic.Client/Settings/Internal/Journal/DataWithJournalOfT.cs
    startLine: 2
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings.Internal.Journal
  syntax:
    content: public DataWithJournal(T Data, Journal Journal)
    parameters:
    - id: Data
      type: '{T}'
    - id: Journal
      type: ToSic.Cre8magic.Settings.Internal.Journal.Journal
    content.vb: Public Sub New(Data As T, Journal As Journal)
  overload: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal`1.#ctor*
  nameWithType.vb: DataWithJournal(Of T).New(T, Journal)
  fullName.vb: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal(Of T).New(T, ToSic.Cre8magic.Settings.Internal.Journal.Journal)
  name.vb: New(T, Journal)
- uid: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal`1.Data
  commentId: P:ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal`1.Data
  id: Data
  parent: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal`1
  langs:
  - csharp
  - vb
  name: Data
  nameWithType: DataWithJournal<T>.Data
  fullName: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal<T>.Data
  type: Property
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/Internal/Journal/DataWithJournalOfT.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: Data
    path: ../ToSic.Cre8Magic.Client/Settings/Internal/Journal/DataWithJournalOfT.cs
    startLine: 2
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings.Internal.Journal
  syntax:
    content: public T Data { get; init; }
    parameters: []
    return:
      type: '{T}'
    content.vb: Public Property Data As T
  overload: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal`1.Data*
  nameWithType.vb: DataWithJournal(Of T).Data
  fullName.vb: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal(Of T).Data
- uid: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal`1.Journal
  commentId: P:ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal`1.Journal
  id: Journal
  parent: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal`1
  langs:
  - csharp
  - vb
  name: Journal
  nameWithType: DataWithJournal<T>.Journal
  fullName: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal<T>.Journal
  type: Property
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/Internal/Journal/DataWithJournalOfT.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: Journal
    path: ../ToSic.Cre8Magic.Client/Settings/Internal/Journal/DataWithJournalOfT.cs
    startLine: 2
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings.Internal.Journal
  syntax:
    content: public Journal Journal { get; init; }
    parameters: []
    return:
      type: ToSic.Cre8magic.Settings.Internal.Journal.Journal
    content.vb: Public Property Journal As Journal
  overload: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal`1.Journal*
  nameWithType.vb: DataWithJournal(Of T).Journal
  fullName.vb: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal(Of T).Journal
references:
- uid: ToSic.Cre8magic.Settings.Internal.Journal
  commentId: N:ToSic.Cre8magic.Settings.Internal.Journal
  href: ToSic.html
  name: ToSic.Cre8magic.Settings.Internal.Journal
  nameWithType: ToSic.Cre8magic.Settings.Internal.Journal
  fullName: ToSic.Cre8magic.Settings.Internal.Journal
  spec.csharp:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Internal
    name: Internal
    href: ToSic.Cre8magic.Settings.Internal.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Internal.Journal
    name: Journal
    href: ToSic.Cre8magic.Settings.Internal.Journal.html
  spec.vb:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Internal
    name: Internal
    href: ToSic.Cre8magic.Settings.Internal.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Internal.Journal
    name: Journal
    href: ToSic.Cre8magic.Settings.Internal.Journal.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.IEquatable{ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal`1}
  commentId: T:System.IEquatable{ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal`1}
  parent: System
  definition: System.IEquatable`1
  href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  name: IEquatable<DataWithJournal<T>>
  nameWithType: IEquatable<DataWithJournal<T>>
  fullName: System.IEquatable<ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal<T>>
  nameWithType.vb: IEquatable(Of DataWithJournal(Of T))
  fullName.vb: System.IEquatable(Of ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal(Of T))
  name.vb: IEquatable(Of DataWithJournal(Of T))
  spec.csharp:
  - uid: System.IEquatable`1
    name: IEquatable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  - name: <
  - uid: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal`1
    name: DataWithJournal
    href: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal-1.html
  - name: <
  - name: T
  - name: '>'
  - name: '>'
  spec.vb:
  - uid: System.IEquatable`1
    name: IEquatable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  - name: (
  - name: Of
  - name: " "
  - uid: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal`1
    name: DataWithJournal
    href: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal-1.html
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
  - name: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.IEquatable`1
  commentId: T:System.IEquatable`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  name: IEquatable<T>
  nameWithType: IEquatable<T>
  fullName: System.IEquatable<T>
  nameWithType.vb: IEquatable(Of T)
  fullName.vb: System.IEquatable(Of T)
  name.vb: IEquatable(Of T)
  spec.csharp:
  - uid: System.IEquatable`1
    name: IEquatable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.IEquatable`1
    name: IEquatable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal`1.#ctor*
  commentId: Overload:ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal`1.#ctor
  href: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal-1.html#ToSic_Cre8magic_Settings_Internal_Journal_DataWithJournal_1__ctor__0_ToSic_Cre8magic_Settings_Internal_Journal_Journal_
  name: DataWithJournal
  nameWithType: DataWithJournal<T>.DataWithJournal
  fullName: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal<T>.DataWithJournal
  nameWithType.vb: DataWithJournal(Of T).New
  fullName.vb: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal(Of T).New
  name.vb: New
- uid: '{T}'
  commentId: '!:T'
  definition: T
  name: T
  nameWithType: T
  fullName: T
- uid: ToSic.Cre8magic.Settings.Internal.Journal.Journal
  commentId: T:ToSic.Cre8magic.Settings.Internal.Journal.Journal
  parent: ToSic.Cre8magic.Settings.Internal.Journal
  href: ToSic.Cre8magic.Settings.Internal.Journal.Journal.html
  name: Journal
  nameWithType: Journal
  fullName: ToSic.Cre8magic.Settings.Internal.Journal.Journal
- uid: T
  name: T
  nameWithType: T
  fullName: T
- uid: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal`1.Data*
  commentId: Overload:ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal`1.Data
  href: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal-1.html#ToSic_Cre8magic_Settings_Internal_Journal_DataWithJournal_1_Data
  name: Data
  nameWithType: DataWithJournal<T>.Data
  fullName: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal<T>.Data
  nameWithType.vb: DataWithJournal(Of T).Data
  fullName.vb: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal(Of T).Data
- uid: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal`1.Journal*
  commentId: Overload:ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal`1.Journal
  href: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal-1.html#ToSic_Cre8magic_Settings_Internal_Journal_DataWithJournal_1_Journal
  name: Journal
  nameWithType: DataWithJournal<T>.Journal
  fullName: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal<T>.Journal
  nameWithType.vb: DataWithJournal(Of T).Journal
  fullName.vb: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal(Of T).Journal
