### YamlMime:ManagedReference
items:
- uid: ToSic.Cre8magic.Settings.IContextWip
  commentId: T:ToSic.Cre8magic.Settings.IContextWip
  id: IContextWip
  parent: ToSic.Cre8magic.Settings
  children:
  - ToSic.Cre8magic.Settings.IContextWip.PageDesigner
  - ToSic.Cre8magic.Settings.IContextWip.PageFactory
  langs:
  - csharp
  - vb
  name: IContextWip
  nameWithType: IContextWip
  fullName: ToSic.Cre8magic.Settings.IContextWip
  type: Interface
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/IContextWip.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: IContextWip
    path: ../ToSic.Cre8Magic.Client/Settings/IContextWip.cs
    startLine: 7
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings
  syntax:
    content: public interface IContextWip
    content.vb: Public Interface IContextWip
- uid: ToSic.Cre8magic.Settings.IContextWip.PageFactory
  commentId: P:ToSic.Cre8magic.Settings.IContextWip.PageFactory
  id: PageFactory
  parent: ToSic.Cre8magic.Settings.IContextWip
  langs:
  - csharp
  - vb
  name: PageFactory
  nameWithType: IContextWip.PageFactory
  fullName: ToSic.Cre8magic.Settings.IContextWip.PageFactory
  type: Property
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/IContextWip.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: PageFactory
    path: ../ToSic.Cre8Magic.Client/Settings/IContextWip.cs
    startLine: 9
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings
  syntax:
    content: MagicPageFactory PageFactory { get; }
    parameters: []
    return:
      type: ToSic.Cre8magic.Pages.Internal.MagicPageFactory
    content.vb: ReadOnly Property PageFactory As MagicPageFactory
  overload: ToSic.Cre8magic.Settings.IContextWip.PageFactory*
- uid: ToSic.Cre8magic.Settings.IContextWip.PageDesigner
  commentId: P:ToSic.Cre8magic.Settings.IContextWip.PageDesigner
  id: PageDesigner
  parent: ToSic.Cre8magic.Settings.IContextWip
  langs:
  - csharp
  - vb
  name: PageDesigner
  nameWithType: IContextWip.PageDesigner
  fullName: ToSic.Cre8magic.Settings.IContextWip.PageDesigner
  type: Property
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/IContextWip.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: PageDesigner
    path: ../ToSic.Cre8Magic.Client/Settings/IContextWip.cs
    startLine: 12
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings
  syntax:
    content: IMagicPageDesigner? PageDesigner { get; }
    parameters: []
    return:
      type: ToSic.Cre8magic.Pages.IMagicPageDesigner
    content.vb: ReadOnly Property PageDesigner As IMagicPageDesigner
  overload: ToSic.Cre8magic.Settings.IContextWip.PageDesigner*
references:
- uid: ToSic.Cre8magic.Settings
  commentId: N:ToSic.Cre8magic.Settings
  href: ToSic.html
  name: ToSic.Cre8magic.Settings
  nameWithType: ToSic.Cre8magic.Settings
  fullName: ToSic.Cre8magic.Settings
  spec.csharp:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
  spec.vb:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
- uid: ToSic.Cre8magic.Settings.IContextWip.PageFactory*
  commentId: Overload:ToSic.Cre8magic.Settings.IContextWip.PageFactory
  href: ToSic.Cre8magic.Settings.IContextWip.html#ToSic_Cre8magic_Settings_IContextWip_PageFactory
  name: PageFactory
  nameWithType: IContextWip.PageFactory
  fullName: ToSic.Cre8magic.Settings.IContextWip.PageFactory
- uid: ToSic.Cre8magic.Pages.Internal.MagicPageFactory
  commentId: T:ToSic.Cre8magic.Pages.Internal.MagicPageFactory
  parent: ToSic.Cre8magic.Pages.Internal
  name: MagicPageFactory
  nameWithType: MagicPageFactory
  fullName: ToSic.Cre8magic.Pages.Internal.MagicPageFactory
- uid: ToSic.Cre8magic.Pages.Internal
  commentId: N:ToSic.Cre8magic.Pages.Internal
  href: ToSic.html
  name: ToSic.Cre8magic.Pages.Internal
  nameWithType: ToSic.Cre8magic.Pages.Internal
  fullName: ToSic.Cre8magic.Pages.Internal
  spec.csharp:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Pages
    name: Pages
    href: ToSic.Cre8magic.Pages.html
  - name: .
  - uid: ToSic.Cre8magic.Pages.Internal
    name: Internal
    href: ToSic.Cre8magic.Pages.Internal.html
  spec.vb:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Pages
    name: Pages
    href: ToSic.Cre8magic.Pages.html
  - name: .
  - uid: ToSic.Cre8magic.Pages.Internal
    name: Internal
    href: ToSic.Cre8magic.Pages.Internal.html
- uid: ToSic.Cre8magic.Settings.IContextWip.PageDesigner*
  commentId: Overload:ToSic.Cre8magic.Settings.IContextWip.PageDesigner
  href: ToSic.Cre8magic.Settings.IContextWip.html#ToSic_Cre8magic_Settings_IContextWip_PageDesigner
  name: PageDesigner
  nameWithType: IContextWip.PageDesigner
  fullName: ToSic.Cre8magic.Settings.IContextWip.PageDesigner
- uid: ToSic.Cre8magic.Pages.IMagicPageDesigner
  commentId: T:ToSic.Cre8magic.Pages.IMagicPageDesigner
  parent: ToSic.Cre8magic.Pages
  href: ToSic.Cre8magic.Pages.IMagicPageDesigner.html
  name: IMagicPageDesigner
  nameWithType: IMagicPageDesigner
  fullName: ToSic.Cre8magic.Pages.IMagicPageDesigner
- uid: ToSic.Cre8magic.Pages
  commentId: N:ToSic.Cre8magic.Pages
  href: ToSic.html
  name: ToSic.Cre8magic.Pages
  nameWithType: ToSic.Cre8magic.Pages
  fullName: ToSic.Cre8magic.Pages
  spec.csharp:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Pages
    name: Pages
    href: ToSic.Cre8magic.Pages.html
  spec.vb:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Pages
    name: Pages
    href: ToSic.Cre8magic.Pages.html
