### YamlMime:ManagedReference
items:
- uid: ToSic.Cre8magic.Menus.Settings.MagicMenuDesigner
  commentId: T:ToSic.Cre8magic.Menus.Settings.MagicMenuDesigner
  id: MagicMenuDesigner
  parent: ToSic.Cre8magic.Menus.Settings
  children:
  - ToSic.Cre8magic.Menus.Settings.MagicMenuDesigner.Classes(System.String,ToSic.Cre8magic.Pages.IMagicPage)
  - ToSic.Cre8magic.Menus.Settings.MagicMenuDesigner.Value(System.String,ToSic.Cre8magic.Pages.IMagicPage)
  langs:
  - csharp
  - vb
  name: MagicMenuDesigner
  nameWithType: MagicMenuDesigner
  fullName: ToSic.Cre8magic.Menus.Settings.MagicMenuDesigner
  type: Class
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Menus/Settings/MagicMenuDesigner.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: MagicMenuDesigner
    path: ../ToSic.Cre8Magic.Client/Menus/Settings/MagicMenuDesigner.cs
    startLine: 12
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Menus.Settings
  summary: Special helper to provide Css classes to menus
  example: []
  syntax:
    content: 'public class MagicMenuDesigner : IMagicPageDesigner'
    content.vb: Public Class MagicMenuDesigner Implements IMagicPageDesigner
  inheritance:
  - System.Object
  implements:
  - ToSic.Cre8magic.Pages.IMagicPageDesigner
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: ToSic.Cre8magic.Menus.Settings.MagicMenuDesigner.Classes(System.String,ToSic.Cre8magic.Pages.IMagicPage)
  commentId: M:ToSic.Cre8magic.Menus.Settings.MagicMenuDesigner.Classes(System.String,ToSic.Cre8magic.Pages.IMagicPage)
  id: Classes(System.String,ToSic.Cre8magic.Pages.IMagicPage)
  parent: ToSic.Cre8magic.Menus.Settings.MagicMenuDesigner
  langs:
  - csharp
  - vb
  name: Classes(string, IMagicPage)
  nameWithType: MagicMenuDesigner.Classes(string, IMagicPage)
  fullName: ToSic.Cre8magic.Menus.Settings.MagicMenuDesigner.Classes(string, ToSic.Cre8magic.Pages.IMagicPage)
  type: Method
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Menus/Settings/MagicMenuDesigner.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: Classes
    path: ../ToSic.Cre8Magic.Client/Menus/Settings/MagicMenuDesigner.cs
    startLine: 30
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Menus.Settings
  example: []
  syntax:
    content: public string Classes(string tag, IMagicPage page)
    parameters:
    - id: tag
      type: System.String
    - id: page
      type: ToSic.Cre8magic.Pages.IMagicPage
    return:
      type: System.String
    content.vb: Public Function Classes(tag As String, page As IMagicPage) As String
  overload: ToSic.Cre8magic.Menus.Settings.MagicMenuDesigner.Classes*
  implements:
  - ToSic.Cre8magic.Pages.IMagicPageDesigner.Classes(System.String,ToSic.Cre8magic.Pages.IMagicPage)
  nameWithType.vb: MagicMenuDesigner.Classes(String, IMagicPage)
  fullName.vb: ToSic.Cre8magic.Menus.Settings.MagicMenuDesigner.Classes(String, ToSic.Cre8magic.Pages.IMagicPage)
  name.vb: Classes(String, IMagicPage)
- uid: ToSic.Cre8magic.Menus.Settings.MagicMenuDesigner.Value(System.String,ToSic.Cre8magic.Pages.IMagicPage)
  commentId: M:ToSic.Cre8magic.Menus.Settings.MagicMenuDesigner.Value(System.String,ToSic.Cre8magic.Pages.IMagicPage)
  id: Value(System.String,ToSic.Cre8magic.Pages.IMagicPage)
  parent: ToSic.Cre8magic.Menus.Settings.MagicMenuDesigner
  langs:
  - csharp
  - vb
  name: Value(string, IMagicPage)
  nameWithType: MagicMenuDesigner.Value(string, IMagicPage)
  fullName: ToSic.Cre8magic.Menus.Settings.MagicMenuDesigner.Value(string, ToSic.Cre8magic.Pages.IMagicPage)
  type: Method
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Menus/Settings/MagicMenuDesigner.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: Value
    path: ../ToSic.Cre8Magic.Client/Menus/Settings/MagicMenuDesigner.cs
    startLine: 40
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Menus.Settings
  example: []
  syntax:
    content: public string Value(string key, IMagicPage page)
    parameters:
    - id: key
      type: System.String
    - id: page
      type: ToSic.Cre8magic.Pages.IMagicPage
    return:
      type: System.String
    content.vb: Public Function Value(key As String, page As IMagicPage) As String
  overload: ToSic.Cre8magic.Menus.Settings.MagicMenuDesigner.Value*
  implements:
  - ToSic.Cre8magic.Pages.IMagicPageDesigner.Value(System.String,ToSic.Cre8magic.Pages.IMagicPage)
  nameWithType.vb: MagicMenuDesigner.Value(String, IMagicPage)
  fullName.vb: ToSic.Cre8magic.Menus.Settings.MagicMenuDesigner.Value(String, ToSic.Cre8magic.Pages.IMagicPage)
  name.vb: Value(String, IMagicPage)
references:
- uid: ToSic.Cre8magic.Menus.Settings
  commentId: N:ToSic.Cre8magic.Menus.Settings
  href: ToSic.html
  name: ToSic.Cre8magic.Menus.Settings
  nameWithType: ToSic.Cre8magic.Menus.Settings
  fullName: ToSic.Cre8magic.Menus.Settings
  spec.csharp:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Menus
    name: Menus
    href: ToSic.Cre8magic.Menus.html
  - name: .
  - uid: ToSic.Cre8magic.Menus.Settings
    name: Settings
    href: ToSic.Cre8magic.Menus.Settings.html
  spec.vb:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Menus
    name: Menus
    href: ToSic.Cre8magic.Menus.html
  - name: .
  - uid: ToSic.Cre8magic.Menus.Settings
    name: Settings
    href: ToSic.Cre8magic.Menus.Settings.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: ToSic.Cre8magic.Pages.IMagicPageDesigner
  commentId: T:ToSic.Cre8magic.Pages.IMagicPageDesigner
  parent: ToSic.Cre8magic.Pages
  href: ToSic.Cre8magic.Pages.IMagicPageDesigner.html
  name: IMagicPageDesigner
  nameWithType: IMagicPageDesigner
  fullName: ToSic.Cre8magic.Pages.IMagicPageDesigner
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: ToSic.Cre8magic.Pages
  commentId: N:ToSic.Cre8magic.Pages
  href: ToSic.html
  name: ToSic.Cre8magic.Pages
  nameWithType: ToSic.Cre8magic.Pages
  fullName: ToSic.Cre8magic.Pages
  spec.csharp:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Pages
    name: Pages
    href: ToSic.Cre8magic.Pages.html
  spec.vb:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Pages
    name: Pages
    href: ToSic.Cre8magic.Pages.html
- uid: ToSic.Cre8magic.Menus.Settings.MagicMenuDesigner.Classes*
  commentId: Overload:ToSic.Cre8magic.Menus.Settings.MagicMenuDesigner.Classes
  href: ToSic.Cre8magic.Menus.Settings.MagicMenuDesigner.html#ToSic_Cre8magic_Menus_Settings_MagicMenuDesigner_Classes_System_String_ToSic_Cre8magic_Pages_IMagicPage_
  name: Classes
  nameWithType: MagicMenuDesigner.Classes
  fullName: ToSic.Cre8magic.Menus.Settings.MagicMenuDesigner.Classes
- uid: ToSic.Cre8magic.Pages.IMagicPageDesigner.Classes(System.String,ToSic.Cre8magic.Pages.IMagicPage)
  commentId: M:ToSic.Cre8magic.Pages.IMagicPageDesigner.Classes(System.String,ToSic.Cre8magic.Pages.IMagicPage)
  parent: ToSic.Cre8magic.Pages.IMagicPageDesigner
  isExternal: true
  href: ToSic.Cre8magic.Pages.IMagicPageDesigner.html#ToSic_Cre8magic_Pages_IMagicPageDesigner_Classes_System_String_ToSic_Cre8magic_Pages_IMagicPage_
  name: Classes(string, IMagicPage)
  nameWithType: IMagicPageDesigner.Classes(string, IMagicPage)
  fullName: ToSic.Cre8magic.Pages.IMagicPageDesigner.Classes(string, ToSic.Cre8magic.Pages.IMagicPage)
  nameWithType.vb: IMagicPageDesigner.Classes(String, IMagicPage)
  fullName.vb: ToSic.Cre8magic.Pages.IMagicPageDesigner.Classes(String, ToSic.Cre8magic.Pages.IMagicPage)
  name.vb: Classes(String, IMagicPage)
  spec.csharp:
  - uid: ToSic.Cre8magic.Pages.IMagicPageDesigner.Classes(System.String,ToSic.Cre8magic.Pages.IMagicPage)
    name: Classes
    href: ToSic.Cre8magic.Pages.IMagicPageDesigner.html#ToSic_Cre8magic_Pages_IMagicPageDesigner_Classes_System_String_ToSic_Cre8magic_Pages_IMagicPage_
  - name: (
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: ','
  - name: " "
  - uid: ToSic.Cre8magic.Pages.IMagicPage
    name: IMagicPage
    href: ToSic.Cre8magic.Pages.IMagicPage.html
  - name: )
  spec.vb:
  - uid: ToSic.Cre8magic.Pages.IMagicPageDesigner.Classes(System.String,ToSic.Cre8magic.Pages.IMagicPage)
    name: Classes
    href: ToSic.Cre8magic.Pages.IMagicPageDesigner.html#ToSic_Cre8magic_Pages_IMagicPageDesigner_Classes_System_String_ToSic_Cre8magic_Pages_IMagicPage_
  - name: (
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: ','
  - name: " "
  - uid: ToSic.Cre8magic.Pages.IMagicPage
    name: IMagicPage
    href: ToSic.Cre8magic.Pages.IMagicPage.html
  - name: )
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: ToSic.Cre8magic.Pages.IMagicPage
  commentId: T:ToSic.Cre8magic.Pages.IMagicPage
  parent: ToSic.Cre8magic.Pages
  href: ToSic.Cre8magic.Pages.IMagicPage.html
  name: IMagicPage
  nameWithType: IMagicPage
  fullName: ToSic.Cre8magic.Pages.IMagicPage
- uid: ToSic.Cre8magic.Menus.Settings.MagicMenuDesigner.Value*
  commentId: Overload:ToSic.Cre8magic.Menus.Settings.MagicMenuDesigner.Value
  href: ToSic.Cre8magic.Menus.Settings.MagicMenuDesigner.html#ToSic_Cre8magic_Menus_Settings_MagicMenuDesigner_Value_System_String_ToSic_Cre8magic_Pages_IMagicPage_
  name: Value
  nameWithType: MagicMenuDesigner.Value
  fullName: ToSic.Cre8magic.Menus.Settings.MagicMenuDesigner.Value
- uid: ToSic.Cre8magic.Pages.IMagicPageDesigner.Value(System.String,ToSic.Cre8magic.Pages.IMagicPage)
  commentId: M:ToSic.Cre8magic.Pages.IMagicPageDesigner.Value(System.String,ToSic.Cre8magic.Pages.IMagicPage)
  parent: ToSic.Cre8magic.Pages.IMagicPageDesigner
  isExternal: true
  href: ToSic.Cre8magic.Pages.IMagicPageDesigner.html#ToSic_Cre8magic_Pages_IMagicPageDesigner_Value_System_String_ToSic_Cre8magic_Pages_IMagicPage_
  name: Value(string, IMagicPage)
  nameWithType: IMagicPageDesigner.Value(string, IMagicPage)
  fullName: ToSic.Cre8magic.Pages.IMagicPageDesigner.Value(string, ToSic.Cre8magic.Pages.IMagicPage)
  nameWithType.vb: IMagicPageDesigner.Value(String, IMagicPage)
  fullName.vb: ToSic.Cre8magic.Pages.IMagicPageDesigner.Value(String, ToSic.Cre8magic.Pages.IMagicPage)
  name.vb: Value(String, IMagicPage)
  spec.csharp:
  - uid: ToSic.Cre8magic.Pages.IMagicPageDesigner.Value(System.String,ToSic.Cre8magic.Pages.IMagicPage)
    name: Value
    href: ToSic.Cre8magic.Pages.IMagicPageDesigner.html#ToSic_Cre8magic_Pages_IMagicPageDesigner_Value_System_String_ToSic_Cre8magic_Pages_IMagicPage_
  - name: (
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: ','
  - name: " "
  - uid: ToSic.Cre8magic.Pages.IMagicPage
    name: IMagicPage
    href: ToSic.Cre8magic.Pages.IMagicPage.html
  - name: )
  spec.vb:
  - uid: ToSic.Cre8magic.Pages.IMagicPageDesigner.Value(System.String,ToSic.Cre8magic.Pages.IMagicPage)
    name: Value
    href: ToSic.Cre8magic.Pages.IMagicPageDesigner.html#ToSic_Cre8magic_Pages_IMagicPageDesigner_Value_System_String_ToSic_Cre8magic_Pages_IMagicPage_
  - name: (
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: ','
  - name: " "
  - uid: ToSic.Cre8magic.Pages.IMagicPage
    name: IMagicPage
    href: ToSic.Cre8magic.Pages.IMagicPage.html
  - name: )
