### YamlMime:ManagedReference
items:
- uid: ToSic.Cre8magic.Settings.Internal.Debug
  commentId: N:ToSic.Cre8magic.Settings.Internal.Debug
  id: Debug
  parent: ToSic.Cre8magic.Settings.Internal
  children:
  - ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettings
  - ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions
  - ToSic.Cre8magic.Settings.Internal.Debug.MagicDebugState
  langs:
  - csharp
  - vb
  name: ToSic.Cre8magic.Settings.Internal.Debug
  nameWithType: ToSic.Cre8magic.Settings.Internal.Debug
  fullName: ToSic.Cre8magic.Settings.Internal.Debug
  type: Namespace
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
references:
- uid: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettings
  commentId: T:ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettings
  parent: ToSic.Cre8magic.Settings.Internal.Debug
  href: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettings.html
  name: IDebugSettings
  nameWithType: IDebugSettings
  fullName: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettings
- uid: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions
  commentId: T:ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions
  parent: ToSic.Cre8magic.Settings.Internal.Debug
  href: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.html
  name: IDebugSettingsExtensions
  nameWithType: IDebugSettingsExtensions
  fullName: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions
- uid: ToSic.Cre8magic.Settings.Internal.Debug.MagicDebugState
  commentId: T:ToSic.Cre8magic.Settings.Internal.Debug.MagicDebugState
  parent: ToSic.Cre8magic.Settings.Internal.Debug
  href: ToSic.Cre8magic.Settings.Internal.Debug.MagicDebugState.html
  name: MagicDebugState
  nameWithType: MagicDebugState
  fullName: ToSic.Cre8magic.Settings.Internal.Debug.MagicDebugState
- uid: ToSic.Cre8magic.Settings.Internal.Debug
  commentId: N:ToSic.Cre8magic.Settings.Internal.Debug
  href: ToSic.html
  name: ToSic.Cre8magic.Settings.Internal.Debug
  nameWithType: ToSic.Cre8magic.Settings.Internal.Debug
  fullName: ToSic.Cre8magic.Settings.Internal.Debug
  spec.csharp:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Internal
    name: Internal
    href: ToSic.Cre8magic.Settings.Internal.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Internal.Debug
    name: Debug
    href: ToSic.Cre8magic.Settings.Internal.Debug.html
  spec.vb:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Internal
    name: Internal
    href: ToSic.Cre8magic.Settings.Internal.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Internal.Debug
    name: Debug
    href: ToSic.Cre8magic.Settings.Internal.Debug.html
