### YamlMime:ManagedReference
items:
- uid: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettings
  commentId: T:ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettings
  id: IDebugSettings
  parent: ToSic.Cre8magic.Settings.Internal.Debug
  children: []
  langs:
  - csharp
  - vb
  name: IDebugSettings
  nameWithType: IDebugSettings
  fullName: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettings
  type: Interface
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/Internal/Debug/IDebugSettings.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: IDebugSettings
    path: ../ToSic.Cre8Magic.Client/Settings/Internal/Debug/IDebugSettings.cs
    startLine: 2
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings.Internal.Debug
  syntax:
    content: public interface IDebugSettings
    content.vb: Public Interface IDebugSettings
  extensionMethods:
  - ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettings.ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.Debug``1
  - ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettings.ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.UseCatalog``1(ToSic.Cre8magic.Settings.MagicSettingsCatalog)
  - ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettings.ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.UseLanguageSettings``1(ToSic.Cre8magic.Languages.MagicLanguageSettings)
references:
- uid: ToSic.Cre8magic.Settings.Internal.Debug
  commentId: N:ToSic.Cre8magic.Settings.Internal.Debug
  href: ToSic.html
  name: ToSic.Cre8magic.Settings.Internal.Debug
  nameWithType: ToSic.Cre8magic.Settings.Internal.Debug
  fullName: ToSic.Cre8magic.Settings.Internal.Debug
  spec.csharp:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Internal
    name: Internal
    href: ToSic.Cre8magic.Settings.Internal.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Internal.Debug
    name: Debug
    href: ToSic.Cre8magic.Settings.Internal.Debug.html
  spec.vb:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Internal
    name: Internal
    href: ToSic.Cre8magic.Settings.Internal.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Internal.Debug
    name: Debug
    href: ToSic.Cre8magic.Settings.Internal.Debug.html
- uid: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettings.ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.Debug``1
  commentId: M:ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.Debug``1(``0)
  parent: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions
  definition: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.Debug``1(``0)
  href: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.html#ToSic_Cre8magic_Settings_Internal_Debug_IDebugSettingsExtensions_Debug__1___0_
  name: Debug<IDebugSettings>(IDebugSettings)
  nameWithType: IDebugSettingsExtensions.Debug<IDebugSettings>(IDebugSettings)
  fullName: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.Debug<ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettings>(ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettings)
  nameWithType.vb: IDebugSettingsExtensions.Debug(Of IDebugSettings)(IDebugSettings)
  fullName.vb: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.Debug(Of ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettings)(ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettings)
  name.vb: Debug(Of IDebugSettings)(IDebugSettings)
  spec.csharp:
  - uid: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.Debug``1(ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettings)
    name: Debug
    href: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.html#ToSic_Cre8magic_Settings_Internal_Debug_IDebugSettingsExtensions_Debug__1___0_
  - name: <
  - uid: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettings
    name: IDebugSettings
    href: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettings.html
  - name: '>'
  - name: (
  - uid: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettings
    name: IDebugSettings
    href: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettings.html
  - name: )
  spec.vb:
  - uid: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.Debug``1(ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettings)
    name: Debug
    href: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.html#ToSic_Cre8magic_Settings_Internal_Debug_IDebugSettingsExtensions_Debug__1___0_
  - name: (
  - name: Of
  - name: " "
  - uid: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettings
    name: IDebugSettings
    href: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettings.html
  - name: )
  - name: (
  - uid: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettings
    name: IDebugSettings
    href: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettings.html
  - name: )
- uid: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettings.ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.UseCatalog``1(ToSic.Cre8magic.Settings.MagicSettingsCatalog)
  commentId: M:ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.UseCatalog``1(``0,ToSic.Cre8magic.Settings.MagicSettingsCatalog)
  parent: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions
  definition: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.UseCatalog``1(``0,ToSic.Cre8magic.Settings.MagicSettingsCatalog)
  href: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.html#ToSic_Cre8magic_Settings_Internal_Debug_IDebugSettingsExtensions_UseCatalog__1___0_ToSic_Cre8magic_Settings_MagicSettingsCatalog_
  name: UseCatalog<IDebugSettings>(IDebugSettings, MagicSettingsCatalog)
  nameWithType: IDebugSettingsExtensions.UseCatalog<IDebugSettings>(IDebugSettings, MagicSettingsCatalog)
  fullName: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.UseCatalog<ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettings>(ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettings, ToSic.Cre8magic.Settings.MagicSettingsCatalog)
  nameWithType.vb: IDebugSettingsExtensions.UseCatalog(Of IDebugSettings)(IDebugSettings, MagicSettingsCatalog)
  fullName.vb: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.UseCatalog(Of ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettings)(ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettings, ToSic.Cre8magic.Settings.MagicSettingsCatalog)
  name.vb: UseCatalog(Of IDebugSettings)(IDebugSettings, MagicSettingsCatalog)
  spec.csharp:
  - uid: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.UseCatalog``1(ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettings,ToSic.Cre8magic.Settings.MagicSettingsCatalog)
    name: UseCatalog
    href: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.html#ToSic_Cre8magic_Settings_Internal_Debug_IDebugSettingsExtensions_UseCatalog__1___0_ToSic_Cre8magic_Settings_MagicSettingsCatalog_
  - name: <
  - uid: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettings
    name: IDebugSettings
    href: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettings.html
  - name: '>'
  - name: (
  - uid: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettings
    name: IDebugSettings
    href: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettings.html
  - name: ','
  - name: " "
  - uid: ToSic.Cre8magic.Settings.MagicSettingsCatalog
    name: MagicSettingsCatalog
    href: ToSic.Cre8magic.Settings.MagicSettingsCatalog.html
  - name: )
  spec.vb:
  - uid: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.UseCatalog``1(ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettings,ToSic.Cre8magic.Settings.MagicSettingsCatalog)
    name: UseCatalog
    href: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.html#ToSic_Cre8magic_Settings_Internal_Debug_IDebugSettingsExtensions_UseCatalog__1___0_ToSic_Cre8magic_Settings_MagicSettingsCatalog_
  - name: (
  - name: Of
  - name: " "
  - uid: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettings
    name: IDebugSettings
    href: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettings.html
  - name: )
  - name: (
  - uid: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettings
    name: IDebugSettings
    href: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettings.html
  - name: ','
  - name: " "
  - uid: ToSic.Cre8magic.Settings.MagicSettingsCatalog
    name: MagicSettingsCatalog
    href: ToSic.Cre8magic.Settings.MagicSettingsCatalog.html
  - name: )
- uid: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettings.ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.UseLanguageSettings``1(ToSic.Cre8magic.Languages.MagicLanguageSettings)
  commentId: M:ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.UseLanguageSettings``1(``0,ToSic.Cre8magic.Languages.MagicLanguageSettings)
  parent: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions
  definition: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.UseLanguageSettings``1(``0,ToSic.Cre8magic.Languages.MagicLanguageSettings)
  href: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.html#ToSic_Cre8magic_Settings_Internal_Debug_IDebugSettingsExtensions_UseLanguageSettings__1___0_ToSic_Cre8magic_Languages_MagicLanguageSettings_
  name: UseLanguageSettings<IDebugSettings>(IDebugSettings, MagicLanguageSettings)
  nameWithType: IDebugSettingsExtensions.UseLanguageSettings<IDebugSettings>(IDebugSettings, MagicLanguageSettings)
  fullName: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.UseLanguageSettings<ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettings>(ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettings, ToSic.Cre8magic.Languages.MagicLanguageSettings)
  nameWithType.vb: IDebugSettingsExtensions.UseLanguageSettings(Of IDebugSettings)(IDebugSettings, MagicLanguageSettings)
  fullName.vb: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.UseLanguageSettings(Of ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettings)(ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettings, ToSic.Cre8magic.Languages.MagicLanguageSettings)
  name.vb: UseLanguageSettings(Of IDebugSettings)(IDebugSettings, MagicLanguageSettings)
  spec.csharp:
  - uid: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.UseLanguageSettings``1(ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettings,ToSic.Cre8magic.Languages.MagicLanguageSettings)
    name: UseLanguageSettings
    href: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.html#ToSic_Cre8magic_Settings_Internal_Debug_IDebugSettingsExtensions_UseLanguageSettings__1___0_ToSic_Cre8magic_Languages_MagicLanguageSettings_
  - name: <
  - uid: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettings
    name: IDebugSettings
    href: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettings.html
  - name: '>'
  - name: (
  - uid: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettings
    name: IDebugSettings
    href: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettings.html
  - name: ','
  - name: " "
  - uid: ToSic.Cre8magic.Languages.MagicLanguageSettings
    name: MagicLanguageSettings
    href: ToSic.Cre8magic.Languages.MagicLanguageSettings.html
  - name: )
  spec.vb:
  - uid: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.UseLanguageSettings``1(ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettings,ToSic.Cre8magic.Languages.MagicLanguageSettings)
    name: UseLanguageSettings
    href: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.html#ToSic_Cre8magic_Settings_Internal_Debug_IDebugSettingsExtensions_UseLanguageSettings__1___0_ToSic_Cre8magic_Languages_MagicLanguageSettings_
  - name: (
  - name: Of
  - name: " "
  - uid: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettings
    name: IDebugSettings
    href: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettings.html
  - name: )
  - name: (
  - uid: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettings
    name: IDebugSettings
    href: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettings.html
  - name: ','
  - name: " "
  - uid: ToSic.Cre8magic.Languages.MagicLanguageSettings
    name: MagicLanguageSettings
    href: ToSic.Cre8magic.Languages.MagicLanguageSettings.html
  - name: )
- uid: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.Debug``1(``0)
  commentId: M:ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.Debug``1(``0)
  href: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.html#ToSic_Cre8magic_Settings_Internal_Debug_IDebugSettingsExtensions_Debug__1___0_
  name: Debug<T>(T)
  nameWithType: IDebugSettingsExtensions.Debug<T>(T)
  fullName: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.Debug<T>(T)
  nameWithType.vb: IDebugSettingsExtensions.Debug(Of T)(T)
  fullName.vb: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.Debug(Of T)(T)
  name.vb: Debug(Of T)(T)
  spec.csharp:
  - uid: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.Debug``1(``0)
    name: Debug
    href: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.html#ToSic_Cre8magic_Settings_Internal_Debug_IDebugSettingsExtensions_Debug__1___0_
  - name: <
  - name: T
  - name: '>'
  - name: (
  - name: T
  - name: )
  spec.vb:
  - uid: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.Debug``1(``0)
    name: Debug
    href: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.html#ToSic_Cre8magic_Settings_Internal_Debug_IDebugSettingsExtensions_Debug__1___0_
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
  - name: (
  - name: T
  - name: )
- uid: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions
  commentId: T:ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions
  parent: ToSic.Cre8magic.Settings.Internal.Debug
  href: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.html
  name: IDebugSettingsExtensions
  nameWithType: IDebugSettingsExtensions
  fullName: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions
- uid: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.UseCatalog``1(``0,ToSic.Cre8magic.Settings.MagicSettingsCatalog)
  commentId: M:ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.UseCatalog``1(``0,ToSic.Cre8magic.Settings.MagicSettingsCatalog)
  href: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.html#ToSic_Cre8magic_Settings_Internal_Debug_IDebugSettingsExtensions_UseCatalog__1___0_ToSic_Cre8magic_Settings_MagicSettingsCatalog_
  name: UseCatalog<T>(T, MagicSettingsCatalog)
  nameWithType: IDebugSettingsExtensions.UseCatalog<T>(T, MagicSettingsCatalog)
  fullName: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.UseCatalog<T>(T, ToSic.Cre8magic.Settings.MagicSettingsCatalog)
  nameWithType.vb: IDebugSettingsExtensions.UseCatalog(Of T)(T, MagicSettingsCatalog)
  fullName.vb: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.UseCatalog(Of T)(T, ToSic.Cre8magic.Settings.MagicSettingsCatalog)
  name.vb: UseCatalog(Of T)(T, MagicSettingsCatalog)
  spec.csharp:
  - uid: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.UseCatalog``1(``0,ToSic.Cre8magic.Settings.MagicSettingsCatalog)
    name: UseCatalog
    href: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.html#ToSic_Cre8magic_Settings_Internal_Debug_IDebugSettingsExtensions_UseCatalog__1___0_ToSic_Cre8magic_Settings_MagicSettingsCatalog_
  - name: <
  - name: T
  - name: '>'
  - name: (
  - name: T
  - name: ','
  - name: " "
  - uid: ToSic.Cre8magic.Settings.MagicSettingsCatalog
    name: MagicSettingsCatalog
    href: ToSic.Cre8magic.Settings.MagicSettingsCatalog.html
  - name: )
  spec.vb:
  - uid: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.UseCatalog``1(``0,ToSic.Cre8magic.Settings.MagicSettingsCatalog)
    name: UseCatalog
    href: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.html#ToSic_Cre8magic_Settings_Internal_Debug_IDebugSettingsExtensions_UseCatalog__1___0_ToSic_Cre8magic_Settings_MagicSettingsCatalog_
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
  - name: (
  - name: T
  - name: ','
  - name: " "
  - uid: ToSic.Cre8magic.Settings.MagicSettingsCatalog
    name: MagicSettingsCatalog
    href: ToSic.Cre8magic.Settings.MagicSettingsCatalog.html
  - name: )
- uid: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.UseLanguageSettings``1(``0,ToSic.Cre8magic.Languages.MagicLanguageSettings)
  commentId: M:ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.UseLanguageSettings``1(``0,ToSic.Cre8magic.Languages.MagicLanguageSettings)
  href: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.html#ToSic_Cre8magic_Settings_Internal_Debug_IDebugSettingsExtensions_UseLanguageSettings__1___0_ToSic_Cre8magic_Languages_MagicLanguageSettings_
  name: UseLanguageSettings<T>(T, MagicLanguageSettings)
  nameWithType: IDebugSettingsExtensions.UseLanguageSettings<T>(T, MagicLanguageSettings)
  fullName: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.UseLanguageSettings<T>(T, ToSic.Cre8magic.Languages.MagicLanguageSettings)
  nameWithType.vb: IDebugSettingsExtensions.UseLanguageSettings(Of T)(T, MagicLanguageSettings)
  fullName.vb: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.UseLanguageSettings(Of T)(T, ToSic.Cre8magic.Languages.MagicLanguageSettings)
  name.vb: UseLanguageSettings(Of T)(T, MagicLanguageSettings)
  spec.csharp:
  - uid: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.UseLanguageSettings``1(``0,ToSic.Cre8magic.Languages.MagicLanguageSettings)
    name: UseLanguageSettings
    href: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.html#ToSic_Cre8magic_Settings_Internal_Debug_IDebugSettingsExtensions_UseLanguageSettings__1___0_ToSic_Cre8magic_Languages_MagicLanguageSettings_
  - name: <
  - name: T
  - name: '>'
  - name: (
  - name: T
  - name: ','
  - name: " "
  - uid: ToSic.Cre8magic.Languages.MagicLanguageSettings
    name: MagicLanguageSettings
    href: ToSic.Cre8magic.Languages.MagicLanguageSettings.html
  - name: )
  spec.vb:
  - uid: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.UseLanguageSettings``1(``0,ToSic.Cre8magic.Languages.MagicLanguageSettings)
    name: UseLanguageSettings
    href: ToSic.Cre8magic.Settings.Internal.Debug.IDebugSettingsExtensions.html#ToSic_Cre8magic_Settings_Internal_Debug_IDebugSettingsExtensions_UseLanguageSettings__1___0_ToSic_Cre8magic_Languages_MagicLanguageSettings_
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
  - name: (
  - name: T
  - name: ','
  - name: " "
  - uid: ToSic.Cre8magic.Languages.MagicLanguageSettings
    name: MagicLanguageSettings
    href: ToSic.Cre8magic.Languages.MagicLanguageSettings.html
  - name: )
