### YamlMime:ManagedReference
items:
- uid: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal`1
  commentId: T:ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal`1
  id: DataWithJournal`1
  parent: ToSic.Cre8magic.Settings.Internal.Journal
  children:
  - ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal`1.#ctor(`0,ToSic.Cre8magic.Settings.Internal.Journal.Journal)
  - ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal`1.Data
  - ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal`1.Journal
  langs:
  - csharp
  - vb
  name: DataWithJournal<T>
  nameWithType: DataWithJournal<T>
  fullName: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal<T>
  type: Class
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/Internal/Journal/DataWithJournalOfT.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: DataWithJournal
    path: ../ToSic.Cre8Magic.Client/Settings/Internal/Journal/DataWithJournalOfT.cs
    startLine: 2
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings.Internal.Journal
  syntax:
    content: public record DataWithJournal<T>
    typeParameters:
    - id: T
    content.vb: Public Class DataWithJournal(Of T)
  inheritance:
  - System.Object
  nameWithType.vb: DataWithJournal(Of T)
  fullName.vb: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal(Of T)
  name.vb: DataWithJournal(Of T)
- uid: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal`1.#ctor(`0,ToSic.Cre8magic.Settings.Internal.Journal.Journal)
  commentId: M:ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal`1.#ctor(`0,ToSic.Cre8magic.Settings.Internal.Journal.Journal)
  id: '#ctor(`0,ToSic.Cre8magic.Settings.Internal.Journal.Journal)'
  parent: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal`1
  langs:
  - csharp
  - vb
  name: DataWithJournal(T, Journal)
  nameWithType: DataWithJournal<T>.DataWithJournal(T, Journal)
  fullName: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal<T>.DataWithJournal(T, ToSic.Cre8magic.Settings.Internal.Journal.Journal)
  type: Constructor
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/Internal/Journal/DataWithJournalOfT.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: .ctor
    path: ../ToSic.Cre8Magic.Client/Settings/Internal/Journal/DataWithJournalOfT.cs
    startLine: 2
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings.Internal.Journal
  syntax:
    content: public DataWithJournal(T Data, Journal Journal)
    parameters:
    - id: Data
      type: '{T}'
    - id: Journal
      type: ToSic.Cre8magic.Settings.Internal.Journal.Journal
    content.vb: Public Sub New(Data As T, Journal As Journal)
  overload: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal`1.#ctor*
  nameWithType.vb: DataWithJournal(Of T).New(T, Journal)
  fullName.vb: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal(Of T).New(T, ToSic.Cre8magic.Settings.Internal.Journal.Journal)
  name.vb: New(T, Journal)
- uid: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal`1.Data
  commentId: P:ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal`1.Data
  id: Data
  parent: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal`1
  langs:
  - csharp
  - vb
  name: Data
  nameWithType: DataWithJournal<T>.Data
  fullName: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal<T>.Data
  type: Property
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/Internal/Journal/DataWithJournalOfT.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: Data
    path: ../ToSic.Cre8Magic.Client/Settings/Internal/Journal/DataWithJournalOfT.cs
    startLine: 2
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings.Internal.Journal
  syntax:
    content: public T Data { get; init; }
    parameters: []
    return:
      type: '{T}'
    content.vb: Public Property Data As T
  overload: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal`1.Data*
  nameWithType.vb: DataWithJournal(Of T).Data
  fullName.vb: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal(Of T).Data
- uid: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal`1.Journal
  commentId: P:ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal`1.Journal
  id: Journal
  parent: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal`1
  langs:
  - csharp
  - vb
  name: Journal
  nameWithType: DataWithJournal<T>.Journal
  fullName: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal<T>.Journal
  type: Property
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/Internal/Journal/DataWithJournalOfT.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: Journal
    path: ../ToSic.Cre8Magic.Client/Settings/Internal/Journal/DataWithJournalOfT.cs
    startLine: 2
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings.Internal.Journal
  syntax:
    content: public Journal Journal { get; init; }
    parameters: []
    return:
      type: ToSic.Cre8magic.Settings.Internal.Journal.Journal
    content.vb: Public Property Journal As Journal
  overload: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal`1.Journal*
  nameWithType.vb: DataWithJournal(Of T).Journal
  fullName.vb: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal(Of T).Journal
references:
- uid: ToSic.Cre8magic.Settings.Internal.Journal
  commentId: N:ToSic.Cre8magic.Settings.Internal.Journal
  href: ToSic.html
  name: ToSic.Cre8magic.Settings.Internal.Journal
  nameWithType: ToSic.Cre8magic.Settings.Internal.Journal
  fullName: ToSic.Cre8magic.Settings.Internal.Journal
  spec.csharp:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Internal
    name: Internal
    href: ToSic.Cre8magic.Settings.Internal.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Internal.Journal
    name: Journal
    href: ToSic.Cre8magic.Settings.Internal.Journal.html
  spec.vb:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Internal
    name: Internal
    href: ToSic.Cre8magic.Settings.Internal.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Internal.Journal
    name: Journal
    href: ToSic.Cre8magic.Settings.Internal.Journal.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal`1.#ctor*
  commentId: Overload:ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal`1.#ctor
  href: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal-1.html#ToSic_Cre8magic_Settings_Internal_Journal_DataWithJournal_1__ctor__0_ToSic_Cre8magic_Settings_Internal_Journal_Journal_
  name: DataWithJournal
  nameWithType: DataWithJournal<T>.DataWithJournal
  fullName: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal<T>.DataWithJournal
  nameWithType.vb: DataWithJournal(Of T).New
  fullName.vb: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal(Of T).New
  name.vb: New
- uid: '{T}'
  commentId: '!:T'
  definition: T
  name: T
  nameWithType: T
  fullName: T
- uid: ToSic.Cre8magic.Settings.Internal.Journal.Journal
  commentId: T:ToSic.Cre8magic.Settings.Internal.Journal.Journal
  parent: ToSic.Cre8magic.Settings.Internal.Journal
  href: ToSic.Cre8magic.Settings.Internal.Journal.Journal.html
  name: Journal
  nameWithType: Journal
  fullName: ToSic.Cre8magic.Settings.Internal.Journal.Journal
- uid: T
  name: T
  nameWithType: T
  fullName: T
- uid: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal`1.Data*
  commentId: Overload:ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal`1.Data
  href: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal-1.html#ToSic_Cre8magic_Settings_Internal_Journal_DataWithJournal_1_Data
  name: Data
  nameWithType: DataWithJournal<T>.Data
  fullName: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal<T>.Data
  nameWithType.vb: DataWithJournal(Of T).Data
  fullName.vb: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal(Of T).Data
- uid: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal`1.Journal*
  commentId: Overload:ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal`1.Journal
  href: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal-1.html#ToSic_Cre8magic_Settings_Internal_Journal_DataWithJournal_1_Journal
  name: Journal
  nameWithType: DataWithJournal<T>.Journal
  fullName: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal<T>.Journal
  nameWithType.vb: DataWithJournal(Of T).Journal
  fullName.vb: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal(Of T).Journal
