### YamlMime:ManagedReference
items:
- uid: ToSic.Cre8magic.Settings.Providers
  commentId: N:ToSic.Cre8magic.Settings.Providers
  id: Providers
  parent: ToSic.Cre8magic.Settings
  children:
  - ToSic.Cre8magic.Settings.Providers.IMagicProviderSection`1
  - ToSic.Cre8magic.Settings.Providers.IMagicSettingsProvider
  langs:
  - csharp
  - vb
  name: ToSic.Cre8magic.Settings.Providers
  nameWithType: ToSic.Cre8magic.Settings.Providers
  fullName: ToSic.Cre8magic.Settings.Providers
  type: Namespace
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
references:
- uid: ToSic.Cre8magic.Settings.Providers.IMagicProviderSection`1
  commentId: T:ToSic.Cre8magic.Settings.Providers.IMagicProviderSection`1
  href: ToSic.Cre8magic.Settings.Providers.IMagicProviderSection-1.html
  name: IMagicProviderSection<TSettings>
  nameWithType: IMagicProviderSection<TSettings>
  fullName: ToSic.Cre8magic.Settings.Providers.IMagicProviderSection<TSettings>
  nameWithType.vb: IMagicProviderSection(Of TSettings)
  fullName.vb: ToSic.Cre8magic.Settings.Providers.IMagicProviderSection(Of TSettings)
  name.vb: IMagicProviderSection(Of TSettings)
  spec.csharp:
  - uid: ToSic.Cre8magic.Settings.Providers.IMagicProviderSection`1
    name: IMagicProviderSection
    href: ToSic.Cre8magic.Settings.Providers.IMagicProviderSection-1.html
  - name: <
  - name: TSettings
  - name: '>'
  spec.vb:
  - uid: ToSic.Cre8magic.Settings.Providers.IMagicProviderSection`1
    name: IMagicProviderSection
    href: ToSic.Cre8magic.Settings.Providers.IMagicProviderSection-1.html
  - name: (
  - name: Of
  - name: " "
  - name: TSettings
  - name: )
- uid: ToSic.Cre8magic.Settings.Providers.IMagicSettingsProvider
  commentId: T:ToSic.Cre8magic.Settings.Providers.IMagicSettingsProvider
  parent: ToSic.Cre8magic.Settings.Providers
  href: ToSic.Cre8magic.Settings.Providers.IMagicSettingsProvider.html
  name: IMagicSettingsProvider
  nameWithType: IMagicSettingsProvider
  fullName: ToSic.Cre8magic.Settings.Providers.IMagicSettingsProvider
- uid: ToSic.Cre8magic.Settings.Providers
  commentId: N:ToSic.Cre8magic.Settings.Providers
  href: ToSic.html
  name: ToSic.Cre8magic.Settings.Providers
  nameWithType: ToSic.Cre8magic.Settings.Providers
  fullName: ToSic.Cre8magic.Settings.Providers
  spec.csharp:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Providers
    name: Providers
    href: ToSic.Cre8magic.Settings.Providers.html
  spec.vb:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Providers
    name: Providers
    href: ToSic.Cre8magic.Settings.Providers.html
