### YamlMime:ManagedReference
items:
- uid: ToSic.Cre8magic.Settings.Internal.ICanClone`1
  commentId: T:ToSic.Cre8magic.Settings.Internal.ICanClone`1
  id: ICanClone`1
  parent: ToSic.Cre8magic.Settings.Internal
  children:
  - ToSic.Cre8magic.Settings.Internal.ICanClone`1.CloneUnder(`0,System.Boolean)
  langs:
  - csharp
  - vb
  name: ICanClone<T>
  nameWithType: ICanClone<T>
  fullName: ToSic.Cre8magic.Settings.Internal.ICanClone<T>
  type: Interface
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/Internal/ICanClone.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: ICanClone
    path: ../ToSic.Cre8Magic.Client/Settings/Internal/ICanClone.cs
    startLine: 2
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings.Internal
  syntax:
    content: >-
      [PrivateApi]

      public interface ICanClone<T>
    typeParameters:
    - id: T
    content.vb: >-
      <PrivateApi>

      Public Interface ICanClone(Of T)
  attributes:
  - type: Oqtane.Documentation.PrivateApi
    ctor: Oqtane.Documentation.PrivateApi.#ctor
    arguments: []
  nameWithType.vb: ICanClone(Of T)
  fullName.vb: ToSic.Cre8magic.Settings.Internal.ICanClone(Of T)
  name.vb: ICanClone(Of T)
- uid: ToSic.Cre8magic.Settings.Internal.ICanClone`1.CloneUnder(`0,System.Boolean)
  commentId: M:ToSic.Cre8magic.Settings.Internal.ICanClone`1.CloneUnder(`0,System.Boolean)
  id: CloneUnder(`0,System.Boolean)
  parent: ToSic.Cre8magic.Settings.Internal.ICanClone`1
  langs:
  - csharp
  - vb
  name: CloneUnder(T?, bool)
  nameWithType: ICanClone<T>.CloneUnder(T?, bool)
  fullName: ToSic.Cre8magic.Settings.Internal.ICanClone<T>.CloneUnder(T?, bool)
  type: Method
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/Internal/ICanClone.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: CloneUnder
    path: ../ToSic.Cre8Magic.Client/Settings/Internal/ICanClone.cs
    startLine: 11
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings.Internal
  summary: Clone the current object under another one which is more important than this one.
  example: []
  syntax:
    content: T CloneUnder(T? priority, bool forceCopy = false)
    parameters:
    - id: priority
      type: '{T}'
      description: ''
    - id: forceCopy
      type: System.Boolean
      description: ''
    return:
      type: '{T}'
      description: ''
    content.vb: Function CloneUnder(priority As T, forceCopy As Boolean = False) As T
  overload: ToSic.Cre8magic.Settings.Internal.ICanClone`1.CloneUnder*
  nameWithType.vb: ICanClone(Of T).CloneUnder(T, Boolean)
  fullName.vb: ToSic.Cre8magic.Settings.Internal.ICanClone(Of T).CloneUnder(T, Boolean)
  name.vb: CloneUnder(T, Boolean)
references:
- uid: ToSic.Cre8magic.Settings.Internal
  commentId: N:ToSic.Cre8magic.Settings.Internal
  href: ToSic.html
  name: ToSic.Cre8magic.Settings.Internal
  nameWithType: ToSic.Cre8magic.Settings.Internal
  fullName: ToSic.Cre8magic.Settings.Internal
  spec.csharp:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Internal
    name: Internal
    href: ToSic.Cre8magic.Settings.Internal.html
  spec.vb:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Internal
    name: Internal
    href: ToSic.Cre8magic.Settings.Internal.html
- uid: ToSic.Cre8magic.Settings.Internal.ICanClone`1.CloneUnder*
  commentId: Overload:ToSic.Cre8magic.Settings.Internal.ICanClone`1.CloneUnder
  href: ToSic.Cre8magic.Settings.Internal.ICanClone-1.html#ToSic_Cre8magic_Settings_Internal_ICanClone_1_CloneUnder__0_System_Boolean_
  name: CloneUnder
  nameWithType: ICanClone<T>.CloneUnder
  fullName: ToSic.Cre8magic.Settings.Internal.ICanClone<T>.CloneUnder
  nameWithType.vb: ICanClone(Of T).CloneUnder
  fullName.vb: ToSic.Cre8magic.Settings.Internal.ICanClone(Of T).CloneUnder
- uid: '{T}'
  commentId: '!:T'
  definition: T
  name: T
  nameWithType: T
  fullName: T
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: T
  name: T
  nameWithType: T
  fullName: T
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
