### YamlMime:ManagedReference
items:
- uid: ToSic.Cre8magic.Settings.Internal.Logging.SettingsException
  commentId: T:ToSic.Cre8magic.Settings.Internal.Logging.SettingsException
  id: SettingsException
  parent: ToSic.Cre8magic.Settings.Internal.Logging
  children:
  - ToSic.Cre8magic.Settings.Internal.Logging.SettingsException.#ctor(System.String)
  langs:
  - csharp
  - vb
  name: SettingsException
  nameWithType: SettingsException
  fullName: ToSic.Cre8magic.Settings.Internal.Logging.SettingsException
  type: Class
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/Internal/Logging/SettingsException.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: SettingsException
    path: ../ToSic.Cre8Magic.Client/Settings/Internal/Logging/SettingsException.cs
    startLine: 2
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings.Internal.Logging
  syntax:
    content: 'public class SettingsException : Exception'
    content.vb: Public Class SettingsException Inherits Exception
  inheritance:
  - System.Object
  - System.Exception
- uid: ToSic.Cre8magic.Settings.Internal.Logging.SettingsException.#ctor(System.String)
  commentId: M:ToSic.Cre8magic.Settings.Internal.Logging.SettingsException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: ToSic.Cre8magic.Settings.Internal.Logging.SettingsException
  langs:
  - csharp
  - vb
  name: SettingsException(string)
  nameWithType: SettingsException.SettingsException(string)
  fullName: ToSic.Cre8magic.Settings.Internal.Logging.SettingsException.SettingsException(string)
  type: Constructor
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/Internal/Logging/SettingsException.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: .ctor
    path: ../ToSic.Cre8Magic.Client/Settings/Internal/Logging/SettingsException.cs
    startLine: 2
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings.Internal.Logging
  syntax:
    content: public SettingsException(string message)
    parameters:
    - id: message
      type: System.String
    content.vb: Public Sub New(message As String)
  overload: ToSic.Cre8magic.Settings.Internal.Logging.SettingsException.#ctor*
  nameWithType.vb: SettingsException.New(String)
  fullName.vb: ToSic.Cre8magic.Settings.Internal.Logging.SettingsException.New(String)
  name.vb: New(String)
references:
- uid: ToSic.Cre8magic.Settings.Internal.Logging
  commentId: N:ToSic.Cre8magic.Settings.Internal.Logging
  href: ToSic.html
  name: ToSic.Cre8magic.Settings.Internal.Logging
  nameWithType: ToSic.Cre8magic.Settings.Internal.Logging
  fullName: ToSic.Cre8magic.Settings.Internal.Logging
  spec.csharp:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Internal
    name: Internal
    href: ToSic.Cre8magic.Settings.Internal.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Internal.Logging
    name: Logging
    href: ToSic.Cre8magic.Settings.Internal.Logging.html
  spec.vb:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Internal
    name: Internal
    href: ToSic.Cre8magic.Settings.Internal.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Internal.Logging
    name: Logging
    href: ToSic.Cre8magic.Settings.Internal.Logging.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Exception
  commentId: T:System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: ToSic.Cre8magic.Settings.Internal.Logging.SettingsException.#ctor*
  commentId: Overload:ToSic.Cre8magic.Settings.Internal.Logging.SettingsException.#ctor
  href: ToSic.Cre8magic.Settings.Internal.Logging.SettingsException.html#ToSic_Cre8magic_Settings_Internal_Logging_SettingsException__ctor_System_String_
  name: SettingsException
  nameWithType: SettingsException.SettingsException
  fullName: ToSic.Cre8magic.Settings.Internal.Logging.SettingsException.SettingsException
  nameWithType.vb: SettingsException.New
  fullName.vb: ToSic.Cre8magic.Settings.Internal.Logging.SettingsException.New
  name.vb: New
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
