### YamlMime:ManagedReference
items:
- uid: ToSic.Cre8magic.Settings.Internal.MagicSettingsCatalogsLoader
  commentId: T:ToSic.Cre8magic.Settings.Internal.MagicSettingsCatalogsLoader
  id: MagicSettingsCatalogsLoader
  parent: ToSic.Cre8magic.Settings.Internal
  children:
  - ToSic.Cre8magic.Settings.Internal.MagicSettingsCatalogsLoader.#ctor(System.Collections.Generic.IEnumerable{ToSic.Cre8magic.Settings.Internal.Sources.IMagicSettingsSource})
  - ToSic.Cre8magic.Settings.Internal.MagicSettingsCatalogsLoader.Catalogs(ToSic.Cre8magic.Themes.MagicThemePackage,System.Boolean)
  langs:
  - csharp
  - vb
  name: MagicSettingsCatalogsLoader
  nameWithType: MagicSettingsCatalogsLoader
  fullName: ToSic.Cre8magic.Settings.Internal.MagicSettingsCatalogsLoader
  type: Class
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/Internal/MagicSettingsCatalogsLoader.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: MagicSettingsCatalogsLoader
    path: ../ToSic.Cre8Magic.Client/Settings/Internal/MagicSettingsCatalogsLoader.cs
    startLine: 11
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings.Internal
  summary: >-
    Helper to load all the magic settings which could be used by the <xref href="ToSic.Cre8magic.Settings.IMagicSettingsService" data-throw-if-not-resolved="false"></xref>.


    It requires that there are <xref href="ToSic.Cre8magic.Themes.MagicThemePackage" data-throw-if-not-resolved="false"></xref> which were usually configured in the theme,

    and then passed to the SettingsService on Setup.
  example: []
  syntax:
    content: public class MagicSettingsCatalogsLoader
    content.vb: Public Class MagicSettingsCatalogsLoader
  inheritance:
  - System.Object
- uid: ToSic.Cre8magic.Settings.Internal.MagicSettingsCatalogsLoader.#ctor(System.Collections.Generic.IEnumerable{ToSic.Cre8magic.Settings.Internal.Sources.IMagicSettingsSource})
  commentId: M:ToSic.Cre8magic.Settings.Internal.MagicSettingsCatalogsLoader.#ctor(System.Collections.Generic.IEnumerable{ToSic.Cre8magic.Settings.Internal.Sources.IMagicSettingsSource})
  id: '#ctor(System.Collections.Generic.IEnumerable{ToSic.Cre8magic.Settings.Internal.Sources.IMagicSettingsSource})'
  parent: ToSic.Cre8magic.Settings.Internal.MagicSettingsCatalogsLoader
  langs:
  - csharp
  - vb
  name: MagicSettingsCatalogsLoader(IEnumerable<IMagicSettingsSource>)
  nameWithType: MagicSettingsCatalogsLoader.MagicSettingsCatalogsLoader(IEnumerable<IMagicSettingsSource>)
  fullName: ToSic.Cre8magic.Settings.Internal.MagicSettingsCatalogsLoader.MagicSettingsCatalogsLoader(System.Collections.Generic.IEnumerable<ToSic.Cre8magic.Settings.Internal.Sources.IMagicSettingsSource>)
  type: Constructor
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/Internal/MagicSettingsCatalogsLoader.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: .ctor
    path: ../ToSic.Cre8Magic.Client/Settings/Internal/MagicSettingsCatalogsLoader.cs
    startLine: 11
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings.Internal
  summary: >-
    Helper to load all the magic settings which could be used by the <xref href="ToSic.Cre8magic.Settings.IMagicSettingsService" data-throw-if-not-resolved="false"></xref>.


    It requires that there are <xref href="ToSic.Cre8magic.Themes.MagicThemePackage" data-throw-if-not-resolved="false"></xref> which were usually configured in the theme,

    and then passed to the SettingsService on Setup.
  example: []
  syntax:
    content: public MagicSettingsCatalogsLoader(IEnumerable<IMagicSettingsSource> sources)
    parameters:
    - id: sources
      type: System.Collections.Generic.IEnumerable{ToSic.Cre8magic.Settings.Internal.Sources.IMagicSettingsSource}
    content.vb: Public Sub New(sources As IEnumerable(Of IMagicSettingsSource))
  overload: ToSic.Cre8magic.Settings.Internal.MagicSettingsCatalogsLoader.#ctor*
  nameWithType.vb: MagicSettingsCatalogsLoader.New(IEnumerable(Of IMagicSettingsSource))
  fullName.vb: ToSic.Cre8magic.Settings.Internal.MagicSettingsCatalogsLoader.New(System.Collections.Generic.IEnumerable(Of ToSic.Cre8magic.Settings.Internal.Sources.IMagicSettingsSource))
  name.vb: New(IEnumerable(Of IMagicSettingsSource))
- uid: ToSic.Cre8magic.Settings.Internal.MagicSettingsCatalogsLoader.Catalogs(ToSic.Cre8magic.Themes.MagicThemePackage,System.Boolean)
  commentId: M:ToSic.Cre8magic.Settings.Internal.MagicSettingsCatalogsLoader.Catalogs(ToSic.Cre8magic.Themes.MagicThemePackage,System.Boolean)
  id: Catalogs(ToSic.Cre8magic.Themes.MagicThemePackage,System.Boolean)
  parent: ToSic.Cre8magic.Settings.Internal.MagicSettingsCatalogsLoader
  langs:
  - csharp
  - vb
  name: Catalogs(MagicThemePackage, bool)
  nameWithType: MagicSettingsCatalogsLoader.Catalogs(MagicThemePackage, bool)
  fullName: ToSic.Cre8magic.Settings.Internal.MagicSettingsCatalogsLoader.Catalogs(ToSic.Cre8magic.Themes.MagicThemePackage, bool)
  type: Method
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/Internal/MagicSettingsCatalogsLoader.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: Catalogs
    path: ../ToSic.Cre8Magic.Client/Settings/Internal/MagicSettingsCatalogsLoader.cs
    startLine: 13
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings.Internal
  syntax:
    content: public List<DataWithJournal<MagicSettingsCatalog>> Catalogs(MagicThemePackage themePackage, bool cache = true)
    parameters:
    - id: themePackage
      type: ToSic.Cre8magic.Themes.MagicThemePackage
    - id: cache
      type: System.Boolean
    return:
      type: System.Collections.Generic.List{ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal{ToSic.Cre8magic.Settings.MagicSettingsCatalog}}
    content.vb: Public Function Catalogs(themePackage As MagicThemePackage, cache As Boolean = True) As List(Of DataWithJournal(Of MagicSettingsCatalog))
  overload: ToSic.Cre8magic.Settings.Internal.MagicSettingsCatalogsLoader.Catalogs*
  nameWithType.vb: MagicSettingsCatalogsLoader.Catalogs(MagicThemePackage, Boolean)
  fullName.vb: ToSic.Cre8magic.Settings.Internal.MagicSettingsCatalogsLoader.Catalogs(ToSic.Cre8magic.Themes.MagicThemePackage, Boolean)
  name.vb: Catalogs(MagicThemePackage, Boolean)
references:
- uid: ToSic.Cre8magic.Settings.IMagicSettingsService
  commentId: T:ToSic.Cre8magic.Settings.IMagicSettingsService
  parent: ToSic.Cre8magic.Settings
  href: ToSic.Cre8magic.Settings.IMagicSettingsService.html
  name: IMagicSettingsService
  nameWithType: IMagicSettingsService
  fullName: ToSic.Cre8magic.Settings.IMagicSettingsService
- uid: ToSic.Cre8magic.Themes.MagicThemePackage
  commentId: T:ToSic.Cre8magic.Themes.MagicThemePackage
  parent: ToSic.Cre8magic.Themes
  href: ToSic.Cre8magic.Themes.MagicThemePackage.html
  name: MagicThemePackage
  nameWithType: MagicThemePackage
  fullName: ToSic.Cre8magic.Themes.MagicThemePackage
- uid: ToSic.Cre8magic.Settings.Internal
  commentId: N:ToSic.Cre8magic.Settings.Internal
  href: ToSic.html
  name: ToSic.Cre8magic.Settings.Internal
  nameWithType: ToSic.Cre8magic.Settings.Internal
  fullName: ToSic.Cre8magic.Settings.Internal
  spec.csharp:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Internal
    name: Internal
    href: ToSic.Cre8magic.Settings.Internal.html
  spec.vb:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Internal
    name: Internal
    href: ToSic.Cre8magic.Settings.Internal.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: ToSic.Cre8magic.Settings
  commentId: N:ToSic.Cre8magic.Settings
  href: ToSic.html
  name: ToSic.Cre8magic.Settings
  nameWithType: ToSic.Cre8magic.Settings
  fullName: ToSic.Cre8magic.Settings
  spec.csharp:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
  spec.vb:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
- uid: ToSic.Cre8magic.Themes
  commentId: N:ToSic.Cre8magic.Themes
  href: ToSic.html
  name: ToSic.Cre8magic.Themes
  nameWithType: ToSic.Cre8magic.Themes
  fullName: ToSic.Cre8magic.Themes
  spec.csharp:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Themes
    name: Themes
    href: ToSic.Cre8magic.Themes.html
  spec.vb:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Themes
    name: Themes
    href: ToSic.Cre8magic.Themes.html
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: ToSic.Cre8magic.Settings.Internal.MagicSettingsCatalogsLoader.#ctor*
  commentId: Overload:ToSic.Cre8magic.Settings.Internal.MagicSettingsCatalogsLoader.#ctor
  href: ToSic.Cre8magic.Settings.Internal.MagicSettingsCatalogsLoader.html#ToSic_Cre8magic_Settings_Internal_MagicSettingsCatalogsLoader__ctor_System_Collections_Generic_IEnumerable_ToSic_Cre8magic_Settings_Internal_Sources_IMagicSettingsSource__
  name: MagicSettingsCatalogsLoader
  nameWithType: MagicSettingsCatalogsLoader.MagicSettingsCatalogsLoader
  fullName: ToSic.Cre8magic.Settings.Internal.MagicSettingsCatalogsLoader.MagicSettingsCatalogsLoader
  nameWithType.vb: MagicSettingsCatalogsLoader.New
  fullName.vb: ToSic.Cre8magic.Settings.Internal.MagicSettingsCatalogsLoader.New
  name.vb: New
- uid: System.Collections.Generic.IEnumerable{ToSic.Cre8magic.Settings.Internal.Sources.IMagicSettingsSource}
  commentId: T:System.Collections.Generic.IEnumerable{ToSic.Cre8magic.Settings.Internal.Sources.IMagicSettingsSource}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IEnumerable`1
  href: ToSic.Cre8magic.Settings.Internal.Sources.IMagicSettingsSource.html
  name: IEnumerable<IMagicSettingsSource>
  nameWithType: IEnumerable<IMagicSettingsSource>
  fullName: System.Collections.Generic.IEnumerable<ToSic.Cre8magic.Settings.Internal.Sources.IMagicSettingsSource>
  nameWithType.vb: IEnumerable(Of IMagicSettingsSource)
  fullName.vb: System.Collections.Generic.IEnumerable(Of ToSic.Cre8magic.Settings.Internal.Sources.IMagicSettingsSource)
  name.vb: IEnumerable(Of IMagicSettingsSource)
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    isExternal: true
  - name: <
  - uid: ToSic.Cre8magic.Settings.Internal.Sources.IMagicSettingsSource
    name: IMagicSettingsSource
    href: ToSic.Cre8magic.Settings.Internal.Sources.IMagicSettingsSource.html
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - uid: ToSic.Cre8magic.Settings.Internal.Sources.IMagicSettingsSource
    name: IMagicSettingsSource
    href: ToSic.Cre8magic.Settings.Internal.Sources.IMagicSettingsSource.html
  - name: )
- uid: System.Collections.Generic.IEnumerable`1
  commentId: T:System.Collections.Generic.IEnumerable`1
  isExternal: true
  name: IEnumerable<T>
  nameWithType: IEnumerable<T>
  fullName: System.Collections.Generic.IEnumerable<T>
  nameWithType.vb: IEnumerable(Of T)
  fullName.vb: System.Collections.Generic.IEnumerable(Of T)
  name.vb: IEnumerable(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    isExternal: true
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
- uid: ToSic.Cre8magic.Settings.Internal.MagicSettingsCatalogsLoader.Catalogs*
  commentId: Overload:ToSic.Cre8magic.Settings.Internal.MagicSettingsCatalogsLoader.Catalogs
  href: ToSic.Cre8magic.Settings.Internal.MagicSettingsCatalogsLoader.html#ToSic_Cre8magic_Settings_Internal_MagicSettingsCatalogsLoader_Catalogs_ToSic_Cre8magic_Themes_MagicThemePackage_System_Boolean_
  name: Catalogs
  nameWithType: MagicSettingsCatalogsLoader.Catalogs
  fullName: ToSic.Cre8magic.Settings.Internal.MagicSettingsCatalogsLoader.Catalogs
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: System.Collections.Generic.List{ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal{ToSic.Cre8magic.Settings.MagicSettingsCatalog}}
  commentId: T:System.Collections.Generic.List{ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal{ToSic.Cre8magic.Settings.MagicSettingsCatalog}}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.List`1
  href: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal-1.html
  name: List<DataWithJournal<MagicSettingsCatalog>>
  nameWithType: List<DataWithJournal<MagicSettingsCatalog>>
  fullName: System.Collections.Generic.List<ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal<ToSic.Cre8magic.Settings.MagicSettingsCatalog>>
  nameWithType.vb: List(Of DataWithJournal(Of MagicSettingsCatalog))
  fullName.vb: System.Collections.Generic.List(Of ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal(Of ToSic.Cre8magic.Settings.MagicSettingsCatalog))
  name.vb: List(Of DataWithJournal(Of MagicSettingsCatalog))
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
  - name: <
  - uid: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal`1
    name: DataWithJournal
    href: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal-1.html
  - name: <
  - uid: ToSic.Cre8magic.Settings.MagicSettingsCatalog
    name: MagicSettingsCatalog
    href: ToSic.Cre8magic.Settings.MagicSettingsCatalog.html
  - name: '>'
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - uid: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal`1
    name: DataWithJournal
    href: ToSic.Cre8magic.Settings.Internal.Journal.DataWithJournal-1.html
  - name: (
  - name: Of
  - name: " "
  - uid: ToSic.Cre8magic.Settings.MagicSettingsCatalog
    name: MagicSettingsCatalog
    href: ToSic.Cre8magic.Settings.MagicSettingsCatalog.html
  - name: )
  - name: )
- uid: System.Collections.Generic.List`1
  commentId: T:System.Collections.Generic.List`1
  isExternal: true
  name: List<T>
  nameWithType: List<T>
  fullName: System.Collections.Generic.List<T>
  nameWithType.vb: List(Of T)
  fullName.vb: System.Collections.Generic.List(Of T)
  name.vb: List(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
