### YamlMime:ManagedReference
items:
- uid: ToSic.Cre8magic.Settings.Internal.Experimental.IMagicSettingsContext
  commentId: T:ToSic.Cre8magic.Settings.Internal.Experimental.IMagicSettingsContext
  id: IMagicSettingsContext
  parent: ToSic.Cre8magic.Settings.Internal.Experimental
  children:
  - ToSic.Cre8magic.Settings.Internal.Experimental.IMagicSettingsContext.FallbackToDefault
  - ToSic.Cre8magic.Settings.Internal.Experimental.IMagicSettingsContext.ModuleState
  - ToSic.Cre8magic.Settings.Internal.Experimental.IMagicSettingsContext.Name
  - ToSic.Cre8magic.Settings.Internal.Experimental.IMagicSettingsContext.PageState
  - ToSic.Cre8magic.Settings.Internal.Experimental.IMagicSettingsContext.Prefix
  langs:
  - csharp
  - vb
  name: IMagicSettingsContext
  nameWithType: IMagicSettingsContext
  fullName: ToSic.Cre8magic.Settings.Internal.Experimental.IMagicSettingsContext
  type: Interface
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/Internal/Experimental/IMagicSettingsContext.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: IMagicSettingsContext
    path: ../ToSic.Cre8Magic.Client/Settings/Internal/Experimental/IMagicSettingsContext.cs
    startLine: 5
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings.Internal.Experimental
  syntax:
    content: public interface IMagicSettingsContext
    content.vb: Public Interface IMagicSettingsContext
- uid: ToSic.Cre8magic.Settings.Internal.Experimental.IMagicSettingsContext.Name
  commentId: P:ToSic.Cre8magic.Settings.Internal.Experimental.IMagicSettingsContext.Name
  id: Name
  parent: ToSic.Cre8magic.Settings.Internal.Experimental.IMagicSettingsContext
  langs:
  - csharp
  - vb
  name: Name
  nameWithType: IMagicSettingsContext.Name
  fullName: ToSic.Cre8magic.Settings.Internal.Experimental.IMagicSettingsContext.Name
  type: Property
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/Internal/Experimental/IMagicSettingsContext.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: Name
    path: ../ToSic.Cre8Magic.Client/Settings/Internal/Experimental/IMagicSettingsContext.cs
    startLine: 12
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings.Internal.Experimental
  summary: >-
    Name of the settings - in case there are named settings to retrieve.


    Can be null, for example when the default settings are requested.
  example: []
  syntax:
    content: string? Name { get; }
    parameters: []
    return:
      type: System.String
    content.vb: ReadOnly Property Name As String
  overload: ToSic.Cre8magic.Settings.Internal.Experimental.IMagicSettingsContext.Name*
- uid: ToSic.Cre8magic.Settings.Internal.Experimental.IMagicSettingsContext.FallbackToDefault
  commentId: P:ToSic.Cre8magic.Settings.Internal.Experimental.IMagicSettingsContext.FallbackToDefault
  id: FallbackToDefault
  parent: ToSic.Cre8magic.Settings.Internal.Experimental.IMagicSettingsContext
  langs:
  - csharp
  - vb
  name: FallbackToDefault
  nameWithType: IMagicSettingsContext.FallbackToDefault
  fullName: ToSic.Cre8magic.Settings.Internal.Experimental.IMagicSettingsContext.FallbackToDefault
  type: Property
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/Internal/Experimental/IMagicSettingsContext.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: FallbackToDefault
    path: ../ToSic.Cre8Magic.Client/Settings/Internal/Experimental/IMagicSettingsContext.cs
    startLine: 14
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings.Internal.Experimental
  syntax:
    content: bool FallbackToDefault { get; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: ReadOnly Property FallbackToDefault As Boolean
  overload: ToSic.Cre8magic.Settings.Internal.Experimental.IMagicSettingsContext.FallbackToDefault*
- uid: ToSic.Cre8magic.Settings.Internal.Experimental.IMagicSettingsContext.Prefix
  commentId: P:ToSic.Cre8magic.Settings.Internal.Experimental.IMagicSettingsContext.Prefix
  id: Prefix
  parent: ToSic.Cre8magic.Settings.Internal.Experimental.IMagicSettingsContext
  langs:
  - csharp
  - vb
  name: Prefix
  nameWithType: IMagicSettingsContext.Prefix
  fullName: ToSic.Cre8magic.Settings.Internal.Experimental.IMagicSettingsContext.Prefix
  type: Property
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/Internal/Experimental/IMagicSettingsContext.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: Prefix
    path: ../ToSic.Cre8Magic.Client/Settings/Internal/Experimental/IMagicSettingsContext.cs
    startLine: 16
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings.Internal.Experimental
  syntax:
    content: string? Prefix { get; }
    parameters: []
    return:
      type: System.String
    content.vb: ReadOnly Property Prefix As String
  overload: ToSic.Cre8magic.Settings.Internal.Experimental.IMagicSettingsContext.Prefix*
- uid: ToSic.Cre8magic.Settings.Internal.Experimental.IMagicSettingsContext.PageState
  commentId: P:ToSic.Cre8magic.Settings.Internal.Experimental.IMagicSettingsContext.PageState
  id: PageState
  parent: ToSic.Cre8magic.Settings.Internal.Experimental.IMagicSettingsContext
  langs:
  - csharp
  - vb
  name: PageState
  nameWithType: IMagicSettingsContext.PageState
  fullName: ToSic.Cre8magic.Settings.Internal.Experimental.IMagicSettingsContext.PageState
  type: Property
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/Internal/Experimental/IMagicSettingsContext.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: PageState
    path: ../ToSic.Cre8Magic.Client/Settings/Internal/Experimental/IMagicSettingsContext.cs
    startLine: 21
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings.Internal.Experimental
  summary: The Page State, which could be used to deliver alternate settings depending on the page.
  example: []
  syntax:
    content: PageState? PageState { get; }
    parameters: []
    return:
      type: Oqtane.UI.PageState
    content.vb: ReadOnly Property PageState As PageState
  overload: ToSic.Cre8magic.Settings.Internal.Experimental.IMagicSettingsContext.PageState*
- uid: ToSic.Cre8magic.Settings.Internal.Experimental.IMagicSettingsContext.ModuleState
  commentId: P:ToSic.Cre8magic.Settings.Internal.Experimental.IMagicSettingsContext.ModuleState
  id: ModuleState
  parent: ToSic.Cre8magic.Settings.Internal.Experimental.IMagicSettingsContext
  langs:
  - csharp
  - vb
  name: ModuleState
  nameWithType: IMagicSettingsContext.ModuleState
  fullName: ToSic.Cre8magic.Settings.Internal.Experimental.IMagicSettingsContext.ModuleState
  type: Property
  source:
    remote:
      path: ToSic.Cre8Magic.Client/Settings/Internal/Experimental/IMagicSettingsContext.cs
      branch: feature/v5
      repo: https://github.com/2sic/oqtane-cre8magic
    id: ModuleState
    path: ../ToSic.Cre8Magic.Client/Settings/Internal/Experimental/IMagicSettingsContext.cs
    startLine: 29
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Settings.Internal.Experimental
  summary: >-
    The Module State, which could be used to deliver alternate settings depending on the module.


    Can be null, if the settings are not related to a module.

    For example, Login Settings.
  example: []
  syntax:
    content: Module? ModuleState { get; }
    parameters: []
    return:
      type: Oqtane.Models.Module
    content.vb: ReadOnly Property ModuleState As [Module]
  overload: ToSic.Cre8magic.Settings.Internal.Experimental.IMagicSettingsContext.ModuleState*
references:
- uid: ToSic.Cre8magic.Settings.Internal.Experimental
  commentId: N:ToSic.Cre8magic.Settings.Internal.Experimental
  href: ToSic.html
  name: ToSic.Cre8magic.Settings.Internal.Experimental
  nameWithType: ToSic.Cre8magic.Settings.Internal.Experimental
  fullName: ToSic.Cre8magic.Settings.Internal.Experimental
  spec.csharp:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Internal
    name: Internal
    href: ToSic.Cre8magic.Settings.Internal.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Internal.Experimental
    name: Experimental
    href: ToSic.Cre8magic.Settings.Internal.Experimental.html
  spec.vb:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Settings
    name: Settings
    href: ToSic.Cre8magic.Settings.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Internal
    name: Internal
    href: ToSic.Cre8magic.Settings.Internal.html
  - name: .
  - uid: ToSic.Cre8magic.Settings.Internal.Experimental
    name: Experimental
    href: ToSic.Cre8magic.Settings.Internal.Experimental.html
- uid: ToSic.Cre8magic.Settings.Internal.Experimental.IMagicSettingsContext.Name*
  commentId: Overload:ToSic.Cre8magic.Settings.Internal.Experimental.IMagicSettingsContext.Name
  href: ToSic.Cre8magic.Settings.Internal.Experimental.IMagicSettingsContext.html#ToSic_Cre8magic_Settings_Internal_Experimental_IMagicSettingsContext_Name
  name: Name
  nameWithType: IMagicSettingsContext.Name
  fullName: ToSic.Cre8magic.Settings.Internal.Experimental.IMagicSettingsContext.Name
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: ToSic.Cre8magic.Settings.Internal.Experimental.IMagicSettingsContext.FallbackToDefault*
  commentId: Overload:ToSic.Cre8magic.Settings.Internal.Experimental.IMagicSettingsContext.FallbackToDefault
  href: ToSic.Cre8magic.Settings.Internal.Experimental.IMagicSettingsContext.html#ToSic_Cre8magic_Settings_Internal_Experimental_IMagicSettingsContext_FallbackToDefault
  name: FallbackToDefault
  nameWithType: IMagicSettingsContext.FallbackToDefault
  fullName: ToSic.Cre8magic.Settings.Internal.Experimental.IMagicSettingsContext.FallbackToDefault
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: ToSic.Cre8magic.Settings.Internal.Experimental.IMagicSettingsContext.Prefix*
  commentId: Overload:ToSic.Cre8magic.Settings.Internal.Experimental.IMagicSettingsContext.Prefix
  href: ToSic.Cre8magic.Settings.Internal.Experimental.IMagicSettingsContext.html#ToSic_Cre8magic_Settings_Internal_Experimental_IMagicSettingsContext_Prefix
  name: Prefix
  nameWithType: IMagicSettingsContext.Prefix
  fullName: ToSic.Cre8magic.Settings.Internal.Experimental.IMagicSettingsContext.Prefix
- uid: ToSic.Cre8magic.Settings.Internal.Experimental.IMagicSettingsContext.PageState*
  commentId: Overload:ToSic.Cre8magic.Settings.Internal.Experimental.IMagicSettingsContext.PageState
  href: ToSic.Cre8magic.Settings.Internal.Experimental.IMagicSettingsContext.html#ToSic_Cre8magic_Settings_Internal_Experimental_IMagicSettingsContext_PageState
  name: PageState
  nameWithType: IMagicSettingsContext.PageState
  fullName: ToSic.Cre8magic.Settings.Internal.Experimental.IMagicSettingsContext.PageState
- uid: Oqtane.UI.PageState
  commentId: T:Oqtane.UI.PageState
  parent: Oqtane.UI
  isExternal: true
  href: https://github.com/sbwalker/oqtane.framework/blob/5e9567158f0f5ea11a746a02b9359695423d7608/Oqtane.Client/UI/PageState.cs
  name: PageState
  nameWithType: PageState
  fullName: Oqtane.UI.PageState
- uid: Oqtane.UI
  commentId: N:Oqtane.UI
  isExternal: true
  name: Oqtane.UI
  nameWithType: Oqtane.UI
  fullName: Oqtane.UI
  spec.csharp:
  - uid: Oqtane
    name: Oqtane
    isExternal: true
  - name: .
  - uid: Oqtane.UI
    name: UI
    isExternal: true
  spec.vb:
  - uid: Oqtane
    name: Oqtane
    isExternal: true
  - name: .
  - uid: Oqtane.UI
    name: UI
    isExternal: true
- uid: ToSic.Cre8magic.Settings.Internal.Experimental.IMagicSettingsContext.ModuleState*
  commentId: Overload:ToSic.Cre8magic.Settings.Internal.Experimental.IMagicSettingsContext.ModuleState
  href: ToSic.Cre8magic.Settings.Internal.Experimental.IMagicSettingsContext.html#ToSic_Cre8magic_Settings_Internal_Experimental_IMagicSettingsContext_ModuleState
  name: ModuleState
  nameWithType: IMagicSettingsContext.ModuleState
  fullName: ToSic.Cre8magic.Settings.Internal.Experimental.IMagicSettingsContext.ModuleState
- uid: Oqtane.Models.Module
  commentId: T:Oqtane.Models.Module
  parent: Oqtane.Models
  name: Module
  nameWithType: Module
  fullName: Oqtane.Models.Module
- uid: Oqtane.Models
  commentId: N:Oqtane.Models
  name: Oqtane.Models
  nameWithType: Oqtane.Models
  fullName: Oqtane.Models
  spec.csharp:
  - uid: Oqtane
    name: Oqtane
  - name: .
  - uid: Oqtane.Models
    name: Models
  spec.vb:
  - uid: Oqtane
    name: Oqtane
  - name: .
  - uid: Oqtane.Models
    name: Models
