### YamlMime:ManagedReference
items:
- uid: ToSic.Cre8magic.Menus.Settings
  commentId: N:ToSic.Cre8magic.Menus.Settings
  id: Settings
  parent: ToSic.Cre8magic.Menus
  children:
  - ToSic.Cre8magic.Menus.Settings.MagicMenuDesigner
  langs:
  - csharp
  - vb
  name: ToSic.Cre8magic.Menus.Settings
  nameWithType: ToSic.Cre8magic.Menus.Settings
  fullName: ToSic.Cre8magic.Menus.Settings
  type: Namespace
  assemblies:
  - ToSic.Cre8magic.Client.Oqtane
references:
- uid: ToSic.Cre8magic.Menus.Settings.MagicMenuDesigner
  commentId: T:ToSic.Cre8magic.Menus.Settings.MagicMenuDesigner
  href: ToSic.Cre8magic.Menus.Settings.MagicMenuDesigner.html
  name: MagicMenuDesigner
  nameWithType: MagicMenuDesigner
  fullName: ToSic.Cre8magic.Menus.Settings.MagicMenuDesigner
